package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpCanInvoiceTbId generated by hbm2java
 */
@Embeddable
public class ShpCanInvoiceTbId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal canInvoiceId;
	private BigDecimal primaryReference;
	private String originCity;
	private String originState;
	private String originZipCode;
	private String originCountry;
	private String destCity;
	private String destState;
	private String destZipCode;
	private String destCountry;
	private Date targetShipDate;
	private BigDecimal weight;
	private String class_;
	private String createUser;
	private Date createDate;
	private String lastUpdateUser;
	private Date lastUpdateDate;
	private BigDecimal status;

	public ShpCanInvoiceTbId() {
	}

	public ShpCanInvoiceTbId(BigDecimal canInvoiceId, BigDecimal primaryReference, String originCity,
			String originState, String originZipCode, String originCountry, String destCity, String destState,
			String destZipCode, String destCountry, Date targetShipDate, BigDecimal weight, String class_,
			String createUser, Date createDate, String lastUpdateUser, Date lastUpdateDate, BigDecimal status) {
		this.canInvoiceId = canInvoiceId;
		this.primaryReference = primaryReference;
		this.originCity = originCity;
		this.originState = originState;
		this.originZipCode = originZipCode;
		this.originCountry = originCountry;
		this.destCity = destCity;
		this.destState = destState;
		this.destZipCode = destZipCode;
		this.destCountry = destCountry;
		this.targetShipDate = targetShipDate;
		this.weight = weight;
		this.class_ = class_;
		this.createUser = createUser;
		this.createDate = createDate;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.status = status;
	}

	@Column(name = "CAN_INVOICE_ID", precision = 22, scale = 0)
	public BigDecimal getCanInvoiceId() {
		return this.canInvoiceId;
	}

	public void setCanInvoiceId(BigDecimal canInvoiceId) {
		this.canInvoiceId = canInvoiceId;
	}

	@Column(name = "PRIMARY_REFERENCE", precision = 22, scale = 0)
	public BigDecimal getPrimaryReference() {
		return this.primaryReference;
	}

	public void setPrimaryReference(BigDecimal primaryReference) {
		this.primaryReference = primaryReference;
	}

	@Column(name = "ORIGIN_CITY", length = 500)
	public String getOriginCity() {
		return this.originCity;
	}

	public void setOriginCity(String originCity) {
		this.originCity = originCity;
	}

	@Column(name = "ORIGIN_STATE", length = 500)
	public String getOriginState() {
		return this.originState;
	}

	public void setOriginState(String originState) {
		this.originState = originState;
	}

	@Column(name = "ORIGIN_ZIP_CODE", length = 500)
	public String getOriginZipCode() {
		return this.originZipCode;
	}

	public void setOriginZipCode(String originZipCode) {
		this.originZipCode = originZipCode;
	}

	@Column(name = "ORIGIN_COUNTRY", length = 500)
	public String getOriginCountry() {
		return this.originCountry;
	}

	public void setOriginCountry(String originCountry) {
		this.originCountry = originCountry;
	}

	@Column(name = "DEST_CITY", length = 500)
	public String getDestCity() {
		return this.destCity;
	}

	public void setDestCity(String destCity) {
		this.destCity = destCity;
	}

	@Column(name = "DEST_STATE", length = 500)
	public String getDestState() {
		return this.destState;
	}

	public void setDestState(String destState) {
		this.destState = destState;
	}

	@Column(name = "DEST_ZIP_CODE", length = 500)
	public String getDestZipCode() {
		return this.destZipCode;
	}

	public void setDestZipCode(String destZipCode) {
		this.destZipCode = destZipCode;
	}

	@Column(name = "DEST_COUNTRY", length = 500)
	public String getDestCountry() {
		return this.destCountry;
	}

	public void setDestCountry(String destCountry) {
		this.destCountry = destCountry;
	}

	@Column(name = "TARGET_SHIP_DATE", length = 7)
	public Date getTargetShipDate() {
		return this.targetShipDate;
	}

	public void setTargetShipDate(Date targetShipDate) {
		this.targetShipDate = targetShipDate;
	}

	@Column(name = "WEIGHT", precision = 22, scale = 0)
	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	@Column(name = "CLASS", length = 500)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "CREATE_USER", length = 500)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "LAST_UPDATE_USER", length = 500)
	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpCanInvoiceTbId))
			return false;
		ShpCanInvoiceTbId castOther = (ShpCanInvoiceTbId) other;

		return ((this.getCanInvoiceId() == castOther.getCanInvoiceId()) || (this.getCanInvoiceId() != null
				&& castOther.getCanInvoiceId() != null && this.getCanInvoiceId().equals(castOther.getCanInvoiceId())))
				&& ((this.getPrimaryReference() == castOther.getPrimaryReference())
						|| (this.getPrimaryReference() != null && castOther.getPrimaryReference() != null
								&& this.getPrimaryReference().equals(castOther.getPrimaryReference())))
				&& ((this.getOriginCity() == castOther.getOriginCity()) || (this.getOriginCity() != null
						&& castOther.getOriginCity() != null && this.getOriginCity().equals(castOther.getOriginCity())))
				&& ((this.getOriginState() == castOther.getOriginState())
						|| (this.getOriginState() != null && castOther.getOriginState() != null
								&& this.getOriginState().equals(castOther.getOriginState())))
				&& ((this.getOriginZipCode() == castOther.getOriginZipCode())
						|| (this.getOriginZipCode() != null && castOther.getOriginZipCode() != null
								&& this.getOriginZipCode().equals(castOther.getOriginZipCode())))
				&& ((this.getOriginCountry() == castOther.getOriginCountry())
						|| (this.getOriginCountry() != null && castOther.getOriginCountry() != null
								&& this.getOriginCountry().equals(castOther.getOriginCountry())))
				&& ((this.getDestCity() == castOther.getDestCity()) || (this.getDestCity() != null
						&& castOther.getDestCity() != null && this.getDestCity().equals(castOther.getDestCity())))
				&& ((this.getDestState() == castOther.getDestState()) || (this.getDestState() != null
						&& castOther.getDestState() != null && this.getDestState().equals(castOther.getDestState())))
				&& ((this.getDestZipCode() == castOther.getDestZipCode())
						|| (this.getDestZipCode() != null && castOther.getDestZipCode() != null
								&& this.getDestZipCode().equals(castOther.getDestZipCode())))
				&& ((this.getDestCountry() == castOther.getDestCountry())
						|| (this.getDestCountry() != null && castOther.getDestCountry() != null
								&& this.getDestCountry().equals(castOther.getDestCountry())))
				&& ((this.getTargetShipDate() == castOther.getTargetShipDate())
						|| (this.getTargetShipDate() != null && castOther.getTargetShipDate() != null
								&& this.getTargetShipDate().equals(castOther.getTargetShipDate())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())))
				&& ((this.getClass_() == castOther.getClass_()) || (this.getClass_() != null
						&& castOther.getClass_() != null && this.getClass_().equals(castOther.getClass_())))
				&& ((this.getCreateUser() == castOther.getCreateUser()) || (this.getCreateUser() != null
						&& castOther.getCreateUser() != null && this.getCreateUser().equals(castOther.getCreateUser())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser())
						|| (this.getLastUpdateUser() != null && castOther.getLastUpdateUser() != null
								&& this.getLastUpdateUser().equals(castOther.getLastUpdateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate())
						|| (this.getLastUpdateDate() != null && castOther.getLastUpdateDate() != null
								&& this.getLastUpdateDate().equals(castOther.getLastUpdateDate())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCanInvoiceId() == null ? 0 : this.getCanInvoiceId().hashCode());
		result = 37 * result + (getPrimaryReference() == null ? 0 : this.getPrimaryReference().hashCode());
		result = 37 * result + (getOriginCity() == null ? 0 : this.getOriginCity().hashCode());
		result = 37 * result + (getOriginState() == null ? 0 : this.getOriginState().hashCode());
		result = 37 * result + (getOriginZipCode() == null ? 0 : this.getOriginZipCode().hashCode());
		result = 37 * result + (getOriginCountry() == null ? 0 : this.getOriginCountry().hashCode());
		result = 37 * result + (getDestCity() == null ? 0 : this.getDestCity().hashCode());
		result = 37 * result + (getDestState() == null ? 0 : this.getDestState().hashCode());
		result = 37 * result + (getDestZipCode() == null ? 0 : this.getDestZipCode().hashCode());
		result = 37 * result + (getDestCountry() == null ? 0 : this.getDestCountry().hashCode());
		result = 37 * result + (getTargetShipDate() == null ? 0 : this.getTargetShipDate().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		result = 37 * result + (getClass_() == null ? 0 : this.getClass_().hashCode());
		result = 37 * result + (getCreateUser() == null ? 0 : this.getCreateUser().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser().hashCode());
		result = 37 * result + (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
