package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpCustomerByUserVwId generated by hbm2java
 */
@Embeddable
public class ShpCustomerByUserVwId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal customerId;
	private String customerCode;
	private String customerName;
	private String customerDescription;
	private String address1;
	private String city;
	private String state;
	private String country;
	private String zipcode;
	private String phone;
	private String fax;
	private String email;
	private String address2;
	private Boolean isActive;
	private Boolean addToDb;
	private Boolean lateManifest;
	private BigDecimal userId;
	private BigDecimal mbaClient;
	private BigDecimal useTranCount;
	private BigDecimal shipdateOnOrigin;
	private BigDecimal fedexGroundGsrOnline;
	private BigDecimal fedexExpressGsrOnline;
	private String emailUpsFromAddress;
	private String emailUpsToAddress;
	private Date emailUpsGsrDate;
	private BigDecimal emailUpsGsrFlag;
	private BigDecimal emailUpsInvoiceFlag;
	private Date emailUpsInvoiceDate;
	private BigDecimal poolPoint;
	private Date createdOn;
	private String createdBy;
	private Date updatedOn;
	private String updatedBy;
	private BigDecimal businessPartnerId;
	private BigDecimal markup;
	private BigDecimal showPubRates;
	private BigDecimal markupType;
	private BigDecimal upsGsrFlag;
	private String fdxPaymentOption;
	private BigDecimal shipperUniqShGrp;
	private BigDecimal poolPointUps;
	private BigDecimal fdxExpressDelayTime;
	private BigDecimal fdxIntlDelayTime;
	private BigDecimal upsExpressDelayTime;
	private BigDecimal upsIntlDelayTime;
	private BigDecimal parentCustomerId;
	private String dhlUserName;
	private String dhlPassword;
	private BigDecimal fedexOnlineFiling;
	private BigDecimal fdxGroundDelayTime;
	private BigDecimal tolerance;
	private BigDecimal aboveToleranceLimit;
	private BigDecimal belowToleranceLimit;
	private BigDecimal toleranceUnit;
	private String primaryBussiness;
	private BigDecimal assignedAuditor;
	private BigDecimal billpayDayOfWeek;
	private BigDecimal isBillpay;
	private BigDecimal isGlNull;
	private BigDecimal nspDaysForPay;
	private BigDecimal paidCust;
	private BigDecimal fedexCloseCycle;
	private String receiverId;
	private BigDecimal isParcelAudit;
	private BigDecimal isNspAudit;
	private BigDecimal isParcelBillpay;
	private Date engageDate;
	private BigDecimal customerStatusId;
	private Boolean upsOmitVoidAudit;
	private Boolean upsOmitAdcAudit;
	private Boolean upsOmitSatAudit;
	private Boolean upsOmitResAudit;
	private String upsNotes;
	private Boolean fedexRemittanceFlag;
	private BigDecimal fedexEdiType;
	private String fedexNotes;
	private Boolean upsOmitDupAudit;
	private BigDecimal upsResDelay;
	private BigDecimal upsSatDelay;
	private BigDecimal upsVoidDelay;
	private BigDecimal upsAdcDelay;
	private BigDecimal upsDupDelay;
	private BigDecimal fdxPickupScanAsOriginZip;
	private BigDecimal fedexCloseDayOfWeek;
	private BigDecimal loadOnlyIntl;
	private String upsComments;
	private BigDecimal glcodeMethod;
	private String customerDefinedName1;
	private String customerDefinedName2;
	private String customerDefinedName3;
	private BigDecimal upsShortPay;
	private BigDecimal upsVoidInDays;
	private Date upsEngageDate;
	private Date fedexEngageDate;
	private Date dhlEngageDate;
	private Date freightEngageDate;
	private BigDecimal upsInvoices;
	private BigDecimal loadConsolidation;
	private String poFormat;
	private String nextAvailablePo;
	private String customerNumber;
	private String glCodeFormat;
	private String costCenterNumberFormat;
	private Boolean isParcelGlNull;
	private BigDecimal residentialAuditForFreight;
	private BigDecimal brokerageParent;
	private Boolean brokerageParentType;
	private Boolean brokerageChildType;
	private BigDecimal nspGroupCustomerId;
	private BigDecimal custQaPercent;
	private BigDecimal custQaPercentCounter;
	private BigDecimal uplift;
	private BigDecimal glcodingAttempt;
	private BigDecimal podRequired;
	private BigDecimal canParcel;
	private BigDecimal canFreight;
	private BigDecimal domesticCurrency;
	private BigDecimal invoicedOnTransactionFee;
	private String pcmilerVersion;
	private String upsPaymentOption;
	private String dhlPaymentOption;
	private BigDecimal payrunBasedOn;
	private BigDecimal validateMultistopQty;
	private BigDecimal emeaCustomerFlag;

	public ShpCustomerByUserVwId() {
	}

	public ShpCustomerByUserVwId(BigDecimal customerId, String customerCode, String customerName,
			String customerDescription, String address1, String city, String state, String country, String zipcode,
			String phone, String fax, String email, String address2, Boolean isActive, Boolean addToDb,
			Boolean lateManifest, BigDecimal userId, BigDecimal mbaClient, BigDecimal useTranCount,
			BigDecimal shipdateOnOrigin, BigDecimal fedexGroundGsrOnline, BigDecimal fedexExpressGsrOnline,
			String emailUpsFromAddress, String emailUpsToAddress, Date emailUpsGsrDate, BigDecimal emailUpsGsrFlag,
			BigDecimal emailUpsInvoiceFlag, Date emailUpsInvoiceDate, BigDecimal poolPoint, Date createdOn,
			String createdBy, Date updatedOn, String updatedBy, BigDecimal businessPartnerId, BigDecimal markup,
			BigDecimal showPubRates, BigDecimal markupType, BigDecimal upsGsrFlag, String fdxPaymentOption,
			BigDecimal shipperUniqShGrp, BigDecimal poolPointUps, BigDecimal fdxExpressDelayTime,
			BigDecimal fdxIntlDelayTime, BigDecimal upsExpressDelayTime, BigDecimal upsIntlDelayTime,
			BigDecimal parentCustomerId, String dhlUserName, String dhlPassword, BigDecimal fedexOnlineFiling,
			BigDecimal fdxGroundDelayTime, BigDecimal tolerance, BigDecimal aboveToleranceLimit,
			BigDecimal belowToleranceLimit, BigDecimal toleranceUnit, String primaryBussiness,
			BigDecimal assignedAuditor, BigDecimal billpayDayOfWeek, BigDecimal isBillpay, BigDecimal isGlNull,
			BigDecimal nspDaysForPay, BigDecimal paidCust, BigDecimal fedexCloseCycle, String receiverId,
			BigDecimal isParcelAudit, BigDecimal isNspAudit, BigDecimal isParcelBillpay, Date engageDate,
			BigDecimal customerStatusId, Boolean upsOmitVoidAudit, Boolean upsOmitAdcAudit, Boolean upsOmitSatAudit,
			Boolean upsOmitResAudit, String upsNotes, Boolean fedexRemittanceFlag, BigDecimal fedexEdiType,
			String fedexNotes, Boolean upsOmitDupAudit, BigDecimal upsResDelay, BigDecimal upsSatDelay,
			BigDecimal upsVoidDelay, BigDecimal upsAdcDelay, BigDecimal upsDupDelay,
			BigDecimal fdxPickupScanAsOriginZip, BigDecimal fedexCloseDayOfWeek, BigDecimal loadOnlyIntl,
			String upsComments, BigDecimal glcodeMethod, String customerDefinedName1, String customerDefinedName2,
			String customerDefinedName3, BigDecimal upsShortPay, BigDecimal upsVoidInDays, Date upsEngageDate,
			Date fedexEngageDate, Date dhlEngageDate, Date freightEngageDate, BigDecimal upsInvoices,
			BigDecimal loadConsolidation, String poFormat, String nextAvailablePo, String customerNumber,
			String glCodeFormat, String costCenterNumberFormat, Boolean isParcelGlNull,
			BigDecimal residentialAuditForFreight, BigDecimal brokerageParent, Boolean brokerageParentType,
			Boolean brokerageChildType, BigDecimal nspGroupCustomerId, BigDecimal custQaPercent,
			BigDecimal custQaPercentCounter, BigDecimal uplift, BigDecimal glcodingAttempt, BigDecimal podRequired,
			BigDecimal canParcel, BigDecimal canFreight, BigDecimal domesticCurrency,
			BigDecimal invoicedOnTransactionFee, String pcmilerVersion, String upsPaymentOption,
			String dhlPaymentOption, BigDecimal payrunBasedOn, BigDecimal validateMultistopQty,
			BigDecimal emeaCustomerFlag) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.customerName = customerName;
		this.customerDescription = customerDescription;
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.country = country;
		this.zipcode = zipcode;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.address2 = address2;
		this.isActive = isActive;
		this.addToDb = addToDb;
		this.lateManifest = lateManifest;
		this.userId = userId;
		this.mbaClient = mbaClient;
		this.useTranCount = useTranCount;
		this.shipdateOnOrigin = shipdateOnOrigin;
		this.fedexGroundGsrOnline = fedexGroundGsrOnline;
		this.fedexExpressGsrOnline = fedexExpressGsrOnline;
		this.emailUpsFromAddress = emailUpsFromAddress;
		this.emailUpsToAddress = emailUpsToAddress;
		this.emailUpsGsrDate = emailUpsGsrDate;
		this.emailUpsGsrFlag = emailUpsGsrFlag;
		this.emailUpsInvoiceFlag = emailUpsInvoiceFlag;
		this.emailUpsInvoiceDate = emailUpsInvoiceDate;
		this.poolPoint = poolPoint;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.updatedOn = updatedOn;
		this.updatedBy = updatedBy;
		this.businessPartnerId = businessPartnerId;
		this.markup = markup;
		this.showPubRates = showPubRates;
		this.markupType = markupType;
		this.upsGsrFlag = upsGsrFlag;
		this.fdxPaymentOption = fdxPaymentOption;
		this.shipperUniqShGrp = shipperUniqShGrp;
		this.poolPointUps = poolPointUps;
		this.fdxExpressDelayTime = fdxExpressDelayTime;
		this.fdxIntlDelayTime = fdxIntlDelayTime;
		this.upsExpressDelayTime = upsExpressDelayTime;
		this.upsIntlDelayTime = upsIntlDelayTime;
		this.parentCustomerId = parentCustomerId;
		this.dhlUserName = dhlUserName;
		this.dhlPassword = dhlPassword;
		this.fedexOnlineFiling = fedexOnlineFiling;
		this.fdxGroundDelayTime = fdxGroundDelayTime;
		this.tolerance = tolerance;
		this.aboveToleranceLimit = aboveToleranceLimit;
		this.belowToleranceLimit = belowToleranceLimit;
		this.toleranceUnit = toleranceUnit;
		this.primaryBussiness = primaryBussiness;
		this.assignedAuditor = assignedAuditor;
		this.billpayDayOfWeek = billpayDayOfWeek;
		this.isBillpay = isBillpay;
		this.isGlNull = isGlNull;
		this.nspDaysForPay = nspDaysForPay;
		this.paidCust = paidCust;
		this.fedexCloseCycle = fedexCloseCycle;
		this.receiverId = receiverId;
		this.isParcelAudit = isParcelAudit;
		this.isNspAudit = isNspAudit;
		this.isParcelBillpay = isParcelBillpay;
		this.engageDate = engageDate;
		this.customerStatusId = customerStatusId;
		this.upsOmitVoidAudit = upsOmitVoidAudit;
		this.upsOmitAdcAudit = upsOmitAdcAudit;
		this.upsOmitSatAudit = upsOmitSatAudit;
		this.upsOmitResAudit = upsOmitResAudit;
		this.upsNotes = upsNotes;
		this.fedexRemittanceFlag = fedexRemittanceFlag;
		this.fedexEdiType = fedexEdiType;
		this.fedexNotes = fedexNotes;
		this.upsOmitDupAudit = upsOmitDupAudit;
		this.upsResDelay = upsResDelay;
		this.upsSatDelay = upsSatDelay;
		this.upsVoidDelay = upsVoidDelay;
		this.upsAdcDelay = upsAdcDelay;
		this.upsDupDelay = upsDupDelay;
		this.fdxPickupScanAsOriginZip = fdxPickupScanAsOriginZip;
		this.fedexCloseDayOfWeek = fedexCloseDayOfWeek;
		this.loadOnlyIntl = loadOnlyIntl;
		this.upsComments = upsComments;
		this.glcodeMethod = glcodeMethod;
		this.customerDefinedName1 = customerDefinedName1;
		this.customerDefinedName2 = customerDefinedName2;
		this.customerDefinedName3 = customerDefinedName3;
		this.upsShortPay = upsShortPay;
		this.upsVoidInDays = upsVoidInDays;
		this.upsEngageDate = upsEngageDate;
		this.fedexEngageDate = fedexEngageDate;
		this.dhlEngageDate = dhlEngageDate;
		this.freightEngageDate = freightEngageDate;
		this.upsInvoices = upsInvoices;
		this.loadConsolidation = loadConsolidation;
		this.poFormat = poFormat;
		this.nextAvailablePo = nextAvailablePo;
		this.customerNumber = customerNumber;
		this.glCodeFormat = glCodeFormat;
		this.costCenterNumberFormat = costCenterNumberFormat;
		this.isParcelGlNull = isParcelGlNull;
		this.residentialAuditForFreight = residentialAuditForFreight;
		this.brokerageParent = brokerageParent;
		this.brokerageParentType = brokerageParentType;
		this.brokerageChildType = brokerageChildType;
		this.nspGroupCustomerId = nspGroupCustomerId;
		this.custQaPercent = custQaPercent;
		this.custQaPercentCounter = custQaPercentCounter;
		this.uplift = uplift;
		this.glcodingAttempt = glcodingAttempt;
		this.podRequired = podRequired;
		this.canParcel = canParcel;
		this.canFreight = canFreight;
		this.domesticCurrency = domesticCurrency;
		this.invoicedOnTransactionFee = invoicedOnTransactionFee;
		this.pcmilerVersion = pcmilerVersion;
		this.upsPaymentOption = upsPaymentOption;
		this.dhlPaymentOption = dhlPaymentOption;
		this.payrunBasedOn = payrunBasedOn;
		this.validateMultistopQty = validateMultistopQty;
		this.emeaCustomerFlag = emeaCustomerFlag;
	}

	@Column(name = "CUSTOMER_ID", precision = 22, scale = 0)
	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CUSTOMER_CODE", length = 10)
	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	@Column(name = "CUSTOMER_NAME", length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "CUSTOMER_DESCRIPTION", length = 100)
	public String getCustomerDescription() {
		return this.customerDescription;
	}

	public void setCustomerDescription(String customerDescription) {
		this.customerDescription = customerDescription;
	}

	@Column(name = "ADDRESS1", length = 100)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "CITY", length = 40)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", length = 30)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ZIPCODE", length = 10)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "PHONE", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "EMAIL", length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ADDRESS2", length = 100)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "IS_ACTIVE", precision = 1, scale = 0)
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "ADD_TO_DB", precision = 1, scale = 0)
	public Boolean getAddToDb() {
		return this.addToDb;
	}

	public void setAddToDb(Boolean addToDb) {
		this.addToDb = addToDb;
	}

	@Column(name = "LATE_MANIFEST", precision = 1, scale = 0)
	public Boolean getLateManifest() {
		return this.lateManifest;
	}

	public void setLateManifest(Boolean lateManifest) {
		this.lateManifest = lateManifest;
	}

	@Column(name = "USER_ID", precision = 22, scale = 0)
	public BigDecimal getUserId() {
		return this.userId;
	}

	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	@Column(name = "MBA_CLIENT", precision = 22, scale = 0)
	public BigDecimal getMbaClient() {
		return this.mbaClient;
	}

	public void setMbaClient(BigDecimal mbaClient) {
		this.mbaClient = mbaClient;
	}

	@Column(name = "USE_TRAN_COUNT", precision = 22, scale = 0)
	public BigDecimal getUseTranCount() {
		return this.useTranCount;
	}

	public void setUseTranCount(BigDecimal useTranCount) {
		this.useTranCount = useTranCount;
	}

	@Column(name = "SHIPDATE_ON_ORIGIN", precision = 22, scale = 0)
	public BigDecimal getShipdateOnOrigin() {
		return this.shipdateOnOrigin;
	}

	public void setShipdateOnOrigin(BigDecimal shipdateOnOrigin) {
		this.shipdateOnOrigin = shipdateOnOrigin;
	}

	@Column(name = "FEDEX_GROUND_GSR_ONLINE", precision = 22, scale = 0)
	public BigDecimal getFedexGroundGsrOnline() {
		return this.fedexGroundGsrOnline;
	}

	public void setFedexGroundGsrOnline(BigDecimal fedexGroundGsrOnline) {
		this.fedexGroundGsrOnline = fedexGroundGsrOnline;
	}

	@Column(name = "FEDEX_EXPRESS_GSR_ONLINE", precision = 22, scale = 0)
	public BigDecimal getFedexExpressGsrOnline() {
		return this.fedexExpressGsrOnline;
	}

	public void setFedexExpressGsrOnline(BigDecimal fedexExpressGsrOnline) {
		this.fedexExpressGsrOnline = fedexExpressGsrOnline;
	}

	@Column(name = "EMAIL_UPS_FROM_ADDRESS", length = 200)
	public String getEmailUpsFromAddress() {
		return this.emailUpsFromAddress;
	}

	public void setEmailUpsFromAddress(String emailUpsFromAddress) {
		this.emailUpsFromAddress = emailUpsFromAddress;
	}

	@Column(name = "EMAIL_UPS_TO_ADDRESS", length = 200)
	public String getEmailUpsToAddress() {
		return this.emailUpsToAddress;
	}

	public void setEmailUpsToAddress(String emailUpsToAddress) {
		this.emailUpsToAddress = emailUpsToAddress;
	}

	@Column(name = "EMAIL_UPS_GSR_DATE", length = 7)
	public Date getEmailUpsGsrDate() {
		return this.emailUpsGsrDate;
	}

	public void setEmailUpsGsrDate(Date emailUpsGsrDate) {
		this.emailUpsGsrDate = emailUpsGsrDate;
	}

	@Column(name = "EMAIL_UPS_GSR_FLAG", precision = 22, scale = 0)
	public BigDecimal getEmailUpsGsrFlag() {
		return this.emailUpsGsrFlag;
	}

	public void setEmailUpsGsrFlag(BigDecimal emailUpsGsrFlag) {
		this.emailUpsGsrFlag = emailUpsGsrFlag;
	}

	@Column(name = "EMAIL_UPS_INVOICE_FLAG", precision = 22, scale = 0)
	public BigDecimal getEmailUpsInvoiceFlag() {
		return this.emailUpsInvoiceFlag;
	}

	public void setEmailUpsInvoiceFlag(BigDecimal emailUpsInvoiceFlag) {
		this.emailUpsInvoiceFlag = emailUpsInvoiceFlag;
	}

	@Column(name = "EMAIL_UPS_INVOICE_DATE", length = 7)
	public Date getEmailUpsInvoiceDate() {
		return this.emailUpsInvoiceDate;
	}

	public void setEmailUpsInvoiceDate(Date emailUpsInvoiceDate) {
		this.emailUpsInvoiceDate = emailUpsInvoiceDate;
	}

	@Column(name = "POOL_POINT", precision = 22, scale = 0)
	public BigDecimal getPoolPoint() {
		return this.poolPoint;
	}

	public void setPoolPoint(BigDecimal poolPoint) {
		this.poolPoint = poolPoint;
	}

	@Column(name = "CREATED_ON", length = 7)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "CREATED_BY", length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "UPDATED_ON", length = 7)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "UPDATED_BY", length = 15)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "BUSINESS_PARTNER_ID", precision = 22, scale = 0)
	public BigDecimal getBusinessPartnerId() {
		return this.businessPartnerId;
	}

	public void setBusinessPartnerId(BigDecimal businessPartnerId) {
		this.businessPartnerId = businessPartnerId;
	}

	@Column(name = "MARKUP", precision = 22, scale = 0)
	public BigDecimal getMarkup() {
		return this.markup;
	}

	public void setMarkup(BigDecimal markup) {
		this.markup = markup;
	}

	@Column(name = "SHOW_PUB_RATES", precision = 22, scale = 0)
	public BigDecimal getShowPubRates() {
		return this.showPubRates;
	}

	public void setShowPubRates(BigDecimal showPubRates) {
		this.showPubRates = showPubRates;
	}

	@Column(name = "MARKUP_TYPE", precision = 22, scale = 0)
	public BigDecimal getMarkupType() {
		return this.markupType;
	}

	public void setMarkupType(BigDecimal markupType) {
		this.markupType = markupType;
	}

	@Column(name = "UPS_GSR_FLAG", precision = 22, scale = 0)
	public BigDecimal getUpsGsrFlag() {
		return this.upsGsrFlag;
	}

	public void setUpsGsrFlag(BigDecimal upsGsrFlag) {
		this.upsGsrFlag = upsGsrFlag;
	}

	@Column(name = "FDX_PAYMENT_OPTION", length = 1)
	public String getFdxPaymentOption() {
		return this.fdxPaymentOption;
	}

	public void setFdxPaymentOption(String fdxPaymentOption) {
		this.fdxPaymentOption = fdxPaymentOption;
	}

	@Column(name = "SHIPPER_UNIQ_SH_GRP", precision = 22, scale = 0)
	public BigDecimal getShipperUniqShGrp() {
		return this.shipperUniqShGrp;
	}

	public void setShipperUniqShGrp(BigDecimal shipperUniqShGrp) {
		this.shipperUniqShGrp = shipperUniqShGrp;
	}

	@Column(name = "POOL_POINT_UPS", precision = 22, scale = 0)
	public BigDecimal getPoolPointUps() {
		return this.poolPointUps;
	}

	public void setPoolPointUps(BigDecimal poolPointUps) {
		this.poolPointUps = poolPointUps;
	}

	@Column(name = "FDX_EXPRESS_DELAY_TIME", precision = 22, scale = 0)
	public BigDecimal getFdxExpressDelayTime() {
		return this.fdxExpressDelayTime;
	}

	public void setFdxExpressDelayTime(BigDecimal fdxExpressDelayTime) {
		this.fdxExpressDelayTime = fdxExpressDelayTime;
	}

	@Column(name = "FDX_INTL_DELAY_TIME", precision = 22, scale = 0)
	public BigDecimal getFdxIntlDelayTime() {
		return this.fdxIntlDelayTime;
	}

	public void setFdxIntlDelayTime(BigDecimal fdxIntlDelayTime) {
		this.fdxIntlDelayTime = fdxIntlDelayTime;
	}

	@Column(name = "UPS_EXPRESS_DELAY_TIME", precision = 22, scale = 0)
	public BigDecimal getUpsExpressDelayTime() {
		return this.upsExpressDelayTime;
	}

	public void setUpsExpressDelayTime(BigDecimal upsExpressDelayTime) {
		this.upsExpressDelayTime = upsExpressDelayTime;
	}

	@Column(name = "UPS_INTL_DELAY_TIME", precision = 22, scale = 0)
	public BigDecimal getUpsIntlDelayTime() {
		return this.upsIntlDelayTime;
	}

	public void setUpsIntlDelayTime(BigDecimal upsIntlDelayTime) {
		this.upsIntlDelayTime = upsIntlDelayTime;
	}

	@Column(name = "PARENT_CUSTOMER_ID", precision = 22, scale = 0)
	public BigDecimal getParentCustomerId() {
		return this.parentCustomerId;
	}

	public void setParentCustomerId(BigDecimal parentCustomerId) {
		this.parentCustomerId = parentCustomerId;
	}

	@Column(name = "DHL_USER_NAME", length = 50)
	public String getDhlUserName() {
		return this.dhlUserName;
	}

	public void setDhlUserName(String dhlUserName) {
		this.dhlUserName = dhlUserName;
	}

	@Column(name = "DHL_PASSWORD", length = 50)
	public String getDhlPassword() {
		return this.dhlPassword;
	}

	public void setDhlPassword(String dhlPassword) {
		this.dhlPassword = dhlPassword;
	}

	@Column(name = "FEDEX_ONLINE_FILING", precision = 22, scale = 0)
	public BigDecimal getFedexOnlineFiling() {
		return this.fedexOnlineFiling;
	}

	public void setFedexOnlineFiling(BigDecimal fedexOnlineFiling) {
		this.fedexOnlineFiling = fedexOnlineFiling;
	}

	@Column(name = "FDX_GROUND_DELAY_TIME", precision = 22, scale = 0)
	public BigDecimal getFdxGroundDelayTime() {
		return this.fdxGroundDelayTime;
	}

	public void setFdxGroundDelayTime(BigDecimal fdxGroundDelayTime) {
		this.fdxGroundDelayTime = fdxGroundDelayTime;
	}

	@Column(name = "TOLERANCE", precision = 22, scale = 0)
	public BigDecimal getTolerance() {
		return this.tolerance;
	}

	public void setTolerance(BigDecimal tolerance) {
		this.tolerance = tolerance;
	}

	@Column(name = "ABOVE_TOLERANCE_LIMIT", precision = 22, scale = 0)
	public BigDecimal getAboveToleranceLimit() {
		return this.aboveToleranceLimit;
	}

	public void setAboveToleranceLimit(BigDecimal aboveToleranceLimit) {
		this.aboveToleranceLimit = aboveToleranceLimit;
	}

	@Column(name = "BELOW_TOLERANCE_LIMIT", precision = 22, scale = 0)
	public BigDecimal getBelowToleranceLimit() {
		return this.belowToleranceLimit;
	}

	public void setBelowToleranceLimit(BigDecimal belowToleranceLimit) {
		this.belowToleranceLimit = belowToleranceLimit;
	}

	@Column(name = "TOLERANCE_UNIT", precision = 22, scale = 0)
	public BigDecimal getToleranceUnit() {
		return this.toleranceUnit;
	}

	public void setToleranceUnit(BigDecimal toleranceUnit) {
		this.toleranceUnit = toleranceUnit;
	}

	@Column(name = "PRIMARY_BUSSINESS", length = 150)
	public String getPrimaryBussiness() {
		return this.primaryBussiness;
	}

	public void setPrimaryBussiness(String primaryBussiness) {
		this.primaryBussiness = primaryBussiness;
	}

	@Column(name = "ASSIGNED_AUDITOR", precision = 22, scale = 0)
	public BigDecimal getAssignedAuditor() {
		return this.assignedAuditor;
	}

	public void setAssignedAuditor(BigDecimal assignedAuditor) {
		this.assignedAuditor = assignedAuditor;
	}

	@Column(name = "BILLPAY_DAY_OF_WEEK", precision = 22, scale = 0)
	public BigDecimal getBillpayDayOfWeek() {
		return this.billpayDayOfWeek;
	}

	public void setBillpayDayOfWeek(BigDecimal billpayDayOfWeek) {
		this.billpayDayOfWeek = billpayDayOfWeek;
	}

	@Column(name = "IS_BILLPAY", precision = 22, scale = 0)
	public BigDecimal getIsBillpay() {
		return this.isBillpay;
	}

	public void setIsBillpay(BigDecimal isBillpay) {
		this.isBillpay = isBillpay;
	}

	@Column(name = "IS_GL_NULL", precision = 22, scale = 0)
	public BigDecimal getIsGlNull() {
		return this.isGlNull;
	}

	public void setIsGlNull(BigDecimal isGlNull) {
		this.isGlNull = isGlNull;
	}

	@Column(name = "NSP_DAYS_FOR_PAY", precision = 22, scale = 0)
	public BigDecimal getNspDaysForPay() {
		return this.nspDaysForPay;
	}

	public void setNspDaysForPay(BigDecimal nspDaysForPay) {
		this.nspDaysForPay = nspDaysForPay;
	}

	@Column(name = "PAID_CUST", precision = 22, scale = 0)
	public BigDecimal getPaidCust() {
		return this.paidCust;
	}

	public void setPaidCust(BigDecimal paidCust) {
		this.paidCust = paidCust;
	}

	@Column(name = "FEDEX_CLOSE_CYCLE", precision = 22, scale = 0)
	public BigDecimal getFedexCloseCycle() {
		return this.fedexCloseCycle;
	}

	public void setFedexCloseCycle(BigDecimal fedexCloseCycle) {
		this.fedexCloseCycle = fedexCloseCycle;
	}

	@Column(name = "RECEIVER_ID", length = 15)
	public String getReceiverId() {
		return this.receiverId;
	}

	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

	@Column(name = "IS_PARCEL_AUDIT", precision = 22, scale = 0)
	public BigDecimal getIsParcelAudit() {
		return this.isParcelAudit;
	}

	public void setIsParcelAudit(BigDecimal isParcelAudit) {
		this.isParcelAudit = isParcelAudit;
	}

	@Column(name = "IS_NSP_AUDIT", precision = 22, scale = 0)
	public BigDecimal getIsNspAudit() {
		return this.isNspAudit;
	}

	public void setIsNspAudit(BigDecimal isNspAudit) {
		this.isNspAudit = isNspAudit;
	}

	@Column(name = "IS_PARCEL_BILLPAY", precision = 22, scale = 0)
	public BigDecimal getIsParcelBillpay() {
		return this.isParcelBillpay;
	}

	public void setIsParcelBillpay(BigDecimal isParcelBillpay) {
		this.isParcelBillpay = isParcelBillpay;
	}

	@Column(name = "ENGAGE_DATE", length = 7)
	public Date getEngageDate() {
		return this.engageDate;
	}

	public void setEngageDate(Date engageDate) {
		this.engageDate = engageDate;
	}

	@Column(name = "CUSTOMER_STATUS_ID", precision = 22, scale = 0)
	public BigDecimal getCustomerStatusId() {
		return this.customerStatusId;
	}

	public void setCustomerStatusId(BigDecimal customerStatusId) {
		this.customerStatusId = customerStatusId;
	}

	@Column(name = "UPS_OMIT_VOID_AUDIT", precision = 1, scale = 0)
	public Boolean getUpsOmitVoidAudit() {
		return this.upsOmitVoidAudit;
	}

	public void setUpsOmitVoidAudit(Boolean upsOmitVoidAudit) {
		this.upsOmitVoidAudit = upsOmitVoidAudit;
	}

	@Column(name = "UPS_OMIT_ADC_AUDIT", precision = 1, scale = 0)
	public Boolean getUpsOmitAdcAudit() {
		return this.upsOmitAdcAudit;
	}

	public void setUpsOmitAdcAudit(Boolean upsOmitAdcAudit) {
		this.upsOmitAdcAudit = upsOmitAdcAudit;
	}

	@Column(name = "UPS_OMIT_SAT_AUDIT", precision = 1, scale = 0)
	public Boolean getUpsOmitSatAudit() {
		return this.upsOmitSatAudit;
	}

	public void setUpsOmitSatAudit(Boolean upsOmitSatAudit) {
		this.upsOmitSatAudit = upsOmitSatAudit;
	}

	@Column(name = "UPS_OMIT_RES_AUDIT", precision = 1, scale = 0)
	public Boolean getUpsOmitResAudit() {
		return this.upsOmitResAudit;
	}

	public void setUpsOmitResAudit(Boolean upsOmitResAudit) {
		this.upsOmitResAudit = upsOmitResAudit;
	}

	@Column(name = "UPS_NOTES", length = 400)
	public String getUpsNotes() {
		return this.upsNotes;
	}

	public void setUpsNotes(String upsNotes) {
		this.upsNotes = upsNotes;
	}

	@Column(name = "FEDEX_REMITTANCE_FLAG", precision = 1, scale = 0)
	public Boolean getFedexRemittanceFlag() {
		return this.fedexRemittanceFlag;
	}

	public void setFedexRemittanceFlag(Boolean fedexRemittanceFlag) {
		this.fedexRemittanceFlag = fedexRemittanceFlag;
	}

	@Column(name = "FEDEX_EDI_TYPE", precision = 22, scale = 0)
	public BigDecimal getFedexEdiType() {
		return this.fedexEdiType;
	}

	public void setFedexEdiType(BigDecimal fedexEdiType) {
		this.fedexEdiType = fedexEdiType;
	}

	@Column(name = "FEDEX_NOTES", length = 400)
	public String getFedexNotes() {
		return this.fedexNotes;
	}

	public void setFedexNotes(String fedexNotes) {
		this.fedexNotes = fedexNotes;
	}

	@Column(name = "UPS_OMIT_DUP_AUDIT", precision = 1, scale = 0)
	public Boolean getUpsOmitDupAudit() {
		return this.upsOmitDupAudit;
	}

	public void setUpsOmitDupAudit(Boolean upsOmitDupAudit) {
		this.upsOmitDupAudit = upsOmitDupAudit;
	}

	@Column(name = "UPS_RES_DELAY", precision = 22, scale = 0)
	public BigDecimal getUpsResDelay() {
		return this.upsResDelay;
	}

	public void setUpsResDelay(BigDecimal upsResDelay) {
		this.upsResDelay = upsResDelay;
	}

	@Column(name = "UPS_SAT_DELAY", precision = 22, scale = 0)
	public BigDecimal getUpsSatDelay() {
		return this.upsSatDelay;
	}

	public void setUpsSatDelay(BigDecimal upsSatDelay) {
		this.upsSatDelay = upsSatDelay;
	}

	@Column(name = "UPS_VOID_DELAY", precision = 22, scale = 0)
	public BigDecimal getUpsVoidDelay() {
		return this.upsVoidDelay;
	}

	public void setUpsVoidDelay(BigDecimal upsVoidDelay) {
		this.upsVoidDelay = upsVoidDelay;
	}

	@Column(name = "UPS_ADC_DELAY", precision = 22, scale = 0)
	public BigDecimal getUpsAdcDelay() {
		return this.upsAdcDelay;
	}

	public void setUpsAdcDelay(BigDecimal upsAdcDelay) {
		this.upsAdcDelay = upsAdcDelay;
	}

	@Column(name = "UPS_DUP_DELAY", precision = 22, scale = 0)
	public BigDecimal getUpsDupDelay() {
		return this.upsDupDelay;
	}

	public void setUpsDupDelay(BigDecimal upsDupDelay) {
		this.upsDupDelay = upsDupDelay;
	}

	@Column(name = "FDX_PICKUP_SCAN_AS_ORIGIN_ZIP", precision = 22, scale = 0)
	public BigDecimal getFdxPickupScanAsOriginZip() {
		return this.fdxPickupScanAsOriginZip;
	}

	public void setFdxPickupScanAsOriginZip(BigDecimal fdxPickupScanAsOriginZip) {
		this.fdxPickupScanAsOriginZip = fdxPickupScanAsOriginZip;
	}

	@Column(name = "FEDEX_CLOSE_DAY_OF_WEEK", precision = 22, scale = 0)
	public BigDecimal getFedexCloseDayOfWeek() {
		return this.fedexCloseDayOfWeek;
	}

	public void setFedexCloseDayOfWeek(BigDecimal fedexCloseDayOfWeek) {
		this.fedexCloseDayOfWeek = fedexCloseDayOfWeek;
	}

	@Column(name = "LOAD_ONLY_INTL", precision = 22, scale = 0)
	public BigDecimal getLoadOnlyIntl() {
		return this.loadOnlyIntl;
	}

	public void setLoadOnlyIntl(BigDecimal loadOnlyIntl) {
		this.loadOnlyIntl = loadOnlyIntl;
	}

	@Column(name = "UPS_COMMENTS", length = 400)
	public String getUpsComments() {
		return this.upsComments;
	}

	public void setUpsComments(String upsComments) {
		this.upsComments = upsComments;
	}

	@Column(name = "GLCODE_METHOD", precision = 22, scale = 0)
	public BigDecimal getGlcodeMethod() {
		return this.glcodeMethod;
	}

	public void setGlcodeMethod(BigDecimal glcodeMethod) {
		this.glcodeMethod = glcodeMethod;
	}

	@Column(name = "CUSTOMER_DEFINED_NAME1", length = 50)
	public String getCustomerDefinedName1() {
		return this.customerDefinedName1;
	}

	public void setCustomerDefinedName1(String customerDefinedName1) {
		this.customerDefinedName1 = customerDefinedName1;
	}

	@Column(name = "CUSTOMER_DEFINED_NAME2", length = 50)
	public String getCustomerDefinedName2() {
		return this.customerDefinedName2;
	}

	public void setCustomerDefinedName2(String customerDefinedName2) {
		this.customerDefinedName2 = customerDefinedName2;
	}

	@Column(name = "CUSTOMER_DEFINED_NAME3", length = 50)
	public String getCustomerDefinedName3() {
		return this.customerDefinedName3;
	}

	public void setCustomerDefinedName3(String customerDefinedName3) {
		this.customerDefinedName3 = customerDefinedName3;
	}

	@Column(name = "UPS_SHORT_PAY", precision = 22, scale = 0)
	public BigDecimal getUpsShortPay() {
		return this.upsShortPay;
	}

	public void setUpsShortPay(BigDecimal upsShortPay) {
		this.upsShortPay = upsShortPay;
	}

	@Column(name = "UPS_VOID_IN_DAYS", precision = 22, scale = 0)
	public BigDecimal getUpsVoidInDays() {
		return this.upsVoidInDays;
	}

	public void setUpsVoidInDays(BigDecimal upsVoidInDays) {
		this.upsVoidInDays = upsVoidInDays;
	}

	@Column(name = "UPS_ENGAGE_DATE", length = 7)
	public Date getUpsEngageDate() {
		return this.upsEngageDate;
	}

	public void setUpsEngageDate(Date upsEngageDate) {
		this.upsEngageDate = upsEngageDate;
	}

	@Column(name = "FEDEX_ENGAGE_DATE", length = 7)
	public Date getFedexEngageDate() {
		return this.fedexEngageDate;
	}

	public void setFedexEngageDate(Date fedexEngageDate) {
		this.fedexEngageDate = fedexEngageDate;
	}

	@Column(name = "DHL_ENGAGE_DATE", length = 7)
	public Date getDhlEngageDate() {
		return this.dhlEngageDate;
	}

	public void setDhlEngageDate(Date dhlEngageDate) {
		this.dhlEngageDate = dhlEngageDate;
	}

	@Column(name = "FREIGHT_ENGAGE_DATE", length = 7)
	public Date getFreightEngageDate() {
		return this.freightEngageDate;
	}

	public void setFreightEngageDate(Date freightEngageDate) {
		this.freightEngageDate = freightEngageDate;
	}

	@Column(name = "UPS_INVOICES", precision = 22, scale = 0)
	public BigDecimal getUpsInvoices() {
		return this.upsInvoices;
	}

	public void setUpsInvoices(BigDecimal upsInvoices) {
		this.upsInvoices = upsInvoices;
	}

	@Column(name = "LOAD_CONSOLIDATION", precision = 22, scale = 0)
	public BigDecimal getLoadConsolidation() {
		return this.loadConsolidation;
	}

	public void setLoadConsolidation(BigDecimal loadConsolidation) {
		this.loadConsolidation = loadConsolidation;
	}

	@Column(name = "PO_FORMAT", length = 500)
	public String getPoFormat() {
		return this.poFormat;
	}

	public void setPoFormat(String poFormat) {
		this.poFormat = poFormat;
	}

	@Column(name = "NEXT_AVAILABLE_PO", length = 500)
	public String getNextAvailablePo() {
		return this.nextAvailablePo;
	}

	public void setNextAvailablePo(String nextAvailablePo) {
		this.nextAvailablePo = nextAvailablePo;
	}

	@Column(name = "CUSTOMER_NUMBER", length = 100)
	public String getCustomerNumber() {
		return this.customerNumber;
	}

	public void setCustomerNumber(String customerNumber) {
		this.customerNumber = customerNumber;
	}

	@Column(name = "GL_CODE_FORMAT", length = 100)
	public String getGlCodeFormat() {
		return this.glCodeFormat;
	}

	public void setGlCodeFormat(String glCodeFormat) {
		this.glCodeFormat = glCodeFormat;
	}

	@Column(name = "COST_CENTER_NUMBER_FORMAT", length = 500)
	public String getCostCenterNumberFormat() {
		return this.costCenterNumberFormat;
	}

	public void setCostCenterNumberFormat(String costCenterNumberFormat) {
		this.costCenterNumberFormat = costCenterNumberFormat;
	}

	@Column(name = "IS_PARCEL_GL_NULL", precision = 1, scale = 0)
	public Boolean getIsParcelGlNull() {
		return this.isParcelGlNull;
	}

	public void setIsParcelGlNull(Boolean isParcelGlNull) {
		this.isParcelGlNull = isParcelGlNull;
	}

	@Column(name = "RESIDENTIAL_AUDIT_FOR_FREIGHT", precision = 22, scale = 0)
	public BigDecimal getResidentialAuditForFreight() {
		return this.residentialAuditForFreight;
	}

	public void setResidentialAuditForFreight(BigDecimal residentialAuditForFreight) {
		this.residentialAuditForFreight = residentialAuditForFreight;
	}

	@Column(name = "BROKERAGE_PARENT", precision = 22, scale = 0)
	public BigDecimal getBrokerageParent() {
		return this.brokerageParent;
	}

	public void setBrokerageParent(BigDecimal brokerageParent) {
		this.brokerageParent = brokerageParent;
	}

	@Column(name = "BROKERAGE_PARENT_TYPE", precision = 1, scale = 0)
	public Boolean getBrokerageParentType() {
		return this.brokerageParentType;
	}

	public void setBrokerageParentType(Boolean brokerageParentType) {
		this.brokerageParentType = brokerageParentType;
	}

	@Column(name = "BROKERAGE_CHILD_TYPE", precision = 1, scale = 0)
	public Boolean getBrokerageChildType() {
		return this.brokerageChildType;
	}

	public void setBrokerageChildType(Boolean brokerageChildType) {
		this.brokerageChildType = brokerageChildType;
	}

	@Column(name = "NSP_GROUP_CUSTOMER_ID", precision = 22, scale = 0)
	public BigDecimal getNspGroupCustomerId() {
		return this.nspGroupCustomerId;
	}

	public void setNspGroupCustomerId(BigDecimal nspGroupCustomerId) {
		this.nspGroupCustomerId = nspGroupCustomerId;
	}

	@Column(name = "CUST_QA_PERCENT", precision = 22, scale = 0)
	public BigDecimal getCustQaPercent() {
		return this.custQaPercent;
	}

	public void setCustQaPercent(BigDecimal custQaPercent) {
		this.custQaPercent = custQaPercent;
	}

	@Column(name = "CUST_QA_PERCENT_COUNTER", precision = 22, scale = 0)
	public BigDecimal getCustQaPercentCounter() {
		return this.custQaPercentCounter;
	}

	public void setCustQaPercentCounter(BigDecimal custQaPercentCounter) {
		this.custQaPercentCounter = custQaPercentCounter;
	}

	@Column(name = "UPLIFT", precision = 22, scale = 0)
	public BigDecimal getUplift() {
		return this.uplift;
	}

	public void setUplift(BigDecimal uplift) {
		this.uplift = uplift;
	}

	@Column(name = "GLCODING_ATTEMPT", precision = 22, scale = 0)
	public BigDecimal getGlcodingAttempt() {
		return this.glcodingAttempt;
	}

	public void setGlcodingAttempt(BigDecimal glcodingAttempt) {
		this.glcodingAttempt = glcodingAttempt;
	}

	@Column(name = "POD_REQUIRED", precision = 22, scale = 0)
	public BigDecimal getPodRequired() {
		return this.podRequired;
	}

	public void setPodRequired(BigDecimal podRequired) {
		this.podRequired = podRequired;
	}

	@Column(name = "CAN_PARCEL", precision = 22, scale = 0)
	public BigDecimal getCanParcel() {
		return this.canParcel;
	}

	public void setCanParcel(BigDecimal canParcel) {
		this.canParcel = canParcel;
	}

	@Column(name = "CAN_FREIGHT", precision = 22, scale = 0)
	public BigDecimal getCanFreight() {
		return this.canFreight;
	}

	public void setCanFreight(BigDecimal canFreight) {
		this.canFreight = canFreight;
	}

	@Column(name = "DOMESTIC_CURRENCY", precision = 22, scale = 0)
	public BigDecimal getDomesticCurrency() {
		return this.domesticCurrency;
	}

	public void setDomesticCurrency(BigDecimal domesticCurrency) {
		this.domesticCurrency = domesticCurrency;
	}

	@Column(name = "INVOICED_ON_TRANSACTION_FEE", precision = 22, scale = 0)
	public BigDecimal getInvoicedOnTransactionFee() {
		return this.invoicedOnTransactionFee;
	}

	public void setInvoicedOnTransactionFee(BigDecimal invoicedOnTransactionFee) {
		this.invoicedOnTransactionFee = invoicedOnTransactionFee;
	}

	@Column(name = "PCMILER_VERSION", length = 20)
	public String getPcmilerVersion() {
		return this.pcmilerVersion;
	}

	public void setPcmilerVersion(String pcmilerVersion) {
		this.pcmilerVersion = pcmilerVersion;
	}

	@Column(name = "UPS_PAYMENT_OPTION", length = 1)
	public String getUpsPaymentOption() {
		return this.upsPaymentOption;
	}

	public void setUpsPaymentOption(String upsPaymentOption) {
		this.upsPaymentOption = upsPaymentOption;
	}

	@Column(name = "DHL_PAYMENT_OPTION", length = 1)
	public String getDhlPaymentOption() {
		return this.dhlPaymentOption;
	}

	public void setDhlPaymentOption(String dhlPaymentOption) {
		this.dhlPaymentOption = dhlPaymentOption;
	}

	@Column(name = "PAYRUN_BASED_ON", precision = 22, scale = 0)
	public BigDecimal getPayrunBasedOn() {
		return this.payrunBasedOn;
	}

	public void setPayrunBasedOn(BigDecimal payrunBasedOn) {
		this.payrunBasedOn = payrunBasedOn;
	}

	@Column(name = "VALIDATE_MULTISTOP_QTY", precision = 22, scale = 0)
	public BigDecimal getValidateMultistopQty() {
		return this.validateMultistopQty;
	}

	public void setValidateMultistopQty(BigDecimal validateMultistopQty) {
		this.validateMultistopQty = validateMultistopQty;
	}

	@Column(name = "EMEA_CUSTOMER_FLAG", precision = 22, scale = 0)
	public BigDecimal getEmeaCustomerFlag() {
		return this.emeaCustomerFlag;
	}

	public void setEmeaCustomerFlag(BigDecimal emeaCustomerFlag) {
		this.emeaCustomerFlag = emeaCustomerFlag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpCustomerByUserVwId))
			return false;
		ShpCustomerByUserVwId castOther = (ShpCustomerByUserVwId) other;

		return ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
				&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCustomerCode() == castOther.getCustomerCode())
						|| (this.getCustomerCode() != null && castOther.getCustomerCode() != null
								&& this.getCustomerCode().equals(castOther.getCustomerCode())))
				&& ((this.getCustomerName() == castOther.getCustomerName())
						|| (this.getCustomerName() != null && castOther.getCustomerName() != null
								&& this.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getCustomerDescription() == castOther.getCustomerDescription())
						|| (this.getCustomerDescription() != null && castOther.getCustomerDescription() != null
								&& this.getCustomerDescription().equals(castOther.getCustomerDescription())))
				&& ((this.getAddress1() == castOther.getAddress1()) || (this.getAddress1() != null
						&& castOther.getAddress1() != null && this.getAddress1().equals(castOther.getAddress1())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getZipcode() == castOther.getZipcode()) || (this.getZipcode() != null
						&& castOther.getZipcode() != null && this.getZipcode().equals(castOther.getZipcode())))
				&& ((this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone().equals(castOther.getPhone())))
				&& ((this.getFax() == castOther.getFax()) || (this.getFax() != null && castOther.getFax() != null
						&& this.getFax().equals(castOther.getFax())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getAddress2() == castOther.getAddress2()) || (this.getAddress2() != null
						&& castOther.getAddress2() != null && this.getAddress2().equals(castOther.getAddress2())))
				&& ((this.getIsActive() == castOther.getIsActive()) || (this.getIsActive() != null
						&& castOther.getIsActive() != null && this.getIsActive().equals(castOther.getIsActive())))
				&& ((this.getAddToDb() == castOther.getAddToDb()) || (this.getAddToDb() != null
						&& castOther.getAddToDb() != null && this.getAddToDb().equals(castOther.getAddToDb())))
				&& ((this.getLateManifest() == castOther.getLateManifest())
						|| (this.getLateManifest() != null && castOther.getLateManifest() != null
								&& this.getLateManifest().equals(castOther.getLateManifest())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getMbaClient() == castOther.getMbaClient()) || (this.getMbaClient() != null
						&& castOther.getMbaClient() != null && this.getMbaClient().equals(castOther.getMbaClient())))
				&& ((this.getUseTranCount() == castOther.getUseTranCount())
						|| (this.getUseTranCount() != null && castOther.getUseTranCount() != null
								&& this.getUseTranCount().equals(castOther.getUseTranCount())))
				&& ((this.getShipdateOnOrigin() == castOther.getShipdateOnOrigin())
						|| (this.getShipdateOnOrigin() != null && castOther.getShipdateOnOrigin() != null
								&& this.getShipdateOnOrigin().equals(castOther.getShipdateOnOrigin())))
				&& ((this.getFedexGroundGsrOnline() == castOther.getFedexGroundGsrOnline())
						|| (this.getFedexGroundGsrOnline() != null && castOther.getFedexGroundGsrOnline() != null
								&& this.getFedexGroundGsrOnline().equals(castOther.getFedexGroundGsrOnline())))
				&& ((this.getFedexExpressGsrOnline() == castOther.getFedexExpressGsrOnline())
						|| (this.getFedexExpressGsrOnline() != null && castOther.getFedexExpressGsrOnline() != null
								&& this.getFedexExpressGsrOnline().equals(castOther.getFedexExpressGsrOnline())))
				&& ((this.getEmailUpsFromAddress() == castOther.getEmailUpsFromAddress())
						|| (this.getEmailUpsFromAddress() != null && castOther.getEmailUpsFromAddress() != null
								&& this.getEmailUpsFromAddress().equals(castOther.getEmailUpsFromAddress())))
				&& ((this.getEmailUpsToAddress() == castOther.getEmailUpsToAddress())
						|| (this.getEmailUpsToAddress() != null && castOther.getEmailUpsToAddress() != null
								&& this.getEmailUpsToAddress().equals(castOther.getEmailUpsToAddress())))
				&& ((this.getEmailUpsGsrDate() == castOther.getEmailUpsGsrDate())
						|| (this.getEmailUpsGsrDate() != null && castOther.getEmailUpsGsrDate() != null
								&& this.getEmailUpsGsrDate().equals(castOther.getEmailUpsGsrDate())))
				&& ((this.getEmailUpsGsrFlag() == castOther.getEmailUpsGsrFlag())
						|| (this.getEmailUpsGsrFlag() != null && castOther.getEmailUpsGsrFlag() != null
								&& this.getEmailUpsGsrFlag().equals(castOther.getEmailUpsGsrFlag())))
				&& ((this.getEmailUpsInvoiceFlag() == castOther.getEmailUpsInvoiceFlag())
						|| (this.getEmailUpsInvoiceFlag() != null && castOther.getEmailUpsInvoiceFlag() != null
								&& this.getEmailUpsInvoiceFlag().equals(castOther.getEmailUpsInvoiceFlag())))
				&& ((this.getEmailUpsInvoiceDate() == castOther.getEmailUpsInvoiceDate())
						|| (this.getEmailUpsInvoiceDate() != null && castOther.getEmailUpsInvoiceDate() != null
								&& this.getEmailUpsInvoiceDate().equals(castOther.getEmailUpsInvoiceDate())))
				&& ((this.getPoolPoint() == castOther.getPoolPoint()) || (this.getPoolPoint() != null
						&& castOther.getPoolPoint() != null && this.getPoolPoint().equals(castOther.getPoolPoint())))
				&& ((this.getCreatedOn() == castOther.getCreatedOn()) || (this.getCreatedOn() != null
						&& castOther.getCreatedOn() != null && this.getCreatedOn().equals(castOther.getCreatedOn())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getUpdatedOn() == castOther.getUpdatedOn()) || (this.getUpdatedOn() != null
						&& castOther.getUpdatedOn() != null && this.getUpdatedOn().equals(castOther.getUpdatedOn())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())))
				&& ((this.getBusinessPartnerId() == castOther.getBusinessPartnerId())
						|| (this.getBusinessPartnerId() != null && castOther.getBusinessPartnerId() != null
								&& this.getBusinessPartnerId().equals(castOther.getBusinessPartnerId())))
				&& ((this.getMarkup() == castOther.getMarkup()) || (this.getMarkup() != null
						&& castOther.getMarkup() != null && this.getMarkup().equals(castOther.getMarkup())))
				&& ((this.getShowPubRates() == castOther.getShowPubRates())
						|| (this.getShowPubRates() != null && castOther.getShowPubRates() != null
								&& this.getShowPubRates().equals(castOther.getShowPubRates())))
				&& ((this.getMarkupType() == castOther.getMarkupType()) || (this.getMarkupType() != null
						&& castOther.getMarkupType() != null && this.getMarkupType().equals(castOther.getMarkupType())))
				&& ((this.getUpsGsrFlag() == castOther.getUpsGsrFlag()) || (this.getUpsGsrFlag() != null
						&& castOther.getUpsGsrFlag() != null && this.getUpsGsrFlag().equals(castOther.getUpsGsrFlag())))
				&& ((this.getFdxPaymentOption() == castOther.getFdxPaymentOption())
						|| (this.getFdxPaymentOption() != null && castOther.getFdxPaymentOption() != null
								&& this.getFdxPaymentOption().equals(castOther.getFdxPaymentOption())))
				&& ((this.getShipperUniqShGrp() == castOther.getShipperUniqShGrp())
						|| (this.getShipperUniqShGrp() != null && castOther.getShipperUniqShGrp() != null
								&& this.getShipperUniqShGrp().equals(castOther.getShipperUniqShGrp())))
				&& ((this.getPoolPointUps() == castOther.getPoolPointUps())
						|| (this.getPoolPointUps() != null && castOther.getPoolPointUps() != null
								&& this.getPoolPointUps().equals(castOther.getPoolPointUps())))
				&& ((this.getFdxExpressDelayTime() == castOther.getFdxExpressDelayTime())
						|| (this.getFdxExpressDelayTime() != null && castOther.getFdxExpressDelayTime() != null
								&& this.getFdxExpressDelayTime().equals(castOther.getFdxExpressDelayTime())))
				&& ((this.getFdxIntlDelayTime() == castOther.getFdxIntlDelayTime())
						|| (this.getFdxIntlDelayTime() != null && castOther.getFdxIntlDelayTime() != null
								&& this.getFdxIntlDelayTime().equals(castOther.getFdxIntlDelayTime())))
				&& ((this.getUpsExpressDelayTime() == castOther.getUpsExpressDelayTime())
						|| (this.getUpsExpressDelayTime() != null && castOther.getUpsExpressDelayTime() != null
								&& this.getUpsExpressDelayTime().equals(castOther.getUpsExpressDelayTime())))
				&& ((this.getUpsIntlDelayTime() == castOther.getUpsIntlDelayTime())
						|| (this.getUpsIntlDelayTime() != null && castOther.getUpsIntlDelayTime() != null
								&& this.getUpsIntlDelayTime().equals(castOther.getUpsIntlDelayTime())))
				&& ((this.getParentCustomerId() == castOther.getParentCustomerId())
						|| (this.getParentCustomerId() != null && castOther.getParentCustomerId() != null
								&& this.getParentCustomerId().equals(castOther.getParentCustomerId())))
				&& ((this.getDhlUserName() == castOther.getDhlUserName())
						|| (this.getDhlUserName() != null && castOther.getDhlUserName() != null
								&& this.getDhlUserName().equals(castOther.getDhlUserName())))
				&& ((this.getDhlPassword() == castOther.getDhlPassword())
						|| (this.getDhlPassword() != null && castOther.getDhlPassword() != null
								&& this.getDhlPassword().equals(castOther.getDhlPassword())))
				&& ((this.getFedexOnlineFiling() == castOther.getFedexOnlineFiling())
						|| (this.getFedexOnlineFiling() != null && castOther.getFedexOnlineFiling() != null
								&& this.getFedexOnlineFiling().equals(castOther.getFedexOnlineFiling())))
				&& ((this.getFdxGroundDelayTime() == castOther.getFdxGroundDelayTime())
						|| (this.getFdxGroundDelayTime() != null && castOther.getFdxGroundDelayTime() != null
								&& this.getFdxGroundDelayTime().equals(castOther.getFdxGroundDelayTime())))
				&& ((this.getTolerance() == castOther.getTolerance()) || (this.getTolerance() != null
						&& castOther.getTolerance() != null && this.getTolerance().equals(castOther.getTolerance())))
				&& ((this.getAboveToleranceLimit() == castOther.getAboveToleranceLimit())
						|| (this.getAboveToleranceLimit() != null && castOther.getAboveToleranceLimit() != null
								&& this.getAboveToleranceLimit().equals(castOther.getAboveToleranceLimit())))
				&& ((this.getBelowToleranceLimit() == castOther.getBelowToleranceLimit())
						|| (this.getBelowToleranceLimit() != null && castOther.getBelowToleranceLimit() != null
								&& this.getBelowToleranceLimit().equals(castOther.getBelowToleranceLimit())))
				&& ((this.getToleranceUnit() == castOther.getToleranceUnit())
						|| (this.getToleranceUnit() != null && castOther.getToleranceUnit() != null
								&& this.getToleranceUnit().equals(castOther.getToleranceUnit())))
				&& ((this.getPrimaryBussiness() == castOther.getPrimaryBussiness())
						|| (this.getPrimaryBussiness() != null && castOther.getPrimaryBussiness() != null
								&& this.getPrimaryBussiness().equals(castOther.getPrimaryBussiness())))
				&& ((this.getAssignedAuditor() == castOther.getAssignedAuditor())
						|| (this.getAssignedAuditor() != null && castOther.getAssignedAuditor() != null
								&& this.getAssignedAuditor().equals(castOther.getAssignedAuditor())))
				&& ((this.getBillpayDayOfWeek() == castOther.getBillpayDayOfWeek())
						|| (this.getBillpayDayOfWeek() != null && castOther.getBillpayDayOfWeek() != null
								&& this.getBillpayDayOfWeek().equals(castOther.getBillpayDayOfWeek())))
				&& ((this.getIsBillpay() == castOther.getIsBillpay()) || (this.getIsBillpay() != null
						&& castOther.getIsBillpay() != null && this.getIsBillpay().equals(castOther.getIsBillpay())))
				&& ((this.getIsGlNull() == castOther.getIsGlNull()) || (this.getIsGlNull() != null
						&& castOther.getIsGlNull() != null && this.getIsGlNull().equals(castOther.getIsGlNull())))
				&& ((this.getNspDaysForPay() == castOther.getNspDaysForPay())
						|| (this.getNspDaysForPay() != null && castOther.getNspDaysForPay() != null
								&& this.getNspDaysForPay().equals(castOther.getNspDaysForPay())))
				&& ((this.getPaidCust() == castOther.getPaidCust()) || (this.getPaidCust() != null
						&& castOther.getPaidCust() != null && this.getPaidCust().equals(castOther.getPaidCust())))
				&& ((this.getFedexCloseCycle() == castOther.getFedexCloseCycle())
						|| (this.getFedexCloseCycle() != null && castOther.getFedexCloseCycle() != null
								&& this.getFedexCloseCycle().equals(castOther.getFedexCloseCycle())))
				&& ((this.getReceiverId() == castOther.getReceiverId()) || (this.getReceiverId() != null
						&& castOther.getReceiverId() != null && this.getReceiverId().equals(castOther.getReceiverId())))
				&& ((this.getIsParcelAudit() == castOther.getIsParcelAudit())
						|| (this.getIsParcelAudit() != null && castOther.getIsParcelAudit() != null
								&& this.getIsParcelAudit().equals(castOther.getIsParcelAudit())))
				&& ((this.getIsNspAudit() == castOther.getIsNspAudit()) || (this.getIsNspAudit() != null
						&& castOther.getIsNspAudit() != null && this.getIsNspAudit().equals(castOther.getIsNspAudit())))
				&& ((this.getIsParcelBillpay() == castOther.getIsParcelBillpay())
						|| (this.getIsParcelBillpay() != null && castOther.getIsParcelBillpay() != null
								&& this.getIsParcelBillpay().equals(castOther.getIsParcelBillpay())))
				&& ((this.getEngageDate() == castOther.getEngageDate()) || (this.getEngageDate() != null
						&& castOther.getEngageDate() != null && this.getEngageDate().equals(castOther.getEngageDate())))
				&& ((this.getCustomerStatusId() == castOther.getCustomerStatusId())
						|| (this.getCustomerStatusId() != null && castOther.getCustomerStatusId() != null
								&& this.getCustomerStatusId().equals(castOther.getCustomerStatusId())))
				&& ((this.getUpsOmitVoidAudit() == castOther.getUpsOmitVoidAudit())
						|| (this.getUpsOmitVoidAudit() != null && castOther.getUpsOmitVoidAudit() != null
								&& this.getUpsOmitVoidAudit().equals(castOther.getUpsOmitVoidAudit())))
				&& ((this.getUpsOmitAdcAudit() == castOther.getUpsOmitAdcAudit())
						|| (this.getUpsOmitAdcAudit() != null && castOther.getUpsOmitAdcAudit() != null
								&& this.getUpsOmitAdcAudit().equals(castOther.getUpsOmitAdcAudit())))
				&& ((this.getUpsOmitSatAudit() == castOther.getUpsOmitSatAudit())
						|| (this.getUpsOmitSatAudit() != null && castOther.getUpsOmitSatAudit() != null
								&& this.getUpsOmitSatAudit().equals(castOther.getUpsOmitSatAudit())))
				&& ((this.getUpsOmitResAudit() == castOther.getUpsOmitResAudit())
						|| (this.getUpsOmitResAudit() != null && castOther.getUpsOmitResAudit() != null
								&& this.getUpsOmitResAudit().equals(castOther.getUpsOmitResAudit())))
				&& ((this.getUpsNotes() == castOther.getUpsNotes()) || (this.getUpsNotes() != null
						&& castOther.getUpsNotes() != null && this.getUpsNotes().equals(castOther.getUpsNotes())))
				&& ((this.getFedexRemittanceFlag() == castOther.getFedexRemittanceFlag())
						|| (this.getFedexRemittanceFlag() != null && castOther.getFedexRemittanceFlag() != null
								&& this.getFedexRemittanceFlag().equals(castOther.getFedexRemittanceFlag())))
				&& ((this.getFedexEdiType() == castOther.getFedexEdiType())
						|| (this.getFedexEdiType() != null && castOther.getFedexEdiType() != null
								&& this.getFedexEdiType().equals(castOther.getFedexEdiType())))
				&& ((this.getFedexNotes() == castOther.getFedexNotes()) || (this.getFedexNotes() != null
						&& castOther.getFedexNotes() != null && this.getFedexNotes().equals(castOther.getFedexNotes())))
				&& ((this.getUpsOmitDupAudit() == castOther.getUpsOmitDupAudit())
						|| (this.getUpsOmitDupAudit() != null && castOther.getUpsOmitDupAudit() != null
								&& this.getUpsOmitDupAudit().equals(castOther.getUpsOmitDupAudit())))
				&& ((this.getUpsResDelay() == castOther.getUpsResDelay())
						|| (this.getUpsResDelay() != null && castOther.getUpsResDelay() != null
								&& this.getUpsResDelay().equals(castOther.getUpsResDelay())))
				&& ((this.getUpsSatDelay() == castOther.getUpsSatDelay())
						|| (this.getUpsSatDelay() != null && castOther.getUpsSatDelay() != null
								&& this.getUpsSatDelay().equals(castOther.getUpsSatDelay())))
				&& ((this.getUpsVoidDelay() == castOther.getUpsVoidDelay())
						|| (this.getUpsVoidDelay() != null && castOther.getUpsVoidDelay() != null
								&& this.getUpsVoidDelay().equals(castOther.getUpsVoidDelay())))
				&& ((this.getUpsAdcDelay() == castOther.getUpsAdcDelay())
						|| (this.getUpsAdcDelay() != null && castOther.getUpsAdcDelay() != null
								&& this.getUpsAdcDelay().equals(castOther.getUpsAdcDelay())))
				&& ((this.getUpsDupDelay() == castOther.getUpsDupDelay())
						|| (this.getUpsDupDelay() != null && castOther.getUpsDupDelay() != null
								&& this.getUpsDupDelay().equals(castOther.getUpsDupDelay())))
				&& ((this.getFdxPickupScanAsOriginZip() == castOther.getFdxPickupScanAsOriginZip())
						|| (this.getFdxPickupScanAsOriginZip() != null
								&& castOther.getFdxPickupScanAsOriginZip() != null
								&& this.getFdxPickupScanAsOriginZip().equals(castOther.getFdxPickupScanAsOriginZip())))
				&& ((this.getFedexCloseDayOfWeek() == castOther.getFedexCloseDayOfWeek())
						|| (this.getFedexCloseDayOfWeek() != null && castOther.getFedexCloseDayOfWeek() != null
								&& this.getFedexCloseDayOfWeek().equals(castOther.getFedexCloseDayOfWeek())))
				&& ((this.getLoadOnlyIntl() == castOther.getLoadOnlyIntl())
						|| (this.getLoadOnlyIntl() != null && castOther.getLoadOnlyIntl() != null
								&& this.getLoadOnlyIntl().equals(castOther.getLoadOnlyIntl())))
				&& ((this.getUpsComments() == castOther.getUpsComments())
						|| (this.getUpsComments() != null && castOther.getUpsComments() != null
								&& this.getUpsComments().equals(castOther.getUpsComments())))
				&& ((this.getGlcodeMethod() == castOther.getGlcodeMethod())
						|| (this.getGlcodeMethod() != null && castOther.getGlcodeMethod() != null
								&& this.getGlcodeMethod().equals(castOther.getGlcodeMethod())))
				&& ((this.getCustomerDefinedName1() == castOther.getCustomerDefinedName1())
						|| (this.getCustomerDefinedName1() != null && castOther.getCustomerDefinedName1() != null
								&& this.getCustomerDefinedName1().equals(castOther.getCustomerDefinedName1())))
				&& ((this.getCustomerDefinedName2() == castOther.getCustomerDefinedName2())
						|| (this.getCustomerDefinedName2() != null && castOther.getCustomerDefinedName2() != null
								&& this.getCustomerDefinedName2().equals(castOther.getCustomerDefinedName2())))
				&& ((this.getCustomerDefinedName3() == castOther.getCustomerDefinedName3())
						|| (this.getCustomerDefinedName3() != null && castOther.getCustomerDefinedName3() != null
								&& this.getCustomerDefinedName3().equals(castOther.getCustomerDefinedName3())))
				&& ((this.getUpsShortPay() == castOther.getUpsShortPay())
						|| (this.getUpsShortPay() != null && castOther.getUpsShortPay() != null
								&& this.getUpsShortPay().equals(castOther.getUpsShortPay())))
				&& ((this.getUpsVoidInDays() == castOther.getUpsVoidInDays())
						|| (this.getUpsVoidInDays() != null && castOther.getUpsVoidInDays() != null
								&& this.getUpsVoidInDays().equals(castOther.getUpsVoidInDays())))
				&& ((this.getUpsEngageDate() == castOther.getUpsEngageDate())
						|| (this.getUpsEngageDate() != null && castOther.getUpsEngageDate() != null
								&& this.getUpsEngageDate().equals(castOther.getUpsEngageDate())))
				&& ((this.getFedexEngageDate() == castOther.getFedexEngageDate())
						|| (this.getFedexEngageDate() != null && castOther.getFedexEngageDate() != null
								&& this.getFedexEngageDate().equals(castOther.getFedexEngageDate())))
				&& ((this.getDhlEngageDate() == castOther.getDhlEngageDate())
						|| (this.getDhlEngageDate() != null && castOther.getDhlEngageDate() != null
								&& this.getDhlEngageDate().equals(castOther.getDhlEngageDate())))
				&& ((this.getFreightEngageDate() == castOther.getFreightEngageDate())
						|| (this.getFreightEngageDate() != null && castOther.getFreightEngageDate() != null
								&& this.getFreightEngageDate().equals(castOther.getFreightEngageDate())))
				&& ((this.getUpsInvoices() == castOther.getUpsInvoices())
						|| (this.getUpsInvoices() != null && castOther.getUpsInvoices() != null
								&& this.getUpsInvoices().equals(castOther.getUpsInvoices())))
				&& ((this.getLoadConsolidation() == castOther.getLoadConsolidation())
						|| (this.getLoadConsolidation() != null && castOther.getLoadConsolidation() != null
								&& this.getLoadConsolidation().equals(castOther.getLoadConsolidation())))
				&& ((this.getPoFormat() == castOther.getPoFormat()) || (this.getPoFormat() != null
						&& castOther.getPoFormat() != null && this.getPoFormat().equals(castOther.getPoFormat())))
				&& ((this.getNextAvailablePo() == castOther.getNextAvailablePo())
						|| (this.getNextAvailablePo() != null && castOther.getNextAvailablePo() != null
								&& this.getNextAvailablePo().equals(castOther.getNextAvailablePo())))
				&& ((this.getCustomerNumber() == castOther.getCustomerNumber())
						|| (this.getCustomerNumber() != null && castOther.getCustomerNumber() != null
								&& this.getCustomerNumber().equals(castOther.getCustomerNumber())))
				&& ((this.getGlCodeFormat() == castOther.getGlCodeFormat())
						|| (this.getGlCodeFormat() != null && castOther.getGlCodeFormat() != null
								&& this.getGlCodeFormat().equals(castOther.getGlCodeFormat())))
				&& ((this.getCostCenterNumberFormat() == castOther.getCostCenterNumberFormat())
						|| (this.getCostCenterNumberFormat() != null && castOther.getCostCenterNumberFormat() != null
								&& this.getCostCenterNumberFormat().equals(castOther.getCostCenterNumberFormat())))
				&& ((this.getIsParcelGlNull() == castOther.getIsParcelGlNull())
						|| (this.getIsParcelGlNull() != null && castOther.getIsParcelGlNull() != null
								&& this.getIsParcelGlNull().equals(castOther.getIsParcelGlNull())))
				&& ((this.getResidentialAuditForFreight() == castOther.getResidentialAuditForFreight())
						|| (this.getResidentialAuditForFreight() != null
								&& castOther.getResidentialAuditForFreight() != null
								&& this.getResidentialAuditForFreight()
										.equals(castOther.getResidentialAuditForFreight())))
				&& ((this.getBrokerageParent() == castOther.getBrokerageParent())
						|| (this.getBrokerageParent() != null && castOther.getBrokerageParent() != null
								&& this.getBrokerageParent().equals(castOther.getBrokerageParent())))
				&& ((this.getBrokerageParentType() == castOther.getBrokerageParentType())
						|| (this.getBrokerageParentType() != null && castOther.getBrokerageParentType() != null
								&& this.getBrokerageParentType().equals(castOther.getBrokerageParentType())))
				&& ((this.getBrokerageChildType() == castOther.getBrokerageChildType())
						|| (this.getBrokerageChildType() != null && castOther.getBrokerageChildType() != null
								&& this.getBrokerageChildType().equals(castOther.getBrokerageChildType())))
				&& ((this.getNspGroupCustomerId() == castOther.getNspGroupCustomerId())
						|| (this.getNspGroupCustomerId() != null && castOther.getNspGroupCustomerId() != null
								&& this.getNspGroupCustomerId().equals(castOther.getNspGroupCustomerId())))
				&& ((this.getCustQaPercent() == castOther.getCustQaPercent())
						|| (this.getCustQaPercent() != null && castOther.getCustQaPercent() != null
								&& this.getCustQaPercent().equals(castOther.getCustQaPercent())))
				&& ((this.getCustQaPercentCounter() == castOther.getCustQaPercentCounter())
						|| (this.getCustQaPercentCounter() != null && castOther.getCustQaPercentCounter() != null
								&& this.getCustQaPercentCounter().equals(castOther.getCustQaPercentCounter())))
				&& ((this.getUplift() == castOther.getUplift()) || (this.getUplift() != null
						&& castOther.getUplift() != null && this.getUplift().equals(castOther.getUplift())))
				&& ((this.getGlcodingAttempt() == castOther.getGlcodingAttempt())
						|| (this.getGlcodingAttempt() != null && castOther.getGlcodingAttempt() != null
								&& this.getGlcodingAttempt().equals(castOther.getGlcodingAttempt())))
				&& ((this.getPodRequired() == castOther.getPodRequired())
						|| (this.getPodRequired() != null && castOther.getPodRequired() != null
								&& this.getPodRequired().equals(castOther.getPodRequired())))
				&& ((this.getCanParcel() == castOther.getCanParcel()) || (this.getCanParcel() != null
						&& castOther.getCanParcel() != null && this.getCanParcel().equals(castOther.getCanParcel())))
				&& ((this.getCanFreight() == castOther.getCanFreight()) || (this.getCanFreight() != null
						&& castOther.getCanFreight() != null && this.getCanFreight().equals(castOther.getCanFreight())))
				&& ((this.getDomesticCurrency() == castOther.getDomesticCurrency())
						|| (this.getDomesticCurrency() != null && castOther.getDomesticCurrency() != null
								&& this.getDomesticCurrency().equals(castOther.getDomesticCurrency())))
				&& ((this.getInvoicedOnTransactionFee() == castOther.getInvoicedOnTransactionFee())
						|| (this.getInvoicedOnTransactionFee() != null
								&& castOther.getInvoicedOnTransactionFee() != null
								&& this.getInvoicedOnTransactionFee().equals(castOther.getInvoicedOnTransactionFee())))
				&& ((this.getPcmilerVersion() == castOther.getPcmilerVersion())
						|| (this.getPcmilerVersion() != null && castOther.getPcmilerVersion() != null
								&& this.getPcmilerVersion().equals(castOther.getPcmilerVersion())))
				&& ((this.getUpsPaymentOption() == castOther.getUpsPaymentOption())
						|| (this.getUpsPaymentOption() != null && castOther.getUpsPaymentOption() != null
								&& this.getUpsPaymentOption().equals(castOther.getUpsPaymentOption())))
				&& ((this.getDhlPaymentOption() == castOther.getDhlPaymentOption())
						|| (this.getDhlPaymentOption() != null && castOther.getDhlPaymentOption() != null
								&& this.getDhlPaymentOption().equals(castOther.getDhlPaymentOption())))
				&& ((this.getPayrunBasedOn() == castOther.getPayrunBasedOn())
						|| (this.getPayrunBasedOn() != null && castOther.getPayrunBasedOn() != null
								&& this.getPayrunBasedOn().equals(castOther.getPayrunBasedOn())))
				&& ((this.getValidateMultistopQty() == castOther.getValidateMultistopQty())
						|| (this.getValidateMultistopQty() != null && castOther.getValidateMultistopQty() != null
								&& this.getValidateMultistopQty().equals(castOther.getValidateMultistopQty())))
				&& ((this.getEmeaCustomerFlag() == castOther.getEmeaCustomerFlag())
						|| (this.getEmeaCustomerFlag() != null && castOther.getEmeaCustomerFlag() != null
								&& this.getEmeaCustomerFlag().equals(castOther.getEmeaCustomerFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCustomerCode() == null ? 0 : this.getCustomerCode().hashCode());
		result = 37 * result + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
		result = 37 * result + (getCustomerDescription() == null ? 0 : this.getCustomerDescription().hashCode());
		result = 37 * result + (getAddress1() == null ? 0 : this.getAddress1().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getZipcode() == null ? 0 : this.getZipcode().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getFax() == null ? 0 : this.getFax().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getAddress2() == null ? 0 : this.getAddress2().hashCode());
		result = 37 * result + (getIsActive() == null ? 0 : this.getIsActive().hashCode());
		result = 37 * result + (getAddToDb() == null ? 0 : this.getAddToDb().hashCode());
		result = 37 * result + (getLateManifest() == null ? 0 : this.getLateManifest().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getMbaClient() == null ? 0 : this.getMbaClient().hashCode());
		result = 37 * result + (getUseTranCount() == null ? 0 : this.getUseTranCount().hashCode());
		result = 37 * result + (getShipdateOnOrigin() == null ? 0 : this.getShipdateOnOrigin().hashCode());
		result = 37 * result + (getFedexGroundGsrOnline() == null ? 0 : this.getFedexGroundGsrOnline().hashCode());
		result = 37 * result + (getFedexExpressGsrOnline() == null ? 0 : this.getFedexExpressGsrOnline().hashCode());
		result = 37 * result + (getEmailUpsFromAddress() == null ? 0 : this.getEmailUpsFromAddress().hashCode());
		result = 37 * result + (getEmailUpsToAddress() == null ? 0 : this.getEmailUpsToAddress().hashCode());
		result = 37 * result + (getEmailUpsGsrDate() == null ? 0 : this.getEmailUpsGsrDate().hashCode());
		result = 37 * result + (getEmailUpsGsrFlag() == null ? 0 : this.getEmailUpsGsrFlag().hashCode());
		result = 37 * result + (getEmailUpsInvoiceFlag() == null ? 0 : this.getEmailUpsInvoiceFlag().hashCode());
		result = 37 * result + (getEmailUpsInvoiceDate() == null ? 0 : this.getEmailUpsInvoiceDate().hashCode());
		result = 37 * result + (getPoolPoint() == null ? 0 : this.getPoolPoint().hashCode());
		result = 37 * result + (getCreatedOn() == null ? 0 : this.getCreatedOn().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getUpdatedOn() == null ? 0 : this.getUpdatedOn().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37 * result + (getBusinessPartnerId() == null ? 0 : this.getBusinessPartnerId().hashCode());
		result = 37 * result + (getMarkup() == null ? 0 : this.getMarkup().hashCode());
		result = 37 * result + (getShowPubRates() == null ? 0 : this.getShowPubRates().hashCode());
		result = 37 * result + (getMarkupType() == null ? 0 : this.getMarkupType().hashCode());
		result = 37 * result + (getUpsGsrFlag() == null ? 0 : this.getUpsGsrFlag().hashCode());
		result = 37 * result + (getFdxPaymentOption() == null ? 0 : this.getFdxPaymentOption().hashCode());
		result = 37 * result + (getShipperUniqShGrp() == null ? 0 : this.getShipperUniqShGrp().hashCode());
		result = 37 * result + (getPoolPointUps() == null ? 0 : this.getPoolPointUps().hashCode());
		result = 37 * result + (getFdxExpressDelayTime() == null ? 0 : this.getFdxExpressDelayTime().hashCode());
		result = 37 * result + (getFdxIntlDelayTime() == null ? 0 : this.getFdxIntlDelayTime().hashCode());
		result = 37 * result + (getUpsExpressDelayTime() == null ? 0 : this.getUpsExpressDelayTime().hashCode());
		result = 37 * result + (getUpsIntlDelayTime() == null ? 0 : this.getUpsIntlDelayTime().hashCode());
		result = 37 * result + (getParentCustomerId() == null ? 0 : this.getParentCustomerId().hashCode());
		result = 37 * result + (getDhlUserName() == null ? 0 : this.getDhlUserName().hashCode());
		result = 37 * result + (getDhlPassword() == null ? 0 : this.getDhlPassword().hashCode());
		result = 37 * result + (getFedexOnlineFiling() == null ? 0 : this.getFedexOnlineFiling().hashCode());
		result = 37 * result + (getFdxGroundDelayTime() == null ? 0 : this.getFdxGroundDelayTime().hashCode());
		result = 37 * result + (getTolerance() == null ? 0 : this.getTolerance().hashCode());
		result = 37 * result + (getAboveToleranceLimit() == null ? 0 : this.getAboveToleranceLimit().hashCode());
		result = 37 * result + (getBelowToleranceLimit() == null ? 0 : this.getBelowToleranceLimit().hashCode());
		result = 37 * result + (getToleranceUnit() == null ? 0 : this.getToleranceUnit().hashCode());
		result = 37 * result + (getPrimaryBussiness() == null ? 0 : this.getPrimaryBussiness().hashCode());
		result = 37 * result + (getAssignedAuditor() == null ? 0 : this.getAssignedAuditor().hashCode());
		result = 37 * result + (getBillpayDayOfWeek() == null ? 0 : this.getBillpayDayOfWeek().hashCode());
		result = 37 * result + (getIsBillpay() == null ? 0 : this.getIsBillpay().hashCode());
		result = 37 * result + (getIsGlNull() == null ? 0 : this.getIsGlNull().hashCode());
		result = 37 * result + (getNspDaysForPay() == null ? 0 : this.getNspDaysForPay().hashCode());
		result = 37 * result + (getPaidCust() == null ? 0 : this.getPaidCust().hashCode());
		result = 37 * result + (getFedexCloseCycle() == null ? 0 : this.getFedexCloseCycle().hashCode());
		result = 37 * result + (getReceiverId() == null ? 0 : this.getReceiverId().hashCode());
		result = 37 * result + (getIsParcelAudit() == null ? 0 : this.getIsParcelAudit().hashCode());
		result = 37 * result + (getIsNspAudit() == null ? 0 : this.getIsNspAudit().hashCode());
		result = 37 * result + (getIsParcelBillpay() == null ? 0 : this.getIsParcelBillpay().hashCode());
		result = 37 * result + (getEngageDate() == null ? 0 : this.getEngageDate().hashCode());
		result = 37 * result + (getCustomerStatusId() == null ? 0 : this.getCustomerStatusId().hashCode());
		result = 37 * result + (getUpsOmitVoidAudit() == null ? 0 : this.getUpsOmitVoidAudit().hashCode());
		result = 37 * result + (getUpsOmitAdcAudit() == null ? 0 : this.getUpsOmitAdcAudit().hashCode());
		result = 37 * result + (getUpsOmitSatAudit() == null ? 0 : this.getUpsOmitSatAudit().hashCode());
		result = 37 * result + (getUpsOmitResAudit() == null ? 0 : this.getUpsOmitResAudit().hashCode());
		result = 37 * result + (getUpsNotes() == null ? 0 : this.getUpsNotes().hashCode());
		result = 37 * result + (getFedexRemittanceFlag() == null ? 0 : this.getFedexRemittanceFlag().hashCode());
		result = 37 * result + (getFedexEdiType() == null ? 0 : this.getFedexEdiType().hashCode());
		result = 37 * result + (getFedexNotes() == null ? 0 : this.getFedexNotes().hashCode());
		result = 37 * result + (getUpsOmitDupAudit() == null ? 0 : this.getUpsOmitDupAudit().hashCode());
		result = 37 * result + (getUpsResDelay() == null ? 0 : this.getUpsResDelay().hashCode());
		result = 37 * result + (getUpsSatDelay() == null ? 0 : this.getUpsSatDelay().hashCode());
		result = 37 * result + (getUpsVoidDelay() == null ? 0 : this.getUpsVoidDelay().hashCode());
		result = 37 * result + (getUpsAdcDelay() == null ? 0 : this.getUpsAdcDelay().hashCode());
		result = 37 * result + (getUpsDupDelay() == null ? 0 : this.getUpsDupDelay().hashCode());
		result = 37 * result
				+ (getFdxPickupScanAsOriginZip() == null ? 0 : this.getFdxPickupScanAsOriginZip().hashCode());
		result = 37 * result + (getFedexCloseDayOfWeek() == null ? 0 : this.getFedexCloseDayOfWeek().hashCode());
		result = 37 * result + (getLoadOnlyIntl() == null ? 0 : this.getLoadOnlyIntl().hashCode());
		result = 37 * result + (getUpsComments() == null ? 0 : this.getUpsComments().hashCode());
		result = 37 * result + (getGlcodeMethod() == null ? 0 : this.getGlcodeMethod().hashCode());
		result = 37 * result + (getCustomerDefinedName1() == null ? 0 : this.getCustomerDefinedName1().hashCode());
		result = 37 * result + (getCustomerDefinedName2() == null ? 0 : this.getCustomerDefinedName2().hashCode());
		result = 37 * result + (getCustomerDefinedName3() == null ? 0 : this.getCustomerDefinedName3().hashCode());
		result = 37 * result + (getUpsShortPay() == null ? 0 : this.getUpsShortPay().hashCode());
		result = 37 * result + (getUpsVoidInDays() == null ? 0 : this.getUpsVoidInDays().hashCode());
		result = 37 * result + (getUpsEngageDate() == null ? 0 : this.getUpsEngageDate().hashCode());
		result = 37 * result + (getFedexEngageDate() == null ? 0 : this.getFedexEngageDate().hashCode());
		result = 37 * result + (getDhlEngageDate() == null ? 0 : this.getDhlEngageDate().hashCode());
		result = 37 * result + (getFreightEngageDate() == null ? 0 : this.getFreightEngageDate().hashCode());
		result = 37 * result + (getUpsInvoices() == null ? 0 : this.getUpsInvoices().hashCode());
		result = 37 * result + (getLoadConsolidation() == null ? 0 : this.getLoadConsolidation().hashCode());
		result = 37 * result + (getPoFormat() == null ? 0 : this.getPoFormat().hashCode());
		result = 37 * result + (getNextAvailablePo() == null ? 0 : this.getNextAvailablePo().hashCode());
		result = 37 * result + (getCustomerNumber() == null ? 0 : this.getCustomerNumber().hashCode());
		result = 37 * result + (getGlCodeFormat() == null ? 0 : this.getGlCodeFormat().hashCode());
		result = 37 * result + (getCostCenterNumberFormat() == null ? 0 : this.getCostCenterNumberFormat().hashCode());
		result = 37 * result + (getIsParcelGlNull() == null ? 0 : this.getIsParcelGlNull().hashCode());
		result = 37 * result
				+ (getResidentialAuditForFreight() == null ? 0 : this.getResidentialAuditForFreight().hashCode());
		result = 37 * result + (getBrokerageParent() == null ? 0 : this.getBrokerageParent().hashCode());
		result = 37 * result + (getBrokerageParentType() == null ? 0 : this.getBrokerageParentType().hashCode());
		result = 37 * result + (getBrokerageChildType() == null ? 0 : this.getBrokerageChildType().hashCode());
		result = 37 * result + (getNspGroupCustomerId() == null ? 0 : this.getNspGroupCustomerId().hashCode());
		result = 37 * result + (getCustQaPercent() == null ? 0 : this.getCustQaPercent().hashCode());
		result = 37 * result + (getCustQaPercentCounter() == null ? 0 : this.getCustQaPercentCounter().hashCode());
		result = 37 * result + (getUplift() == null ? 0 : this.getUplift().hashCode());
		result = 37 * result + (getGlcodingAttempt() == null ? 0 : this.getGlcodingAttempt().hashCode());
		result = 37 * result + (getPodRequired() == null ? 0 : this.getPodRequired().hashCode());
		result = 37 * result + (getCanParcel() == null ? 0 : this.getCanParcel().hashCode());
		result = 37 * result + (getCanFreight() == null ? 0 : this.getCanFreight().hashCode());
		result = 37 * result + (getDomesticCurrency() == null ? 0 : this.getDomesticCurrency().hashCode());
		result = 37 * result
				+ (getInvoicedOnTransactionFee() == null ? 0 : this.getInvoicedOnTransactionFee().hashCode());
		result = 37 * result + (getPcmilerVersion() == null ? 0 : this.getPcmilerVersion().hashCode());
		result = 37 * result + (getUpsPaymentOption() == null ? 0 : this.getUpsPaymentOption().hashCode());
		result = 37 * result + (getDhlPaymentOption() == null ? 0 : this.getDhlPaymentOption().hashCode());
		result = 37 * result + (getPayrunBasedOn() == null ? 0 : this.getPayrunBasedOn().hashCode());
		result = 37 * result + (getValidateMultistopQty() == null ? 0 : this.getValidateMultistopQty().hashCode());
		result = 37 * result + (getEmeaCustomerFlag() == null ? 0 : this.getEmeaCustomerFlag().hashCode());
		return result;
	}

}
