package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpCanInvoiceTb generated by hbm2java
 */
@Entity
@Table(name = "SHP_CAN_INVOICE_TB")
public class ShpCanInvoiceTb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpCanInvoiceTbId id;

	public ShpCanInvoiceTb() {
	}

	public ShpCanInvoiceTb(ShpCanInvoiceTbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "canInvoiceId", column = @Column(name = "CAN_INVOICE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "primaryReference", column = @Column(name = "PRIMARY_REFERENCE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "originCity", column = @Column(name = "ORIGIN_CITY", length = 500) ),
			@AttributeOverride(name = "originState", column = @Column(name = "ORIGIN_STATE", length = 500) ),
			@AttributeOverride(name = "originZipCode", column = @Column(name = "ORIGIN_ZIP_CODE", length = 500) ),
			@AttributeOverride(name = "originCountry", column = @Column(name = "ORIGIN_COUNTRY", length = 500) ),
			@AttributeOverride(name = "destCity", column = @Column(name = "DEST_CITY", length = 500) ),
			@AttributeOverride(name = "destState", column = @Column(name = "DEST_STATE", length = 500) ),
			@AttributeOverride(name = "destZipCode", column = @Column(name = "DEST_ZIP_CODE", length = 500) ),
			@AttributeOverride(name = "destCountry", column = @Column(name = "DEST_COUNTRY", length = 500) ),
			@AttributeOverride(name = "targetShipDate", column = @Column(name = "TARGET_SHIP_DATE", length = 7) ),
			@AttributeOverride(name = "weight", column = @Column(name = "WEIGHT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "class_", column = @Column(name = "CLASS", length = 500) ),
			@AttributeOverride(name = "createUser", column = @Column(name = "CREATE_USER", length = 500) ),
			@AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 7) ),
			@AttributeOverride(name = "lastUpdateUser", column = @Column(name = "LAST_UPDATE_USER", length = 500) ),
			@AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATE_DATE", length = 7) ),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", precision = 22, scale = 0) ) })
	public ShpCanInvoiceTbId getId() {
		return this.id;
	}

	public void setId(ShpCanInvoiceTbId id) {
		this.id = id;
	}

}
