package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpCustomerByUserVw generated by hbm2java
 */
@Entity
@Table(name = "SHP_CUSTOMER_BY_USER_VW")
public class ShpCustomerByUserVw implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpCustomerByUserVwId id;

	public ShpCustomerByUserVw() {
	}

	public ShpCustomerByUserVw(ShpCustomerByUserVwId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "customerCode", column = @Column(name = "CUSTOMER_CODE", length = 10) ),
			@AttributeOverride(name = "customerName", column = @Column(name = "CUSTOMER_NAME", length = 100) ),
			@AttributeOverride(name = "customerDescription", column = @Column(name = "CUSTOMER_DESCRIPTION", length = 100) ),
			@AttributeOverride(name = "address1", column = @Column(name = "ADDRESS1", length = 100) ),
			@AttributeOverride(name = "city", column = @Column(name = "CITY", length = 40) ),
			@AttributeOverride(name = "state", column = @Column(name = "STATE", length = 20) ),
			@AttributeOverride(name = "country", column = @Column(name = "COUNTRY", length = 30) ),
			@AttributeOverride(name = "zipcode", column = @Column(name = "ZIPCODE", length = 10) ),
			@AttributeOverride(name = "phone", column = @Column(name = "PHONE", length = 20) ),
			@AttributeOverride(name = "fax", column = @Column(name = "FAX", length = 20) ),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", length = 150) ),
			@AttributeOverride(name = "address2", column = @Column(name = "ADDRESS2", length = 100) ),
			@AttributeOverride(name = "isActive", column = @Column(name = "IS_ACTIVE", precision = 1, scale = 0) ),
			@AttributeOverride(name = "addToDb", column = @Column(name = "ADD_TO_DB", precision = 1, scale = 0) ),
			@AttributeOverride(name = "lateManifest", column = @Column(name = "LATE_MANIFEST", precision = 1, scale = 0) ),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "mbaClient", column = @Column(name = "MBA_CLIENT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "useTranCount", column = @Column(name = "USE_TRAN_COUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "shipdateOnOrigin", column = @Column(name = "SHIPDATE_ON_ORIGIN", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fedexGroundGsrOnline", column = @Column(name = "FEDEX_GROUND_GSR_ONLINE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fedexExpressGsrOnline", column = @Column(name = "FEDEX_EXPRESS_GSR_ONLINE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "emailUpsFromAddress", column = @Column(name = "EMAIL_UPS_FROM_ADDRESS", length = 200) ),
			@AttributeOverride(name = "emailUpsToAddress", column = @Column(name = "EMAIL_UPS_TO_ADDRESS", length = 200) ),
			@AttributeOverride(name = "emailUpsGsrDate", column = @Column(name = "EMAIL_UPS_GSR_DATE", length = 7) ),
			@AttributeOverride(name = "emailUpsGsrFlag", column = @Column(name = "EMAIL_UPS_GSR_FLAG", precision = 22, scale = 0) ),
			@AttributeOverride(name = "emailUpsInvoiceFlag", column = @Column(name = "EMAIL_UPS_INVOICE_FLAG", precision = 22, scale = 0) ),
			@AttributeOverride(name = "emailUpsInvoiceDate", column = @Column(name = "EMAIL_UPS_INVOICE_DATE", length = 7) ),
			@AttributeOverride(name = "poolPoint", column = @Column(name = "POOL_POINT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "createdOn", column = @Column(name = "CREATED_ON", length = 7) ),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY", length = 15) ),
			@AttributeOverride(name = "updatedOn", column = @Column(name = "UPDATED_ON", length = 7) ),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "UPDATED_BY", length = 15) ),
			@AttributeOverride(name = "businessPartnerId", column = @Column(name = "BUSINESS_PARTNER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "markup", column = @Column(name = "MARKUP", precision = 22, scale = 0) ),
			@AttributeOverride(name = "showPubRates", column = @Column(name = "SHOW_PUB_RATES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "markupType", column = @Column(name = "MARKUP_TYPE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsGsrFlag", column = @Column(name = "UPS_GSR_FLAG", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fdxPaymentOption", column = @Column(name = "FDX_PAYMENT_OPTION", length = 1) ),
			@AttributeOverride(name = "shipperUniqShGrp", column = @Column(name = "SHIPPER_UNIQ_SH_GRP", precision = 22, scale = 0) ),
			@AttributeOverride(name = "poolPointUps", column = @Column(name = "POOL_POINT_UPS", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fdxExpressDelayTime", column = @Column(name = "FDX_EXPRESS_DELAY_TIME", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fdxIntlDelayTime", column = @Column(name = "FDX_INTL_DELAY_TIME", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsExpressDelayTime", column = @Column(name = "UPS_EXPRESS_DELAY_TIME", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsIntlDelayTime", column = @Column(name = "UPS_INTL_DELAY_TIME", precision = 22, scale = 0) ),
			@AttributeOverride(name = "parentCustomerId", column = @Column(name = "PARENT_CUSTOMER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "dhlUserName", column = @Column(name = "DHL_USER_NAME", length = 50) ),
			@AttributeOverride(name = "dhlPassword", column = @Column(name = "DHL_PASSWORD", length = 50) ),
			@AttributeOverride(name = "fedexOnlineFiling", column = @Column(name = "FEDEX_ONLINE_FILING", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fdxGroundDelayTime", column = @Column(name = "FDX_GROUND_DELAY_TIME", precision = 22, scale = 0) ),
			@AttributeOverride(name = "tolerance", column = @Column(name = "TOLERANCE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "aboveToleranceLimit", column = @Column(name = "ABOVE_TOLERANCE_LIMIT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "belowToleranceLimit", column = @Column(name = "BELOW_TOLERANCE_LIMIT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "toleranceUnit", column = @Column(name = "TOLERANCE_UNIT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "primaryBussiness", column = @Column(name = "PRIMARY_BUSSINESS", length = 150) ),
			@AttributeOverride(name = "assignedAuditor", column = @Column(name = "ASSIGNED_AUDITOR", precision = 22, scale = 0) ),
			@AttributeOverride(name = "billpayDayOfWeek", column = @Column(name = "BILLPAY_DAY_OF_WEEK", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isBillpay", column = @Column(name = "IS_BILLPAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isGlNull", column = @Column(name = "IS_GL_NULL", precision = 22, scale = 0) ),
			@AttributeOverride(name = "nspDaysForPay", column = @Column(name = "NSP_DAYS_FOR_PAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "paidCust", column = @Column(name = "PAID_CUST", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fedexCloseCycle", column = @Column(name = "FEDEX_CLOSE_CYCLE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "receiverId", column = @Column(name = "RECEIVER_ID", length = 15) ),
			@AttributeOverride(name = "isParcelAudit", column = @Column(name = "IS_PARCEL_AUDIT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isNspAudit", column = @Column(name = "IS_NSP_AUDIT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isParcelBillpay", column = @Column(name = "IS_PARCEL_BILLPAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "engageDate", column = @Column(name = "ENGAGE_DATE", length = 7) ),
			@AttributeOverride(name = "customerStatusId", column = @Column(name = "CUSTOMER_STATUS_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsOmitVoidAudit", column = @Column(name = "UPS_OMIT_VOID_AUDIT", precision = 1, scale = 0) ),
			@AttributeOverride(name = "upsOmitAdcAudit", column = @Column(name = "UPS_OMIT_ADC_AUDIT", precision = 1, scale = 0) ),
			@AttributeOverride(name = "upsOmitSatAudit", column = @Column(name = "UPS_OMIT_SAT_AUDIT", precision = 1, scale = 0) ),
			@AttributeOverride(name = "upsOmitResAudit", column = @Column(name = "UPS_OMIT_RES_AUDIT", precision = 1, scale = 0) ),
			@AttributeOverride(name = "upsNotes", column = @Column(name = "UPS_NOTES", length = 400) ),
			@AttributeOverride(name = "fedexRemittanceFlag", column = @Column(name = "FEDEX_REMITTANCE_FLAG", precision = 1, scale = 0) ),
			@AttributeOverride(name = "fedexEdiType", column = @Column(name = "FEDEX_EDI_TYPE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fedexNotes", column = @Column(name = "FEDEX_NOTES", length = 400) ),
			@AttributeOverride(name = "upsOmitDupAudit", column = @Column(name = "UPS_OMIT_DUP_AUDIT", precision = 1, scale = 0) ),
			@AttributeOverride(name = "upsResDelay", column = @Column(name = "UPS_RES_DELAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsSatDelay", column = @Column(name = "UPS_SAT_DELAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsVoidDelay", column = @Column(name = "UPS_VOID_DELAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsAdcDelay", column = @Column(name = "UPS_ADC_DELAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsDupDelay", column = @Column(name = "UPS_DUP_DELAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fdxPickupScanAsOriginZip", column = @Column(name = "FDX_PICKUP_SCAN_AS_ORIGIN_ZIP", precision = 22, scale = 0) ),
			@AttributeOverride(name = "fedexCloseDayOfWeek", column = @Column(name = "FEDEX_CLOSE_DAY_OF_WEEK", precision = 22, scale = 0) ),
			@AttributeOverride(name = "loadOnlyIntl", column = @Column(name = "LOAD_ONLY_INTL", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsComments", column = @Column(name = "UPS_COMMENTS", length = 400) ),
			@AttributeOverride(name = "glcodeMethod", column = @Column(name = "GLCODE_METHOD", precision = 22, scale = 0) ),
			@AttributeOverride(name = "customerDefinedName1", column = @Column(name = "CUSTOMER_DEFINED_NAME1", length = 50) ),
			@AttributeOverride(name = "customerDefinedName2", column = @Column(name = "CUSTOMER_DEFINED_NAME2", length = 50) ),
			@AttributeOverride(name = "customerDefinedName3", column = @Column(name = "CUSTOMER_DEFINED_NAME3", length = 50) ),
			@AttributeOverride(name = "upsShortPay", column = @Column(name = "UPS_SHORT_PAY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsVoidInDays", column = @Column(name = "UPS_VOID_IN_DAYS", precision = 22, scale = 0) ),
			@AttributeOverride(name = "upsEngageDate", column = @Column(name = "UPS_ENGAGE_DATE", length = 7) ),
			@AttributeOverride(name = "fedexEngageDate", column = @Column(name = "FEDEX_ENGAGE_DATE", length = 7) ),
			@AttributeOverride(name = "dhlEngageDate", column = @Column(name = "DHL_ENGAGE_DATE", length = 7) ),
			@AttributeOverride(name = "freightEngageDate", column = @Column(name = "FREIGHT_ENGAGE_DATE", length = 7) ),
			@AttributeOverride(name = "upsInvoices", column = @Column(name = "UPS_INVOICES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "loadConsolidation", column = @Column(name = "LOAD_CONSOLIDATION", precision = 22, scale = 0) ),
			@AttributeOverride(name = "poFormat", column = @Column(name = "PO_FORMAT", length = 500) ),
			@AttributeOverride(name = "nextAvailablePo", column = @Column(name = "NEXT_AVAILABLE_PO", length = 500) ),
			@AttributeOverride(name = "customerNumber", column = @Column(name = "CUSTOMER_NUMBER", length = 100) ),
			@AttributeOverride(name = "glCodeFormat", column = @Column(name = "GL_CODE_FORMAT", length = 100) ),
			@AttributeOverride(name = "costCenterNumberFormat", column = @Column(name = "COST_CENTER_NUMBER_FORMAT", length = 500) ),
			@AttributeOverride(name = "isParcelGlNull", column = @Column(name = "IS_PARCEL_GL_NULL", precision = 1, scale = 0) ),
			@AttributeOverride(name = "residentialAuditForFreight", column = @Column(name = "RESIDENTIAL_AUDIT_FOR_FREIGHT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "brokerageParent", column = @Column(name = "BROKERAGE_PARENT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "brokerageParentType", column = @Column(name = "BROKERAGE_PARENT_TYPE", precision = 1, scale = 0) ),
			@AttributeOverride(name = "brokerageChildType", column = @Column(name = "BROKERAGE_CHILD_TYPE", precision = 1, scale = 0) ),
			@AttributeOverride(name = "nspGroupCustomerId", column = @Column(name = "NSP_GROUP_CUSTOMER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "custQaPercent", column = @Column(name = "CUST_QA_PERCENT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "custQaPercentCounter", column = @Column(name = "CUST_QA_PERCENT_COUNTER", precision = 22, scale = 0) ),
			@AttributeOverride(name = "uplift", column = @Column(name = "UPLIFT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "glcodingAttempt", column = @Column(name = "GLCODING_ATTEMPT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "podRequired", column = @Column(name = "POD_REQUIRED", precision = 22, scale = 0) ),
			@AttributeOverride(name = "canParcel", column = @Column(name = "CAN_PARCEL", precision = 22, scale = 0) ),
			@AttributeOverride(name = "canFreight", column = @Column(name = "CAN_FREIGHT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "domesticCurrency", column = @Column(name = "DOMESTIC_CURRENCY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoicedOnTransactionFee", column = @Column(name = "INVOICED_ON_TRANSACTION_FEE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "pcmilerVersion", column = @Column(name = "PCMILER_VERSION", length = 20) ),
			@AttributeOverride(name = "upsPaymentOption", column = @Column(name = "UPS_PAYMENT_OPTION", length = 1) ),
			@AttributeOverride(name = "dhlPaymentOption", column = @Column(name = "DHL_PAYMENT_OPTION", length = 1) ),
			@AttributeOverride(name = "payrunBasedOn", column = @Column(name = "PAYRUN_BASED_ON", precision = 22, scale = 0) ),
			@AttributeOverride(name = "validateMultistopQty", column = @Column(name = "VALIDATE_MULTISTOP_QTY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "emeaCustomerFlag", column = @Column(name = "EMEA_CUSTOMER_FLAG", precision = 22, scale = 0) ) })
	public ShpCustomerByUserVwId getId() {
		return this.id;
	}

	public void setId(ShpCustomerByUserVwId id) {
		this.id = id;
	}

}
