package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpCurrConvRatesTb generated by hbm2java
 */
@Entity
@Table(name = "SHP_CURR_CONV_RATES_TB")
public class ShpCurrConvRatesTb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpCurrConvRatesTbId id;

	public ShpCurrConvRatesTb() {
	}

	public ShpCurrConvRatesTb(ShpCurrConvRatesTbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "rateId", column = @Column(name = "RATE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "rateDate", column = @Column(name = "RATE_DATE", length = 7) ),
			@AttributeOverride(name = "currencyCode", column = @Column(name = "CURRENCY_CODE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "usdExRate", column = @Column(name = "USD_EX_RATE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "field1", column = @Column(name = "FIELD1", length = 50) ),
			@AttributeOverride(name = "field2", column = @Column(name = "FIELD2", length = 50) ),
			@AttributeOverride(name = "field3", column = @Column(name = "FIELD3", length = 50) ),
			@AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 7) ),
			@AttributeOverride(name = "createUser", column = @Column(name = "CREATE_USER", length = 100) ) })
	public ShpCurrConvRatesTbId getId() {
		return this.id;
	}

	public void setId(ShpCurrConvRatesTbId id) {
		this.id = id;
	}

}
