package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpNspOrdMatchingTbId generated by hbm2java
 */
@Embeddable
public class ShpNspOrdMatchingTbId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal nspOrdMatchingId;
	private String orderNumber;
	private String city;
	private String state;
	private String zipCode;
	private String fileName;
	private String skuNumbers;
	private String createUser;
	private Date createDate;
	private String lastUpdateUser;
	private Date lastUpdateDate;
	private String fileType;
	private String manShipperCode;
	private BigDecimal customerId;
	private String ccNbr;
	private String wbsElement;
	private BigDecimal sapVendorId;
	private String sapVendorName;
	private BigDecimal poDocLineItemNbr;
	private String poLineItemTxt;
	private Date poCreateDate;
	private String category;
	private String internalOrderNumber;

	public ShpNspOrdMatchingTbId() {
	}

	public ShpNspOrdMatchingTbId(BigDecimal nspOrdMatchingId, String orderNumber, String city, String state,
			String zipCode, String fileName, String skuNumbers, String createUser, Date createDate,
			String lastUpdateUser, Date lastUpdateDate, String fileType, String manShipperCode, BigDecimal customerId,
			String ccNbr, String wbsElement, BigDecimal sapVendorId, String sapVendorName, BigDecimal poDocLineItemNbr,
			String poLineItemTxt, Date poCreateDate, String category, String internalOrderNumber) {
		this.nspOrdMatchingId = nspOrdMatchingId;
		this.orderNumber = orderNumber;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		this.fileName = fileName;
		this.skuNumbers = skuNumbers;
		this.createUser = createUser;
		this.createDate = createDate;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.fileType = fileType;
		this.manShipperCode = manShipperCode;
		this.customerId = customerId;
		this.ccNbr = ccNbr;
		this.wbsElement = wbsElement;
		this.sapVendorId = sapVendorId;
		this.sapVendorName = sapVendorName;
		this.poDocLineItemNbr = poDocLineItemNbr;
		this.poLineItemTxt = poLineItemTxt;
		this.poCreateDate = poCreateDate;
		this.category = category;
		this.internalOrderNumber = internalOrderNumber;
	}

	@Column(name = "NSP_ORD_MATCHING_ID", precision = 22, scale = 0)
	public BigDecimal getNspOrdMatchingId() {
		return this.nspOrdMatchingId;
	}

	public void setNspOrdMatchingId(BigDecimal nspOrdMatchingId) {
		this.nspOrdMatchingId = nspOrdMatchingId;
	}

	@Column(name = "ORDER_NUMBER", length = 100)
	public String getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "CITY", length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP_CODE", length = 100)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "FILE_NAME", length = 250)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "SKU_NUMBERS", length = 250)
	public String getSkuNumbers() {
		return this.skuNumbers;
	}

	public void setSkuNumbers(String skuNumbers) {
		this.skuNumbers = skuNumbers;
	}

	@Column(name = "CREATE_USER", length = 50)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "LAST_UPDATE_USER", length = 50)
	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "FILE_TYPE", length = 50)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "MAN_SHIPPER_CODE", length = 50)
	public String getManShipperCode() {
		return this.manShipperCode;
	}

	public void setManShipperCode(String manShipperCode) {
		this.manShipperCode = manShipperCode;
	}

	@Column(name = "CUSTOMER_ID", precision = 22, scale = 0)
	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CC_NBR", length = 100)
	public String getCcNbr() {
		return this.ccNbr;
	}

	public void setCcNbr(String ccNbr) {
		this.ccNbr = ccNbr;
	}

	@Column(name = "WBS_ELEMENT", length = 100)
	public String getWbsElement() {
		return this.wbsElement;
	}

	public void setWbsElement(String wbsElement) {
		this.wbsElement = wbsElement;
	}

	@Column(name = "SAP_VENDOR_ID", precision = 22, scale = 0)
	public BigDecimal getSapVendorId() {
		return this.sapVendorId;
	}

	public void setSapVendorId(BigDecimal sapVendorId) {
		this.sapVendorId = sapVendorId;
	}

	@Column(name = "SAP_VENDOR_NAME", length = 100)
	public String getSapVendorName() {
		return this.sapVendorName;
	}

	public void setSapVendorName(String sapVendorName) {
		this.sapVendorName = sapVendorName;
	}

	@Column(name = "PO_DOC_LINE_ITEM_NBR", precision = 22, scale = 0)
	public BigDecimal getPoDocLineItemNbr() {
		return this.poDocLineItemNbr;
	}

	public void setPoDocLineItemNbr(BigDecimal poDocLineItemNbr) {
		this.poDocLineItemNbr = poDocLineItemNbr;
	}

	@Column(name = "PO_LINE_ITEM_TXT", length = 100)
	public String getPoLineItemTxt() {
		return this.poLineItemTxt;
	}

	public void setPoLineItemTxt(String poLineItemTxt) {
		this.poLineItemTxt = poLineItemTxt;
	}

	@Column(name = "PO_CREATE_DATE", length = 7)
	public Date getPoCreateDate() {
		return this.poCreateDate;
	}

	public void setPoCreateDate(Date poCreateDate) {
		this.poCreateDate = poCreateDate;
	}

	@Column(name = "CATEGORY", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "INTERNAL_ORDER_NUMBER", length = 100)
	public String getInternalOrderNumber() {
		return this.internalOrderNumber;
	}

	public void setInternalOrderNumber(String internalOrderNumber) {
		this.internalOrderNumber = internalOrderNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpNspOrdMatchingTbId))
			return false;
		ShpNspOrdMatchingTbId castOther = (ShpNspOrdMatchingTbId) other;

		return ((this.getNspOrdMatchingId() == castOther.getNspOrdMatchingId())
				|| (this.getNspOrdMatchingId() != null && castOther.getNspOrdMatchingId() != null
						&& this.getNspOrdMatchingId().equals(castOther.getNspOrdMatchingId())))
				&& ((this.getOrderNumber() == castOther.getOrderNumber())
						|| (this.getOrderNumber() != null && castOther.getOrderNumber() != null
								&& this.getOrderNumber().equals(castOther.getOrderNumber())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getZipCode() == castOther.getZipCode()) || (this.getZipCode() != null
						&& castOther.getZipCode() != null && this.getZipCode().equals(castOther.getZipCode())))
				&& ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null
						&& castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())))
				&& ((this.getSkuNumbers() == castOther.getSkuNumbers()) || (this.getSkuNumbers() != null
						&& castOther.getSkuNumbers() != null && this.getSkuNumbers().equals(castOther.getSkuNumbers())))
				&& ((this.getCreateUser() == castOther.getCreateUser()) || (this.getCreateUser() != null
						&& castOther.getCreateUser() != null && this.getCreateUser().equals(castOther.getCreateUser())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser())
						|| (this.getLastUpdateUser() != null && castOther.getLastUpdateUser() != null
								&& this.getLastUpdateUser().equals(castOther.getLastUpdateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate())
						|| (this.getLastUpdateDate() != null && castOther.getLastUpdateDate() != null
								&& this.getLastUpdateDate().equals(castOther.getLastUpdateDate())))
				&& ((this.getFileType() == castOther.getFileType()) || (this.getFileType() != null
						&& castOther.getFileType() != null && this.getFileType().equals(castOther.getFileType())))
				&& ((this.getManShipperCode() == castOther.getManShipperCode())
						|| (this.getManShipperCode() != null && castOther.getManShipperCode() != null
								&& this.getManShipperCode().equals(castOther.getManShipperCode())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCcNbr() == castOther.getCcNbr()) || (this.getCcNbr() != null
						&& castOther.getCcNbr() != null && this.getCcNbr().equals(castOther.getCcNbr())))
				&& ((this.getWbsElement() == castOther.getWbsElement()) || (this.getWbsElement() != null
						&& castOther.getWbsElement() != null && this.getWbsElement().equals(castOther.getWbsElement())))
				&& ((this.getSapVendorId() == castOther.getSapVendorId())
						|| (this.getSapVendorId() != null && castOther.getSapVendorId() != null
								&& this.getSapVendorId().equals(castOther.getSapVendorId())))
				&& ((this.getSapVendorName() == castOther.getSapVendorName())
						|| (this.getSapVendorName() != null && castOther.getSapVendorName() != null
								&& this.getSapVendorName().equals(castOther.getSapVendorName())))
				&& ((this.getPoDocLineItemNbr() == castOther.getPoDocLineItemNbr())
						|| (this.getPoDocLineItemNbr() != null && castOther.getPoDocLineItemNbr() != null
								&& this.getPoDocLineItemNbr().equals(castOther.getPoDocLineItemNbr())))
				&& ((this.getPoLineItemTxt() == castOther.getPoLineItemTxt())
						|| (this.getPoLineItemTxt() != null && castOther.getPoLineItemTxt() != null
								&& this.getPoLineItemTxt().equals(castOther.getPoLineItemTxt())))
				&& ((this.getPoCreateDate() == castOther.getPoCreateDate())
						|| (this.getPoCreateDate() != null && castOther.getPoCreateDate() != null
								&& this.getPoCreateDate().equals(castOther.getPoCreateDate())))
				&& ((this.getCategory() == castOther.getCategory()) || (this.getCategory() != null
						&& castOther.getCategory() != null && this.getCategory().equals(castOther.getCategory())))
				&& ((this.getInternalOrderNumber() == castOther.getInternalOrderNumber())
						|| (this.getInternalOrderNumber() != null && castOther.getInternalOrderNumber() != null
								&& this.getInternalOrderNumber().equals(castOther.getInternalOrderNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNspOrdMatchingId() == null ? 0 : this.getNspOrdMatchingId().hashCode());
		result = 37 * result + (getOrderNumber() == null ? 0 : this.getOrderNumber().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getZipCode() == null ? 0 : this.getZipCode().hashCode());
		result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
		result = 37 * result + (getSkuNumbers() == null ? 0 : this.getSkuNumbers().hashCode());
		result = 37 * result + (getCreateUser() == null ? 0 : this.getCreateUser().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser().hashCode());
		result = 37 * result + (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate().hashCode());
		result = 37 * result + (getFileType() == null ? 0 : this.getFileType().hashCode());
		result = 37 * result + (getManShipperCode() == null ? 0 : this.getManShipperCode().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCcNbr() == null ? 0 : this.getCcNbr().hashCode());
		result = 37 * result + (getWbsElement() == null ? 0 : this.getWbsElement().hashCode());
		result = 37 * result + (getSapVendorId() == null ? 0 : this.getSapVendorId().hashCode());
		result = 37 * result + (getSapVendorName() == null ? 0 : this.getSapVendorName().hashCode());
		result = 37 * result + (getPoDocLineItemNbr() == null ? 0 : this.getPoDocLineItemNbr().hashCode());
		result = 37 * result + (getPoLineItemTxt() == null ? 0 : this.getPoLineItemTxt().hashCode());
		result = 37 * result + (getPoCreateDate() == null ? 0 : this.getPoCreateDate().hashCode());
		result = 37 * result + (getCategory() == null ? 0 : this.getCategory().hashCode());
		result = 37 * result + (getInternalOrderNumber() == null ? 0 : this.getInternalOrderNumber().hashCode());
		return result;
	}

}
