package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpNspMultiStopTbId generated by hbm2java
 */
@Embeddable
public class ShpNspMultiStopTbId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal nspMultiStopId;
	private BigDecimal invoiceDetailsId;
	private BigDecimal scannedInvoiceId;
	private BigDecimal stopNumber;
	private String stopName;
	private String stopAddress1;
	private String stopAddress2;
	private String stopState;
	private String stopCity;
	private String stopZipcode;
	private String stopCountry;
	private BigDecimal carrierQty;
	private BigDecimal carrierWeight;
	private BigDecimal carrierUom;
	private String carrierChargeDesc;
	private String carrierFrtClass;
	private String bolNumber;
	private String poNumber;
	private String totalWeight;
	private String totalWeightUom;
	private String multiStopMode;
	private BigDecimal calculatedMiles;
	private BigDecimal serviceCodeId;
	private BigDecimal totalPallets;
	private String equipmentType;
	private String stopPort;

	public ShpNspMultiStopTbId() {
	}

	public ShpNspMultiStopTbId(BigDecimal nspMultiStopId, BigDecimal invoiceDetailsId, BigDecimal scannedInvoiceId,
			BigDecimal stopNumber, String stopName, String stopAddress1, String stopAddress2, String stopState,
			String stopCity, String stopZipcode, String stopCountry, BigDecimal carrierQty, BigDecimal carrierWeight,
			BigDecimal carrierUom, String carrierChargeDesc, String carrierFrtClass, String bolNumber, String poNumber,
			String totalWeight, String totalWeightUom, String multiStopMode, BigDecimal calculatedMiles,
			BigDecimal serviceCodeId, BigDecimal totalPallets, String equipmentType, String stopPort) {
		this.nspMultiStopId = nspMultiStopId;
		this.invoiceDetailsId = invoiceDetailsId;
		this.scannedInvoiceId = scannedInvoiceId;
		this.stopNumber = stopNumber;
		this.stopName = stopName;
		this.stopAddress1 = stopAddress1;
		this.stopAddress2 = stopAddress2;
		this.stopState = stopState;
		this.stopCity = stopCity;
		this.stopZipcode = stopZipcode;
		this.stopCountry = stopCountry;
		this.carrierQty = carrierQty;
		this.carrierWeight = carrierWeight;
		this.carrierUom = carrierUom;
		this.carrierChargeDesc = carrierChargeDesc;
		this.carrierFrtClass = carrierFrtClass;
		this.bolNumber = bolNumber;
		this.poNumber = poNumber;
		this.totalWeight = totalWeight;
		this.totalWeightUom = totalWeightUom;
		this.multiStopMode = multiStopMode;
		this.calculatedMiles = calculatedMiles;
		this.serviceCodeId = serviceCodeId;
		this.totalPallets = totalPallets;
		this.equipmentType = equipmentType;
		this.stopPort = stopPort;
	}

	@Column(name = "NSP_MULTI_STOP_ID", precision = 22, scale = 0)
	public BigDecimal getNspMultiStopId() {
		return this.nspMultiStopId;
	}

	public void setNspMultiStopId(BigDecimal nspMultiStopId) {
		this.nspMultiStopId = nspMultiStopId;
	}

	@Column(name = "INVOICE_DETAILS_ID", precision = 22, scale = 0)
	public BigDecimal getInvoiceDetailsId() {
		return this.invoiceDetailsId;
	}

	public void setInvoiceDetailsId(BigDecimal invoiceDetailsId) {
		this.invoiceDetailsId = invoiceDetailsId;
	}

	@Column(name = "SCANNED_INVOICE_ID", precision = 22, scale = 0)
	public BigDecimal getScannedInvoiceId() {
		return this.scannedInvoiceId;
	}

	public void setScannedInvoiceId(BigDecimal scannedInvoiceId) {
		this.scannedInvoiceId = scannedInvoiceId;
	}

	@Column(name = "STOP_NUMBER", precision = 22, scale = 0)
	public BigDecimal getStopNumber() {
		return this.stopNumber;
	}

	public void setStopNumber(BigDecimal stopNumber) {
		this.stopNumber = stopNumber;
	}

	@Column(name = "STOP_NAME", length = 100)
	public String getStopName() {
		return this.stopName;
	}

	public void setStopName(String stopName) {
		this.stopName = stopName;
	}

	@Column(name = "STOP_ADDRESS_1", length = 100)
	public String getStopAddress1() {
		return this.stopAddress1;
	}

	public void setStopAddress1(String stopAddress1) {
		this.stopAddress1 = stopAddress1;
	}

	@Column(name = "STOP_ADDRESS_2", length = 100)
	public String getStopAddress2() {
		return this.stopAddress2;
	}

	public void setStopAddress2(String stopAddress2) {
		this.stopAddress2 = stopAddress2;
	}

	@Column(name = "STOP_STATE", length = 100)
	public String getStopState() {
		return this.stopState;
	}

	public void setStopState(String stopState) {
		this.stopState = stopState;
	}

	@Column(name = "STOP_CITY", length = 100)
	public String getStopCity() {
		return this.stopCity;
	}

	public void setStopCity(String stopCity) {
		this.stopCity = stopCity;
	}

	@Column(name = "STOP_ZIPCODE", length = 100)
	public String getStopZipcode() {
		return this.stopZipcode;
	}

	public void setStopZipcode(String stopZipcode) {
		this.stopZipcode = stopZipcode;
	}

	@Column(name = "STOP_COUNTRY", length = 100)
	public String getStopCountry() {
		return this.stopCountry;
	}

	public void setStopCountry(String stopCountry) {
		this.stopCountry = stopCountry;
	}

	@Column(name = "CARRIER_QTY", precision = 22, scale = 0)
	public BigDecimal getCarrierQty() {
		return this.carrierQty;
	}

	public void setCarrierQty(BigDecimal carrierQty) {
		this.carrierQty = carrierQty;
	}

	@Column(name = "CARRIER_WEIGHT", precision = 22, scale = 0)
	public BigDecimal getCarrierWeight() {
		return this.carrierWeight;
	}

	public void setCarrierWeight(BigDecimal carrierWeight) {
		this.carrierWeight = carrierWeight;
	}

	@Column(name = "CARRIER_UOM", precision = 22, scale = 0)
	public BigDecimal getCarrierUom() {
		return this.carrierUom;
	}

	public void setCarrierUom(BigDecimal carrierUom) {
		this.carrierUom = carrierUom;
	}

	@Column(name = "CARRIER_CHARGE_DESC", length = 250)
	public String getCarrierChargeDesc() {
		return this.carrierChargeDesc;
	}

	public void setCarrierChargeDesc(String carrierChargeDesc) {
		this.carrierChargeDesc = carrierChargeDesc;
	}

	@Column(name = "CARRIER_FRT_CLASS", length = 10)
	public String getCarrierFrtClass() {
		return this.carrierFrtClass;
	}

	public void setCarrierFrtClass(String carrierFrtClass) {
		this.carrierFrtClass = carrierFrtClass;
	}

	@Column(name = "BOL_NUMBER", length = 100)
	public String getBolNumber() {
		return this.bolNumber;
	}

	public void setBolNumber(String bolNumber) {
		this.bolNumber = bolNumber;
	}

	@Column(name = "PO_NUMBER", length = 100)
	public String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "TOTAL_WEIGHT", length = 100)
	public String getTotalWeight() {
		return this.totalWeight;
	}

	public void setTotalWeight(String totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Column(name = "TOTAL_WEIGHT_UOM", length = 100)
	public String getTotalWeightUom() {
		return this.totalWeightUom;
	}

	public void setTotalWeightUom(String totalWeightUom) {
		this.totalWeightUom = totalWeightUom;
	}

	@Column(name = "MULTI_STOP_MODE", length = 10)
	public String getMultiStopMode() {
		return this.multiStopMode;
	}

	public void setMultiStopMode(String multiStopMode) {
		this.multiStopMode = multiStopMode;
	}

	@Column(name = "CALCULATED_MILES", precision = 22, scale = 0)
	public BigDecimal getCalculatedMiles() {
		return this.calculatedMiles;
	}

	public void setCalculatedMiles(BigDecimal calculatedMiles) {
		this.calculatedMiles = calculatedMiles;
	}

	@Column(name = "SERVICE_CODE_ID", precision = 22, scale = 0)
	public BigDecimal getServiceCodeId() {
		return this.serviceCodeId;
	}

	public void setServiceCodeId(BigDecimal serviceCodeId) {
		this.serviceCodeId = serviceCodeId;
	}

	@Column(name = "TOTAL_PALLETS", precision = 22, scale = 0)
	public BigDecimal getTotalPallets() {
		return this.totalPallets;
	}

	public void setTotalPallets(BigDecimal totalPallets) {
		this.totalPallets = totalPallets;
	}

	@Column(name = "EQUIPMENT_TYPE", length = 50)
	public String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(String equipmentType) {
		this.equipmentType = equipmentType;
	}

	@Column(name = "STOP_PORT", length = 50)
	public String getStopPort() {
		return this.stopPort;
	}

	public void setStopPort(String stopPort) {
		this.stopPort = stopPort;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpNspMultiStopTbId))
			return false;
		ShpNspMultiStopTbId castOther = (ShpNspMultiStopTbId) other;

		return ((this.getNspMultiStopId() == castOther.getNspMultiStopId())
				|| (this.getNspMultiStopId() != null && castOther.getNspMultiStopId() != null
						&& this.getNspMultiStopId().equals(castOther.getNspMultiStopId())))
				&& ((this.getInvoiceDetailsId() == castOther.getInvoiceDetailsId())
						|| (this.getInvoiceDetailsId() != null && castOther.getInvoiceDetailsId() != null
								&& this.getInvoiceDetailsId().equals(castOther.getInvoiceDetailsId())))
				&& ((this.getScannedInvoiceId() == castOther.getScannedInvoiceId())
						|| (this.getScannedInvoiceId() != null && castOther.getScannedInvoiceId() != null
								&& this.getScannedInvoiceId().equals(castOther.getScannedInvoiceId())))
				&& ((this.getStopNumber() == castOther.getStopNumber()) || (this.getStopNumber() != null
						&& castOther.getStopNumber() != null && this.getStopNumber().equals(castOther.getStopNumber())))
				&& ((this.getStopName() == castOther.getStopName()) || (this.getStopName() != null
						&& castOther.getStopName() != null && this.getStopName().equals(castOther.getStopName())))
				&& ((this.getStopAddress1() == castOther.getStopAddress1())
						|| (this.getStopAddress1() != null && castOther.getStopAddress1() != null
								&& this.getStopAddress1().equals(castOther.getStopAddress1())))
				&& ((this.getStopAddress2() == castOther.getStopAddress2())
						|| (this.getStopAddress2() != null && castOther.getStopAddress2() != null
								&& this.getStopAddress2().equals(castOther.getStopAddress2())))
				&& ((this.getStopState() == castOther.getStopState()) || (this.getStopState() != null
						&& castOther.getStopState() != null && this.getStopState().equals(castOther.getStopState())))
				&& ((this.getStopCity() == castOther.getStopCity()) || (this.getStopCity() != null
						&& castOther.getStopCity() != null && this.getStopCity().equals(castOther.getStopCity())))
				&& ((this.getStopZipcode() == castOther.getStopZipcode())
						|| (this.getStopZipcode() != null && castOther.getStopZipcode() != null
								&& this.getStopZipcode().equals(castOther.getStopZipcode())))
				&& ((this.getStopCountry() == castOther.getStopCountry())
						|| (this.getStopCountry() != null && castOther.getStopCountry() != null
								&& this.getStopCountry().equals(castOther.getStopCountry())))
				&& ((this.getCarrierQty() == castOther.getCarrierQty()) || (this.getCarrierQty() != null
						&& castOther.getCarrierQty() != null && this.getCarrierQty().equals(castOther.getCarrierQty())))
				&& ((this.getCarrierWeight() == castOther.getCarrierWeight())
						|| (this.getCarrierWeight() != null && castOther.getCarrierWeight() != null
								&& this.getCarrierWeight().equals(castOther.getCarrierWeight())))
				&& ((this.getCarrierUom() == castOther.getCarrierUom()) || (this.getCarrierUom() != null
						&& castOther.getCarrierUom() != null && this.getCarrierUom().equals(castOther.getCarrierUom())))
				&& ((this.getCarrierChargeDesc() == castOther.getCarrierChargeDesc())
						|| (this.getCarrierChargeDesc() != null && castOther.getCarrierChargeDesc() != null
								&& this.getCarrierChargeDesc().equals(castOther.getCarrierChargeDesc())))
				&& ((this.getCarrierFrtClass() == castOther.getCarrierFrtClass())
						|| (this.getCarrierFrtClass() != null && castOther.getCarrierFrtClass() != null
								&& this.getCarrierFrtClass().equals(castOther.getCarrierFrtClass())))
				&& ((this.getBolNumber() == castOther.getBolNumber()) || (this.getBolNumber() != null
						&& castOther.getBolNumber() != null && this.getBolNumber().equals(castOther.getBolNumber())))
				&& ((this.getPoNumber() == castOther.getPoNumber()) || (this.getPoNumber() != null
						&& castOther.getPoNumber() != null && this.getPoNumber().equals(castOther.getPoNumber())))
				&& ((this.getTotalWeight() == castOther.getTotalWeight())
						|| (this.getTotalWeight() != null && castOther.getTotalWeight() != null
								&& this.getTotalWeight().equals(castOther.getTotalWeight())))
				&& ((this.getTotalWeightUom() == castOther.getTotalWeightUom())
						|| (this.getTotalWeightUom() != null && castOther.getTotalWeightUom() != null
								&& this.getTotalWeightUom().equals(castOther.getTotalWeightUom())))
				&& ((this.getMultiStopMode() == castOther.getMultiStopMode())
						|| (this.getMultiStopMode() != null && castOther.getMultiStopMode() != null
								&& this.getMultiStopMode().equals(castOther.getMultiStopMode())))
				&& ((this.getCalculatedMiles() == castOther.getCalculatedMiles())
						|| (this.getCalculatedMiles() != null && castOther.getCalculatedMiles() != null
								&& this.getCalculatedMiles().equals(castOther.getCalculatedMiles())))
				&& ((this.getServiceCodeId() == castOther.getServiceCodeId())
						|| (this.getServiceCodeId() != null && castOther.getServiceCodeId() != null
								&& this.getServiceCodeId().equals(castOther.getServiceCodeId())))
				&& ((this.getTotalPallets() == castOther.getTotalPallets())
						|| (this.getTotalPallets() != null && castOther.getTotalPallets() != null
								&& this.getTotalPallets().equals(castOther.getTotalPallets())))
				&& ((this.getEquipmentType() == castOther.getEquipmentType())
						|| (this.getEquipmentType() != null && castOther.getEquipmentType() != null
								&& this.getEquipmentType().equals(castOther.getEquipmentType())))
				&& ((this.getStopPort() == castOther.getStopPort()) || (this.getStopPort() != null
						&& castOther.getStopPort() != null && this.getStopPort().equals(castOther.getStopPort())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNspMultiStopId() == null ? 0 : this.getNspMultiStopId().hashCode());
		result = 37 * result + (getInvoiceDetailsId() == null ? 0 : this.getInvoiceDetailsId().hashCode());
		result = 37 * result + (getScannedInvoiceId() == null ? 0 : this.getScannedInvoiceId().hashCode());
		result = 37 * result + (getStopNumber() == null ? 0 : this.getStopNumber().hashCode());
		result = 37 * result + (getStopName() == null ? 0 : this.getStopName().hashCode());
		result = 37 * result + (getStopAddress1() == null ? 0 : this.getStopAddress1().hashCode());
		result = 37 * result + (getStopAddress2() == null ? 0 : this.getStopAddress2().hashCode());
		result = 37 * result + (getStopState() == null ? 0 : this.getStopState().hashCode());
		result = 37 * result + (getStopCity() == null ? 0 : this.getStopCity().hashCode());
		result = 37 * result + (getStopZipcode() == null ? 0 : this.getStopZipcode().hashCode());
		result = 37 * result + (getStopCountry() == null ? 0 : this.getStopCountry().hashCode());
		result = 37 * result + (getCarrierQty() == null ? 0 : this.getCarrierQty().hashCode());
		result = 37 * result + (getCarrierWeight() == null ? 0 : this.getCarrierWeight().hashCode());
		result = 37 * result + (getCarrierUom() == null ? 0 : this.getCarrierUom().hashCode());
		result = 37 * result + (getCarrierChargeDesc() == null ? 0 : this.getCarrierChargeDesc().hashCode());
		result = 37 * result + (getCarrierFrtClass() == null ? 0 : this.getCarrierFrtClass().hashCode());
		result = 37 * result + (getBolNumber() == null ? 0 : this.getBolNumber().hashCode());
		result = 37 * result + (getPoNumber() == null ? 0 : this.getPoNumber().hashCode());
		result = 37 * result + (getTotalWeight() == null ? 0 : this.getTotalWeight().hashCode());
		result = 37 * result + (getTotalWeightUom() == null ? 0 : this.getTotalWeightUom().hashCode());
		result = 37 * result + (getMultiStopMode() == null ? 0 : this.getMultiStopMode().hashCode());
		result = 37 * result + (getCalculatedMiles() == null ? 0 : this.getCalculatedMiles().hashCode());
		result = 37 * result + (getServiceCodeId() == null ? 0 : this.getServiceCodeId().hashCode());
		result = 37 * result + (getTotalPallets() == null ? 0 : this.getTotalPallets().hashCode());
		result = 37 * result + (getEquipmentType() == null ? 0 : this.getEquipmentType().hashCode());
		result = 37 * result + (getStopPort() == null ? 0 : this.getStopPort().hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ShpNspMultiStopTbId [" + (nspMultiStopId != null ? "nspMultiStopId=" + nspMultiStopId + ", " : "")
				+ (invoiceDetailsId != null ? "invoiceDetailsId=" + invoiceDetailsId + ", " : "")
				+ (scannedInvoiceId != null ? "scannedInvoiceId=" + scannedInvoiceId + ", " : "")
				+ (stopNumber != null ? "stopNumber=" + stopNumber + ", " : "")
				+ (stopName != null ? "stopName=" + stopName + ", " : "")
				+ (stopAddress1 != null ? "stopAddress1=" + stopAddress1 + ", " : "")
				+ (stopAddress2 != null ? "stopAddress2=" + stopAddress2 + ", " : "")
				+ (stopState != null ? "stopState=" + stopState + ", " : "")
				+ (stopCity != null ? "stopCity=" + stopCity + ", " : "")
				+ (stopZipcode != null ? "stopZipcode=" + stopZipcode + ", " : "")
				+ (stopCountry != null ? "stopCountry=" + stopCountry + ", " : "")
				+ (carrierQty != null ? "carrierQty=" + carrierQty + ", " : "")
				+ (carrierWeight != null ? "carrierWeight=" + carrierWeight + ", " : "")
				+ (carrierUom != null ? "carrierUom=" + carrierUom + ", " : "")
				+ (carrierChargeDesc != null ? "carrierChargeDesc=" + carrierChargeDesc + ", " : "")
				+ (carrierFrtClass != null ? "carrierFrtClass=" + carrierFrtClass + ", " : "")
				+ (bolNumber != null ? "bolNumber=" + bolNumber + ", " : "")
				+ (poNumber != null ? "poNumber=" + poNumber + ", " : "")
				+ (totalWeight != null ? "totalWeight=" + totalWeight + ", " : "")
				+ (totalWeightUom != null ? "totalWeightUom=" + totalWeightUom + ", " : "")
				+ (multiStopMode != null ? "multiStopMode=" + multiStopMode + ", " : "")
				+ (calculatedMiles != null ? "calculatedMiles=" + calculatedMiles + ", " : "")
				+ (serviceCodeId != null ? "serviceCodeId=" + serviceCodeId + ", " : "")
				+ (totalPallets != null ? "totalPallets=" + totalPallets + ", " : "")
				+ (equipmentType != null ? "equipmentType=" + equipmentType + ", " : "")
				+ (stopPort != null ? "stopPort=" + stopPort : "") + "]";
	}

}
