package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpNspCarrierCreditTb generated by hbm2java
 */
@Entity
@Table(name = "SHP_NSP_CARRIER_CREDIT_TB")
public class ShpNspCarrierCreditTb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpNspCarrierCreditTbId id;

	public ShpNspCarrierCreditTb() {
	}

	public ShpNspCarrierCreditTb(ShpNspCarrierCreditTbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "creditId", column = @Column(name = "CREDIT_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "carrierId", column = @Column(name = "CARRIER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "creditType", column = @Column(name = "CREDIT_TYPE", length = 20) ),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 20) ),
			@AttributeOverride(name = "carrierRef", column = @Column(name = "CARRIER_REF", length = 20) ),
			@AttributeOverride(name = "totalCrAmount", column = @Column(name = "TOTAL_CR_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "usedCrAmount", column = @Column(name = "USED_CR_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "remainingCrAmount", column = @Column(name = "REMAINING_CR_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "comments", column = @Column(name = "COMMENTS", length = 500) ),
			@AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 7) ),
			@AttributeOverride(name = "createUser", column = @Column(name = "CREATE_USER", length = 20) ),
			@AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATE_DATE", length = 7) ),
			@AttributeOverride(name = "lastUpdateUser", column = @Column(name = "LAST_UPDATE_USER", length = 20) ),
			@AttributeOverride(name = "currencyId", column = @Column(name = "CURRENCY_ID", precision = 22, scale = 0) ) })
	public ShpNspCarrierCreditTbId getId() {
		return this.id;
	}

	public void setId(ShpNspCarrierCreditTbId id) {
		this.id = id;
	}

}
