package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpNspScannedInvoiceVwId generated by hbm2java
 */
@Embeddable
public class ShpNspScannedInvoiceVwId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Date createDate;
	private BigDecimal nspScannedInvoiceId;
	private String invoiceFileName;
	private String invoiceNumber;
	private BigDecimal customerId;
	private String customerName;
	private String createUser;
	private BigDecimal invoiceStatus;
	private String invoiceStatusText;
	private BigDecimal carrierId;
	private Date receivedDate;
	private BigDecimal templateId;
	private BigDecimal bulkInvCount;
	private String reason;
	private Boolean isOde;
	private String deAssignedTo;
	private Date deAssignedDate;
	private String qaAssignedTo;
	private Date qaAssignedDate;
	private String carrierName;

	public ShpNspScannedInvoiceVwId() {
	}

	public ShpNspScannedInvoiceVwId(Date createDate, BigDecimal nspScannedInvoiceId, String invoiceFileName,
			String invoiceNumber, BigDecimal customerId, String customerName, String createUser,
			BigDecimal invoiceStatus, String invoiceStatusText, BigDecimal carrierId, Date receivedDate,
			BigDecimal templateId, BigDecimal bulkInvCount, String reason, Boolean isOde, String deAssignedTo,
			Date deAssignedDate, String qaAssignedTo, Date qaAssignedDate, String carrierName) {
		this.createDate = createDate;
		this.nspScannedInvoiceId = nspScannedInvoiceId;
		this.invoiceFileName = invoiceFileName;
		this.invoiceNumber = invoiceNumber;
		this.customerId = customerId;
		this.customerName = customerName;
		this.createUser = createUser;
		this.invoiceStatus = invoiceStatus;
		this.invoiceStatusText = invoiceStatusText;
		this.carrierId = carrierId;
		this.receivedDate = receivedDate;
		this.templateId = templateId;
		this.bulkInvCount = bulkInvCount;
		this.reason = reason;
		this.isOde = isOde;
		this.deAssignedTo = deAssignedTo;
		this.deAssignedDate = deAssignedDate;
		this.qaAssignedTo = qaAssignedTo;
		this.qaAssignedDate = qaAssignedDate;
		this.carrierName = carrierName;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "NSP_SCANNED_INVOICE_ID", precision = 22, scale = 0)
	public BigDecimal getNspScannedInvoiceId() {
		return this.nspScannedInvoiceId;
	}

	public void setNspScannedInvoiceId(BigDecimal nspScannedInvoiceId) {
		this.nspScannedInvoiceId = nspScannedInvoiceId;
	}

	@Column(name = "INVOICE_FILE_NAME", length = 100)
	public String getInvoiceFileName() {
		return this.invoiceFileName;
	}

	public void setInvoiceFileName(String invoiceFileName) {
		this.invoiceFileName = invoiceFileName;
	}

	@Column(name = "INVOICE_NUMBER", length = 100)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "CUSTOMER_ID", precision = 22, scale = 0)
	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CUSTOMER_NAME", length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "CREATE_USER", length = 100)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "INVOICE_STATUS", precision = 22, scale = 0)
	public BigDecimal getInvoiceStatus() {
		return this.invoiceStatus;
	}

	public void setInvoiceStatus(BigDecimal invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}

	@Column(name = "INVOICE_STATUS_TEXT", length = 4000)
	public String getInvoiceStatusText() {
		return this.invoiceStatusText;
	}

	public void setInvoiceStatusText(String invoiceStatusText) {
		this.invoiceStatusText = invoiceStatusText;
	}

	@Column(name = "CARRIER_ID", precision = 22, scale = 0)
	public BigDecimal getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(BigDecimal carrierId) {
		this.carrierId = carrierId;
	}

	@Column(name = "RECEIVED_DATE", length = 7)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	@Column(name = "TEMPLATE_ID", precision = 22, scale = 0)
	public BigDecimal getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(BigDecimal templateId) {
		this.templateId = templateId;
	}

	@Column(name = "BULK_INV_COUNT", precision = 22, scale = 0)
	public BigDecimal getBulkInvCount() {
		return this.bulkInvCount;
	}

	public void setBulkInvCount(BigDecimal bulkInvCount) {
		this.bulkInvCount = bulkInvCount;
	}

	@Column(name = "REASON", length = 4000)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "IS_ODE", precision = 1, scale = 0)
	public Boolean getIsOde() {
		return this.isOde;
	}

	public void setIsOde(Boolean isOde) {
		this.isOde = isOde;
	}

	@Column(name = "DE_ASSIGNED_TO", length = 100)
	public String getDeAssignedTo() {
		return this.deAssignedTo;
	}

	public void setDeAssignedTo(String deAssignedTo) {
		this.deAssignedTo = deAssignedTo;
	}

	@Column(name = "DE_ASSIGNED_DATE", length = 7)
	public Date getDeAssignedDate() {
		return this.deAssignedDate;
	}

	public void setDeAssignedDate(Date deAssignedDate) {
		this.deAssignedDate = deAssignedDate;
	}

	@Column(name = "QA_ASSIGNED_TO", length = 100)
	public String getQaAssignedTo() {
		return this.qaAssignedTo;
	}

	public void setQaAssignedTo(String qaAssignedTo) {
		this.qaAssignedTo = qaAssignedTo;
	}

	@Column(name = "QA_ASSIGNED_DATE", length = 7)
	public Date getQaAssignedDate() {
		return this.qaAssignedDate;
	}

	public void setQaAssignedDate(Date qaAssignedDate) {
		this.qaAssignedDate = qaAssignedDate;
	}

	@Column(name = "CARRIER_NAME", length = 100)
	public String getCarrierName() {
		return this.carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpNspScannedInvoiceVwId))
			return false;
		ShpNspScannedInvoiceVwId castOther = (ShpNspScannedInvoiceVwId) other;

		return ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
				&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getNspScannedInvoiceId() == castOther.getNspScannedInvoiceId())
						|| (this.getNspScannedInvoiceId() != null && castOther.getNspScannedInvoiceId() != null
								&& this.getNspScannedInvoiceId().equals(castOther.getNspScannedInvoiceId())))
				&& ((this.getInvoiceFileName() == castOther.getInvoiceFileName())
						|| (this.getInvoiceFileName() != null && castOther.getInvoiceFileName() != null
								&& this.getInvoiceFileName().equals(castOther.getInvoiceFileName())))
				&& ((this.getInvoiceNumber() == castOther.getInvoiceNumber())
						|| (this.getInvoiceNumber() != null && castOther.getInvoiceNumber() != null
								&& this.getInvoiceNumber().equals(castOther.getInvoiceNumber())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCustomerName() == castOther.getCustomerName())
						|| (this.getCustomerName() != null && castOther.getCustomerName() != null
								&& this.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getCreateUser() == castOther.getCreateUser()) || (this.getCreateUser() != null
						&& castOther.getCreateUser() != null && this.getCreateUser().equals(castOther.getCreateUser())))
				&& ((this.getInvoiceStatus() == castOther.getInvoiceStatus())
						|| (this.getInvoiceStatus() != null && castOther.getInvoiceStatus() != null
								&& this.getInvoiceStatus().equals(castOther.getInvoiceStatus())))
				&& ((this.getInvoiceStatusText() == castOther.getInvoiceStatusText())
						|| (this.getInvoiceStatusText() != null && castOther.getInvoiceStatusText() != null
								&& this.getInvoiceStatusText().equals(castOther.getInvoiceStatusText())))
				&& ((this.getCarrierId() == castOther.getCarrierId()) || (this.getCarrierId() != null
						&& castOther.getCarrierId() != null && this.getCarrierId().equals(castOther.getCarrierId())))
				&& ((this.getReceivedDate() == castOther.getReceivedDate())
						|| (this.getReceivedDate() != null && castOther.getReceivedDate() != null
								&& this.getReceivedDate().equals(castOther.getReceivedDate())))
				&& ((this.getTemplateId() == castOther.getTemplateId()) || (this.getTemplateId() != null
						&& castOther.getTemplateId() != null && this.getTemplateId().equals(castOther.getTemplateId())))
				&& ((this.getBulkInvCount() == castOther.getBulkInvCount())
						|| (this.getBulkInvCount() != null && castOther.getBulkInvCount() != null
								&& this.getBulkInvCount().equals(castOther.getBulkInvCount())))
				&& ((this.getReason() == castOther.getReason()) || (this.getReason() != null
						&& castOther.getReason() != null && this.getReason().equals(castOther.getReason())))
				&& ((this.getIsOde() == castOther.getIsOde()) || (this.getIsOde() != null
						&& castOther.getIsOde() != null && this.getIsOde().equals(castOther.getIsOde())))
				&& ((this.getDeAssignedTo() == castOther.getDeAssignedTo())
						|| (this.getDeAssignedTo() != null && castOther.getDeAssignedTo() != null
								&& this.getDeAssignedTo().equals(castOther.getDeAssignedTo())))
				&& ((this.getDeAssignedDate() == castOther.getDeAssignedDate())
						|| (this.getDeAssignedDate() != null && castOther.getDeAssignedDate() != null
								&& this.getDeAssignedDate().equals(castOther.getDeAssignedDate())))
				&& ((this.getQaAssignedTo() == castOther.getQaAssignedTo())
						|| (this.getQaAssignedTo() != null && castOther.getQaAssignedTo() != null
								&& this.getQaAssignedTo().equals(castOther.getQaAssignedTo())))
				&& ((this.getQaAssignedDate() == castOther.getQaAssignedDate())
						|| (this.getQaAssignedDate() != null && castOther.getQaAssignedDate() != null
								&& this.getQaAssignedDate().equals(castOther.getQaAssignedDate())))
				&& ((this.getCarrierName() == castOther.getCarrierName())
						|| (this.getCarrierName() != null && castOther.getCarrierName() != null
								&& this.getCarrierName().equals(castOther.getCarrierName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getNspScannedInvoiceId() == null ? 0 : this.getNspScannedInvoiceId().hashCode());
		result = 37 * result + (getInvoiceFileName() == null ? 0 : this.getInvoiceFileName().hashCode());
		result = 37 * result + (getInvoiceNumber() == null ? 0 : this.getInvoiceNumber().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCustomerName() == null ? 0 : this.getCustomerName().hashCode());
		result = 37 * result + (getCreateUser() == null ? 0 : this.getCreateUser().hashCode());
		result = 37 * result + (getInvoiceStatus() == null ? 0 : this.getInvoiceStatus().hashCode());
		result = 37 * result + (getInvoiceStatusText() == null ? 0 : this.getInvoiceStatusText().hashCode());
		result = 37 * result + (getCarrierId() == null ? 0 : this.getCarrierId().hashCode());
		result = 37 * result + (getReceivedDate() == null ? 0 : this.getReceivedDate().hashCode());
		result = 37 * result + (getTemplateId() == null ? 0 : this.getTemplateId().hashCode());
		result = 37 * result + (getBulkInvCount() == null ? 0 : this.getBulkInvCount().hashCode());
		result = 37 * result + (getReason() == null ? 0 : this.getReason().hashCode());
		result = 37 * result + (getIsOde() == null ? 0 : this.getIsOde().hashCode());
		result = 37 * result + (getDeAssignedTo() == null ? 0 : this.getDeAssignedTo().hashCode());
		result = 37 * result + (getDeAssignedDate() == null ? 0 : this.getDeAssignedDate().hashCode());
		result = 37 * result + (getQaAssignedTo() == null ? 0 : this.getQaAssignedTo().hashCode());
		result = 37 * result + (getQaAssignedDate() == null ? 0 : this.getQaAssignedDate().hashCode());
		result = 37 * result + (getCarrierName() == null ? 0 : this.getCarrierName().hashCode());
		return result;
	}

}
