package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpNspInvDetailsTestTb generated by hbm2java
 */
@Entity
@Table(name = "SHP_NSP_INV_DETAILS_TEST_TB")
public class ShpNspInvDetailsTestTb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpNspInvDetailsTestTbId id;

	public ShpNspInvDetailsTestTb() {
	}

	public ShpNspInvDetailsTestTb(ShpNspInvDetailsTestTbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nspInvoiceDetailsId", column = @Column(name = "NSP_INVOICE_DETAILS_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceNumber", column = @Column(name = "INVOICE_NUMBER", length = 100) ),
			@AttributeOverride(name = "scannedInvoiceId", column = @Column(name = "SCANNED_INVOICE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "proNumber", column = @Column(name = "PRO_NUMBER", length = 500) ),
			@AttributeOverride(name = "bolNumber", column = @Column(name = "BOL_NUMBER", length = 100) ),
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "carrierId", column = @Column(name = "CARRIER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "billOption", column = @Column(name = "BILL_OPTION", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceMode", column = @Column(name = "INVOICE_MODE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "remitToAddress", column = @Column(name = "REMIT_TO_ADDRESS", length = 500) ),
			@AttributeOverride(name = "billDate", column = @Column(name = "BILL_DATE", length = 7) ),
			@AttributeOverride(name = "shipDate", column = @Column(name = "SHIP_DATE", length = 7) ),
			@AttributeOverride(name = "deliveryDate", column = @Column(name = "DELIVERY_DATE", length = 7) ),
			@AttributeOverride(name = "invoiceDueDate", column = @Column(name = "INVOICE_DUE_DATE", length = 7) ),
			@AttributeOverride(name = "totalWeight", column = @Column(name = "TOTAL_WEIGHT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "totalCharges", column = @Column(name = "TOTAL_CHARGES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "totalWeightUom", column = @Column(name = "TOTAL_WEIGHT_UOM", precision = 22, scale = 0) ),
			@AttributeOverride(name = "tarrifCode", column = @Column(name = "TARRIF_CODE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "glAccountsCode", column = @Column(name = "GL_ACCOUNTS_CODE", length = 250) ),
			@AttributeOverride(name = "runNo", column = @Column(name = "RUN_NO", length = 20) ),
			@AttributeOverride(name = "checkNo", column = @Column(name = "CHECK_NO", length = 20) ),
			@AttributeOverride(name = "checkDate", column = @Column(name = "CHECK_DATE", length = 7) ),
			@AttributeOverride(name = "checkAmount", column = @Column(name = "CHECK_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "shipperName", column = @Column(name = "SHIPPER_NAME", length = 100) ),
			@AttributeOverride(name = "shipperAddress1", column = @Column(name = "SHIPPER_ADDRESS_1", length = 100) ),
			@AttributeOverride(name = "shipperAddress2", column = @Column(name = "SHIPPER_ADDRESS_2", length = 100) ),
			@AttributeOverride(name = "shipperAddress3", column = @Column(name = "SHIPPER_ADDRESS_3", length = 100) ),
			@AttributeOverride(name = "shipperState", column = @Column(name = "SHIPPER_STATE", length = 100) ),
			@AttributeOverride(name = "shipperCity", column = @Column(name = "SHIPPER_CITY", length = 100) ),
			@AttributeOverride(name = "shipperZipcode", column = @Column(name = "SHIPPER_ZIPCODE", length = 100) ),
			@AttributeOverride(name = "shipperCountry", column = @Column(name = "SHIPPER_COUNTRY", length = 100) ),
			@AttributeOverride(name = "receiverName", column = @Column(name = "RECEIVER_NAME", length = 100) ),
			@AttributeOverride(name = "receiverAddress1", column = @Column(name = "RECEIVER_ADDRESS_1", length = 100) ),
			@AttributeOverride(name = "receiverAddress2", column = @Column(name = "RECEIVER_ADDRESS_2", length = 100) ),
			@AttributeOverride(name = "receiverAddress3", column = @Column(name = "RECEIVER_ADDRESS_3", length = 100) ),
			@AttributeOverride(name = "receiverState", column = @Column(name = "RECEIVER_STATE", length = 100) ),
			@AttributeOverride(name = "receiverCity", column = @Column(name = "RECEIVER_CITY", length = 100) ),
			@AttributeOverride(name = "receiverZipcode", column = @Column(name = "RECEIVER_ZIPCODE", length = 100) ),
			@AttributeOverride(name = "receiverCountry", column = @Column(name = "RECEIVER_COUNTRY", length = 100) ),
			@AttributeOverride(name = "reference1", column = @Column(name = "REFERENCE1", length = 4000) ),
			@AttributeOverride(name = "reference2", column = @Column(name = "REFERENCE2", length = 2500) ),
			@AttributeOverride(name = "dataEntryComments", column = @Column(name = "DATA_ENTRY_COMMENTS", length = 500) ),
			@AttributeOverride(name = "auditorComments", column = @Column(name = "AUDITOR_COMMENTS", length = 500) ),
			@AttributeOverride(name = "customerComments", column = @Column(name = "CUSTOMER_COMMENTS", length = 500) ),
			@AttributeOverride(name = "subtotalAmount", column = @Column(name = "SUBTOTAL_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceTax1Amount", column = @Column(name = "INVOICE_TAX1_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceTax2Amount", column = @Column(name = "INVOICE_TAX2_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "totalDueAmount", column = @Column(name = "TOTAL_DUE_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "paidAmount", column = @Column(name = "PAID_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "balanceAmount", column = @Column(name = "BALANCE_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isBillOptionCorrect", column = @Column(name = "IS_BILL_OPTION_CORRECT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isDuplicateBillingChecked", column = @Column(name = "IS_DUPLICATE_BILLING_CHECKED", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isFreightChargeChecked", column = @Column(name = "IS_FREIGHT_CHARGE_CHECKED", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isFuelSurchargesChecked", column = @Column(name = "IS_FUEL_SURCHARGES_CHECKED", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isAccessorialsChecked", column = @Column(name = "IS_ACCESSORIALS_CHECKED", precision = 22, scale = 0) ),
			@AttributeOverride(name = "isDocumentationChecked", column = @Column(name = "IS_DOCUMENTATION_CHECKED", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceStatus", column = @Column(name = "INVOICE_STATUS", precision = 22, scale = 0) ),
			@AttributeOverride(name = "createUser", column = @Column(name = "CREATE_USER", length = 100) ),
			@AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 7) ),
			@AttributeOverride(name = "lastUpdateUser", column = @Column(name = "LAST_UPDATE_USER", length = 100) ),
			@AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATE_DATE", length = 7) ),
			@AttributeOverride(name = "poNumber", column = @Column(name = "PO_NUMBER", length = 250) ),
			@AttributeOverride(name = "ratingContract", column = @Column(name = "RATING_CONTRACT", length = 100) ),
			@AttributeOverride(name = "invoiceType", column = @Column(name = "INVOICE_TYPE", length = 2) ),
			@AttributeOverride(name = "origInvoiceId", column = @Column(name = "ORIG_INVOICE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "closedDate", column = @Column(name = "CLOSED_DATE", length = 7) ),
			@AttributeOverride(name = "closedBy", column = @Column(name = "CLOSED_BY", length = 20) ),
			@AttributeOverride(name = "custAction", column = @Column(name = "CUST_ACTION", precision = 22, scale = 0) ),
			@AttributeOverride(name = "custActionBy", column = @Column(name = "CUST_ACTION_BY", length = 20) ),
			@AttributeOverride(name = "custActionDate", column = @Column(name = "CUST_ACTION_DATE", length = 7) ),
			@AttributeOverride(name = "receivedDate", column = @Column(name = "RECEIVED_DATE", length = 7) ),
			@AttributeOverride(name = "childCarrierName", column = @Column(name = "CHILD_CARRIER_NAME", length = 500) ),
			@AttributeOverride(name = "portOfOrigin", column = @Column(name = "PORT_OF_ORIGIN", length = 100) ),
			@AttributeOverride(name = "portOfDestination", column = @Column(name = "PORT_OF_DESTINATION", length = 100) ),
			@AttributeOverride(name = "dwExtractFlag", column = @Column(name = "DW_EXTRACT_FLAG", precision = 22, scale = 0) ),
			@AttributeOverride(name = "serviceCodeId", column = @Column(name = "SERVICE_CODE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "linkedDocuments", column = @Column(name = "LINKED_DOCUMENTS", length = 500) ),
			@AttributeOverride(name = "fileId", column = @Column(name = "FILE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "reference3", column = @Column(name = "REFERENCE3", length = 2500) ),
			@AttributeOverride(name = "reference4", column = @Column(name = "REFERENCE4", length = 2500) ),
			@AttributeOverride(name = "billedMiles", column = @Column(name = "BILLED_MILES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "ratedMiles", column = @Column(name = "RATED_MILES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "currencyCode", column = @Column(name = "CURRENCY_CODE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "equipmentType", column = @Column(name = "EQUIPMENT_TYPE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "billtoName", column = @Column(name = "BILLTO_NAME", length = 100) ),
			@AttributeOverride(name = "billtoAddress1", column = @Column(name = "BILLTO_ADDRESS_1", length = 100) ),
			@AttributeOverride(name = "billtoAddress2", column = @Column(name = "BILLTO_ADDRESS_2", length = 100) ),
			@AttributeOverride(name = "billtoAddress3", column = @Column(name = "BILLTO_ADDRESS_3", length = 100) ),
			@AttributeOverride(name = "billtoState", column = @Column(name = "BILLTO_STATE", length = 100) ),
			@AttributeOverride(name = "billtoCity", column = @Column(name = "BILLTO_CITY", length = 100) ),
			@AttributeOverride(name = "billtoZipcode", column = @Column(name = "BILLTO_ZIPCODE", length = 100) ),
			@AttributeOverride(name = "billtoCountry", column = @Column(name = "BILLTO_COUNTRY", length = 100) ),
			@AttributeOverride(name = "invoiceHsTaxAmount", column = @Column(name = "INVOICE_HS_TAX_AMOUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "accountNumber", column = @Column(name = "ACCOUNT_NUMBER", length = 100) ),
			@AttributeOverride(name = "addressType", column = @Column(name = "ADDRESS_TYPE", length = 1) ),
			@AttributeOverride(name = "ratingComments", column = @Column(name = "RATING_COMMENTS", length = 4000) ),
			@AttributeOverride(name = "actualMiles", column = @Column(name = "ACTUAL_MILES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "exportCode", column = @Column(name = "EXPORT_CODE", length = 100) ),
			@AttributeOverride(name = "importCode", column = @Column(name = "IMPORT_CODE", length = 100) ),
			@AttributeOverride(name = "shipperVatin", column = @Column(name = "SHIPPER_VATIN", length = 50) ),
			@AttributeOverride(name = "receiverVatin", column = @Column(name = "RECEIVER_VATIN", length = 50) ),
			@AttributeOverride(name = "usdTotalCharges", column = @Column(name = "USD_TOTAL_CHARGES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "ftpserverLogId", column = @Column(name = "FTPSERVER_LOG_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "ladingDescription", column = @Column(name = "LADING_DESCRIPTION", length = 4000) ),
			@AttributeOverride(name = "totalInvoicedVolume", column = @Column(name = "TOTAL_INVOICED_VOLUME", precision = 22, scale = 0) ),
			@AttributeOverride(name = "totalInvoicedUom", column = @Column(name = "TOTAL_INVOICED_UOM", precision = 22, scale = 0) ),
			@AttributeOverride(name = "totalShipUnits", column = @Column(name = "TOTAL_SHIP_UNITS", precision = 22, scale = 0) ),
			@AttributeOverride(name = "totalShipUom", column = @Column(name = "TOTAL_SHIP_UOM", precision = 22, scale = 0) ),
			@AttributeOverride(name = "exceptionReason", column = @Column(name = "EXCEPTION_REASON", precision = 22, scale = 0) ),
			@AttributeOverride(name = "loadMatchExcpDate", column = @Column(name = "LOAD_MATCH_EXCP_DATE", length = 7) ),
			@AttributeOverride(name = "shipperRegion", column = @Column(name = "SHIPPER_REGION", length = 25) ),
			@AttributeOverride(name = "receiverRegion", column = @Column(name = "RECEIVER_REGION", length = 25) ),
			@AttributeOverride(name = "laneId", column = @Column(name = "LANE_ID", length = 400) ),
			@AttributeOverride(name = "incoTermPoint", column = @Column(name = "INCO_TERM_POINT", length = 20) ),
			@AttributeOverride(name = "houseBolNumber", column = @Column(name = "HOUSE_BOL_NUMBER", length = 20) ),
			@AttributeOverride(name = "masterBolNumber", column = @Column(name = "MASTER_BOL_NUMBER", length = 20) ),
			@AttributeOverride(name = "incoTermCode", column = @Column(name = "INCO_TERM_CODE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "interlineDeliveryDate", column = @Column(name = "INTERLINE_DELIVERY_DATE", length = 7) ),
			@AttributeOverride(name = "interlineVesselName", column = @Column(name = "INTERLINE_VESSEL_NAME", length = 500) ),
			@AttributeOverride(name = "interlineVoyageNumber", column = @Column(name = "INTERLINE_VOYAGE_NUMBER", length = 500) ),
			@AttributeOverride(name = "customsDocumentNumber", column = @Column(name = "CUSTOMS_DOCUMENT_NUMBER", length = 20) ),
			@AttributeOverride(name = "laneDescription", column = @Column(name = "LANE_DESCRIPTION", length = 400) ),
			@AttributeOverride(name = "glbEquipType", column = @Column(name = "GLB_EQUIP_TYPE", length = 100) ),
			@AttributeOverride(name = "distanceUom", column = @Column(name = "DISTANCE_UOM", precision = 22, scale = 0) ),
			@AttributeOverride(name = "interlineCarrier", column = @Column(name = "INTERLINE_CARRIER", precision = 22, scale = 0) ),
			@AttributeOverride(name = "calculatedMiles", column = @Column(name = "CALCULATED_MILES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invPageCount", column = @Column(name = "INV_PAGE_COUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceIsaNumber", column = @Column(name = "INVOICE_ISA_NUMBER", length = 250) ) })
	public ShpNspInvDetailsTestTbId getId() {
		return this.id;
	}

	public void setId(ShpNspInvDetailsTestTbId id) {
		this.id = id;
	}

}
