package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpNspOrdMatchingTb generated by hbm2java
 */
@Entity
@Table(name = "SHP_NSP_ORD_MATCHING_TB")
public class ShpNspOrdMatchingTb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpNspOrdMatchingTbId id;

	public ShpNspOrdMatchingTb() {
	}

	public ShpNspOrdMatchingTb(ShpNspOrdMatchingTbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nspOrdMatchingId", column = @Column(name = "NSP_ORD_MATCHING_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "orderNumber", column = @Column(name = "ORDER_NUMBER", length = 100) ),
			@AttributeOverride(name = "city", column = @Column(name = "CITY", length = 100) ),
			@AttributeOverride(name = "state", column = @Column(name = "STATE", length = 100) ),
			@AttributeOverride(name = "zipCode", column = @Column(name = "ZIP_CODE", length = 100) ),
			@AttributeOverride(name = "fileName", column = @Column(name = "FILE_NAME", length = 250) ),
			@AttributeOverride(name = "skuNumbers", column = @Column(name = "SKU_NUMBERS", length = 250) ),
			@AttributeOverride(name = "createUser", column = @Column(name = "CREATE_USER", length = 50) ),
			@AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 7) ),
			@AttributeOverride(name = "lastUpdateUser", column = @Column(name = "LAST_UPDATE_USER", length = 50) ),
			@AttributeOverride(name = "lastUpdateDate", column = @Column(name = "LAST_UPDATE_DATE", length = 7) ),
			@AttributeOverride(name = "fileType", column = @Column(name = "FILE_TYPE", length = 50) ),
			@AttributeOverride(name = "manShipperCode", column = @Column(name = "MAN_SHIPPER_CODE", length = 50) ),
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "ccNbr", column = @Column(name = "CC_NBR", length = 100) ),
			@AttributeOverride(name = "wbsElement", column = @Column(name = "WBS_ELEMENT", length = 100) ),
			@AttributeOverride(name = "sapVendorId", column = @Column(name = "SAP_VENDOR_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "sapVendorName", column = @Column(name = "SAP_VENDOR_NAME", length = 100) ),
			@AttributeOverride(name = "poDocLineItemNbr", column = @Column(name = "PO_DOC_LINE_ITEM_NBR", precision = 22, scale = 0) ),
			@AttributeOverride(name = "poLineItemTxt", column = @Column(name = "PO_LINE_ITEM_TXT", length = 100) ),
			@AttributeOverride(name = "poCreateDate", column = @Column(name = "PO_CREATE_DATE", length = 7) ),
			@AttributeOverride(name = "category", column = @Column(name = "CATEGORY", length = 100) ),
			@AttributeOverride(name = "internalOrderNumber", column = @Column(name = "INTERNAL_ORDER_NUMBER", length = 100) ) })
	public ShpNspOrdMatchingTbId getId() {
		return this.id;
	}

	public void setId(ShpNspOrdMatchingTbId id) {
		this.id = id;
	}

}
