package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpNspScannedInvoiceVw generated by hbm2java
 */
@Entity
@Table(name = "SHP_NSP_SCANNED_INVOICE_VW")
public class ShpNspScannedInvoiceVw implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpNspScannedInvoiceVwId id;

	public ShpNspScannedInvoiceVw() {
	}

	public ShpNspScannedInvoiceVw(ShpNspScannedInvoiceVwId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "createDate", column = @Column(name = "CREATE_DATE", length = 7) ),
			@AttributeOverride(name = "nspScannedInvoiceId", column = @Column(name = "NSP_SCANNED_INVOICE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceFileName", column = @Column(name = "INVOICE_FILE_NAME", length = 100) ),
			@AttributeOverride(name = "invoiceNumber", column = @Column(name = "INVOICE_NUMBER", length = 100) ),
			@AttributeOverride(name = "customerId", column = @Column(name = "CUSTOMER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "customerName", column = @Column(name = "CUSTOMER_NAME", length = 100) ),
			@AttributeOverride(name = "createUser", column = @Column(name = "CREATE_USER", length = 100) ),
			@AttributeOverride(name = "invoiceStatus", column = @Column(name = "INVOICE_STATUS", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceStatusText", column = @Column(name = "INVOICE_STATUS_TEXT", length = 4000) ),
			@AttributeOverride(name = "carrierId", column = @Column(name = "CARRIER_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "receivedDate", column = @Column(name = "RECEIVED_DATE", length = 7) ),
			@AttributeOverride(name = "templateId", column = @Column(name = "TEMPLATE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "bulkInvCount", column = @Column(name = "BULK_INV_COUNT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "reason", column = @Column(name = "REASON", length = 4000) ),
			@AttributeOverride(name = "isOde", column = @Column(name = "IS_ODE", precision = 1, scale = 0) ),
			@AttributeOverride(name = "deAssignedTo", column = @Column(name = "DE_ASSIGNED_TO", length = 100) ),
			@AttributeOverride(name = "deAssignedDate", column = @Column(name = "DE_ASSIGNED_DATE", length = 7) ),
			@AttributeOverride(name = "qaAssignedTo", column = @Column(name = "QA_ASSIGNED_TO", length = 100) ),
			@AttributeOverride(name = "qaAssignedDate", column = @Column(name = "QA_ASSIGNED_DATE", length = 7) ),
			@AttributeOverride(name = "carrierName", column = @Column(name = "CARRIER_NAME", length = 100) ) })
	public ShpNspScannedInvoiceVwId getId() {
		return this.id;
	}

	public void setId(ShpNspScannedInvoiceVwId id) {
		this.id = id;
	}

}
