package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpNspMultiStopTb generated by hbm2java
 */
@Entity
@Table(name = "SHP_NSP_MULTI_STOP_TB")
public class ShpNspMultiStopTb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpNspMultiStopTbId id;

	public ShpNspMultiStopTb() {
	}

	public ShpNspMultiStopTb(ShpNspMultiStopTbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nspMultiStopId", column = @Column(name = "NSP_MULTI_STOP_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "invoiceDetailsId", column = @Column(name = "INVOICE_DETAILS_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "scannedInvoiceId", column = @Column(name = "SCANNED_INVOICE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "stopNumber", column = @Column(name = "STOP_NUMBER", precision = 22, scale = 0) ),
			@AttributeOverride(name = "stopName", column = @Column(name = "STOP_NAME", length = 100) ),
			@AttributeOverride(name = "stopAddress1", column = @Column(name = "STOP_ADDRESS_1", length = 100) ),
			@AttributeOverride(name = "stopAddress2", column = @Column(name = "STOP_ADDRESS_2", length = 100) ),
			@AttributeOverride(name = "stopState", column = @Column(name = "STOP_STATE", length = 100) ),
			@AttributeOverride(name = "stopCity", column = @Column(name = "STOP_CITY", length = 100) ),
			@AttributeOverride(name = "stopZipcode", column = @Column(name = "STOP_ZIPCODE", length = 100) ),
			@AttributeOverride(name = "stopCountry", column = @Column(name = "STOP_COUNTRY", length = 100) ),
			@AttributeOverride(name = "carrierQty", column = @Column(name = "CARRIER_QTY", precision = 22, scale = 0) ),
			@AttributeOverride(name = "carrierWeight", column = @Column(name = "CARRIER_WEIGHT", precision = 22, scale = 0) ),
			@AttributeOverride(name = "carrierUom", column = @Column(name = "CARRIER_UOM", precision = 22, scale = 0) ),
			@AttributeOverride(name = "carrierChargeDesc", column = @Column(name = "CARRIER_CHARGE_DESC", length = 250) ),
			@AttributeOverride(name = "carrierFrtClass", column = @Column(name = "CARRIER_FRT_CLASS", length = 10) ),
			@AttributeOverride(name = "bolNumber", column = @Column(name = "BOL_NUMBER", length = 100) ),
			@AttributeOverride(name = "poNumber", column = @Column(name = "PO_NUMBER", length = 100) ),
			@AttributeOverride(name = "totalWeight", column = @Column(name = "TOTAL_WEIGHT", length = 100) ),
			@AttributeOverride(name = "totalWeightUom", column = @Column(name = "TOTAL_WEIGHT_UOM", length = 100) ),
			@AttributeOverride(name = "multiStopMode", column = @Column(name = "MULTI_STOP_MODE", length = 10) ),
			@AttributeOverride(name = "calculatedMiles", column = @Column(name = "CALCULATED_MILES", precision = 22, scale = 0) ),
			@AttributeOverride(name = "serviceCodeId", column = @Column(name = "SERVICE_CODE_ID", precision = 22, scale = 0) ),
			@AttributeOverride(name = "totalPallets", column = @Column(name = "TOTAL_PALLETS", precision = 22, scale = 0) ),
			@AttributeOverride(name = "equipmentType", column = @Column(name = "EQUIPMENT_TYPE", length = 50) ),
			@AttributeOverride(name = "stopPort", column = @Column(name = "STOP_PORT", length = 50) ) })
	public ShpNspMultiStopTbId getId() {
		return this.id;
	}

	public void setId(ShpNspMultiStopTbId id) {
		this.id = id;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ShpNspMultiStopTb [" + (id != null ? "id=" + id : "") + "]";
	}

}
