package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpNspCcLinkedTbId generated by hbm2java
 */
@Embeddable
public class ShpNspCcLinkedTbId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal ccLinkedId;
	private BigDecimal creditId;
	private BigDecimal invoiceId;
	private String glCode;
	private BigDecimal creditAmount;
	private BigDecimal linkSeq;
	private BigDecimal status;
	private Date createDate;
	private String createUser;
	private Date lastUpdateDate;
	private String lastUpdateUser;
	private BigDecimal usedCrAmt;
	private String displayLink;

	public ShpNspCcLinkedTbId() {
	}

	public ShpNspCcLinkedTbId(BigDecimal ccLinkedId, BigDecimal creditId, BigDecimal invoiceId, String glCode,
			BigDecimal creditAmount, BigDecimal linkSeq, BigDecimal status, Date createDate, String createUser,
			Date lastUpdateDate, String lastUpdateUser, BigDecimal usedCrAmt, String displayLink) {
		this.ccLinkedId = ccLinkedId;
		this.creditId = creditId;
		this.invoiceId = invoiceId;
		this.glCode = glCode;
		this.creditAmount = creditAmount;
		this.linkSeq = linkSeq;
		this.status = status;
		this.createDate = createDate;
		this.createUser = createUser;
		this.lastUpdateDate = lastUpdateDate;
		this.lastUpdateUser = lastUpdateUser;
		this.usedCrAmt = usedCrAmt;
		this.displayLink = displayLink;
	}

	@Column(name = "CC_LINKED_ID", precision = 22, scale = 0)
	public BigDecimal getCcLinkedId() {
		return this.ccLinkedId;
	}

	public void setCcLinkedId(BigDecimal ccLinkedId) {
		this.ccLinkedId = ccLinkedId;
	}

	@Column(name = "CREDIT_ID", precision = 22, scale = 0)
	public BigDecimal getCreditId() {
		return this.creditId;
	}

	public void setCreditId(BigDecimal creditId) {
		this.creditId = creditId;
	}

	@Column(name = "INVOICE_ID", precision = 22, scale = 0)
	public BigDecimal getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(BigDecimal invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "GL_CODE", length = 20)
	public String getGlCode() {
		return this.glCode;
	}

	public void setGlCode(String glCode) {
		this.glCode = glCode;
	}

	@Column(name = "CREDIT_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getCreditAmount() {
		return this.creditAmount;
	}

	public void setCreditAmount(BigDecimal creditAmount) {
		this.creditAmount = creditAmount;
	}

	@Column(name = "LINK_SEQ", precision = 22, scale = 0)
	public BigDecimal getLinkSeq() {
		return this.linkSeq;
	}

	public void setLinkSeq(BigDecimal linkSeq) {
		this.linkSeq = linkSeq;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER", length = 20)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "LAST_UPDATE_USER", length = 20)
	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	@Column(name = "USED_CR_AMT", precision = 22, scale = 0)
	public BigDecimal getUsedCrAmt() {
		return this.usedCrAmt;
	}

	public void setUsedCrAmt(BigDecimal usedCrAmt) {
		this.usedCrAmt = usedCrAmt;
	}

	@Column(name = "DISPLAY_LINK", length = 500)
	public String getDisplayLink() {
		return this.displayLink;
	}

	public void setDisplayLink(String displayLink) {
		this.displayLink = displayLink;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpNspCcLinkedTbId))
			return false;
		ShpNspCcLinkedTbId castOther = (ShpNspCcLinkedTbId) other;

		return ((this.getCcLinkedId() == castOther.getCcLinkedId()) || (this.getCcLinkedId() != null
				&& castOther.getCcLinkedId() != null && this.getCcLinkedId().equals(castOther.getCcLinkedId())))
				&& ((this.getCreditId() == castOther.getCreditId()) || (this.getCreditId() != null
						&& castOther.getCreditId() != null && this.getCreditId().equals(castOther.getCreditId())))
				&& ((this.getInvoiceId() == castOther.getInvoiceId()) || (this.getInvoiceId() != null
						&& castOther.getInvoiceId() != null && this.getInvoiceId().equals(castOther.getInvoiceId())))
				&& ((this.getGlCode() == castOther.getGlCode()) || (this.getGlCode() != null
						&& castOther.getGlCode() != null && this.getGlCode().equals(castOther.getGlCode())))
				&& ((this.getCreditAmount() == castOther.getCreditAmount())
						|| (this.getCreditAmount() != null && castOther.getCreditAmount() != null
								&& this.getCreditAmount().equals(castOther.getCreditAmount())))
				&& ((this.getLinkSeq() == castOther.getLinkSeq()) || (this.getLinkSeq() != null
						&& castOther.getLinkSeq() != null && this.getLinkSeq().equals(castOther.getLinkSeq())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateUser() == castOther.getCreateUser()) || (this.getCreateUser() != null
						&& castOther.getCreateUser() != null && this.getCreateUser().equals(castOther.getCreateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate())
						|| (this.getLastUpdateDate() != null && castOther.getLastUpdateDate() != null
								&& this.getLastUpdateDate().equals(castOther.getLastUpdateDate())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser())
						|| (this.getLastUpdateUser() != null && castOther.getLastUpdateUser() != null
								&& this.getLastUpdateUser().equals(castOther.getLastUpdateUser())))
				&& ((this.getUsedCrAmt() == castOther.getUsedCrAmt()) || (this.getUsedCrAmt() != null
						&& castOther.getUsedCrAmt() != null && this.getUsedCrAmt().equals(castOther.getUsedCrAmt())))
				&& ((this.getDisplayLink() == castOther.getDisplayLink())
						|| (this.getDisplayLink() != null && castOther.getDisplayLink() != null
								&& this.getDisplayLink().equals(castOther.getDisplayLink())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCcLinkedId() == null ? 0 : this.getCcLinkedId().hashCode());
		result = 37 * result + (getCreditId() == null ? 0 : this.getCreditId().hashCode());
		result = 37 * result + (getInvoiceId() == null ? 0 : this.getInvoiceId().hashCode());
		result = 37 * result + (getGlCode() == null ? 0 : this.getGlCode().hashCode());
		result = 37 * result + (getCreditAmount() == null ? 0 : this.getCreditAmount().hashCode());
		result = 37 * result + (getLinkSeq() == null ? 0 : this.getLinkSeq().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getCreateUser() == null ? 0 : this.getCreateUser().hashCode());
		result = 37 * result + (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate().hashCode());
		result = 37 * result + (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser().hashCode());
		result = 37 * result + (getUsedCrAmt() == null ? 0 : this.getUsedCrAmt().hashCode());
		result = 37 * result + (getDisplayLink() == null ? 0 : this.getDisplayLink().hashCode());
		return result;
	}

}
