package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpNspInvDetailsTestTbId generated by hbm2java
 */
@Embeddable
public class ShpNspInvDetailsTestTbId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal nspInvoiceDetailsId;
	private String invoiceNumber;
	private BigDecimal scannedInvoiceId;
	private String proNumber;
	private String bolNumber;
	private BigDecimal customerId;
	private BigDecimal carrierId;
	private BigDecimal billOption;
	private BigDecimal invoiceMode;
	private String remitToAddress;
	private Date billDate;
	private Date shipDate;
	private Date deliveryDate;
	private Date invoiceDueDate;
	private BigDecimal totalWeight;
	private BigDecimal totalCharges;
	private BigDecimal totalWeightUom;
	private BigDecimal tarrifCode;
	private String glAccountsCode;
	private String runNo;
	private String checkNo;
	private Date checkDate;
	private BigDecimal checkAmount;
	private String shipperName;
	private String shipperAddress1;
	private String shipperAddress2;
	private String shipperAddress3;
	private String shipperState;
	private String shipperCity;
	private String shipperZipcode;
	private String shipperCountry;
	private String receiverName;
	private String receiverAddress1;
	private String receiverAddress2;
	private String receiverAddress3;
	private String receiverState;
	private String receiverCity;
	private String receiverZipcode;
	private String receiverCountry;
	private String reference1;
	private String reference2;
	private String dataEntryComments;
	private String auditorComments;
	private String customerComments;
	private BigDecimal subtotalAmount;
	private BigDecimal invoiceTax1Amount;
	private BigDecimal invoiceTax2Amount;
	private BigDecimal totalDueAmount;
	private BigDecimal paidAmount;
	private BigDecimal balanceAmount;
	private BigDecimal isBillOptionCorrect;
	private BigDecimal isDuplicateBillingChecked;
	private BigDecimal isFreightChargeChecked;
	private BigDecimal isFuelSurchargesChecked;
	private BigDecimal isAccessorialsChecked;
	private BigDecimal isDocumentationChecked;
	private BigDecimal invoiceStatus;
	private String createUser;
	private Date createDate;
	private String lastUpdateUser;
	private Date lastUpdateDate;
	private String poNumber;
	private String ratingContract;
	private String invoiceType;
	private BigDecimal origInvoiceId;
	private Date closedDate;
	private String closedBy;
	private BigDecimal custAction;
	private String custActionBy;
	private Date custActionDate;
	private Date receivedDate;
	private String childCarrierName;
	private String portOfOrigin;
	private String portOfDestination;
	private BigDecimal dwExtractFlag;
	private BigDecimal serviceCodeId;
	private String linkedDocuments;
	private BigDecimal fileId;
	private String reference3;
	private String reference4;
	private BigDecimal billedMiles;
	private BigDecimal ratedMiles;
	private BigDecimal currencyCode;
	private BigDecimal equipmentType;
	private String billtoName;
	private String billtoAddress1;
	private String billtoAddress2;
	private String billtoAddress3;
	private String billtoState;
	private String billtoCity;
	private String billtoZipcode;
	private String billtoCountry;
	private BigDecimal invoiceHsTaxAmount;
	private String accountNumber;
	private String addressType;
	private String ratingComments;
	private BigDecimal actualMiles;
	private String exportCode;
	private String importCode;
	private String shipperVatin;
	private String receiverVatin;
	private BigDecimal usdTotalCharges;
	private BigDecimal ftpserverLogId;
	private String ladingDescription;
	private BigDecimal totalInvoicedVolume;
	private BigDecimal totalInvoicedUom;
	private BigDecimal totalShipUnits;
	private BigDecimal totalShipUom;
	private BigDecimal exceptionReason;
	private Date loadMatchExcpDate;
	private String shipperRegion;
	private String receiverRegion;
	private String laneId;
	private String incoTermPoint;
	private String houseBolNumber;
	private String masterBolNumber;
	private BigDecimal incoTermCode;
	private Date interlineDeliveryDate;
	private String interlineVesselName;
	private String interlineVoyageNumber;
	private String customsDocumentNumber;
	private String laneDescription;
	private String glbEquipType;
	private BigDecimal distanceUom;
	private BigDecimal interlineCarrier;
	private BigDecimal calculatedMiles;
	private BigDecimal invPageCount;
	private String invoiceIsaNumber;

	public ShpNspInvDetailsTestTbId() {
	}

	public ShpNspInvDetailsTestTbId(BigDecimal nspInvoiceDetailsId, String invoiceNumber, BigDecimal scannedInvoiceId,
			String proNumber, String bolNumber, BigDecimal customerId, BigDecimal carrierId, BigDecimal billOption,
			BigDecimal invoiceMode, String remitToAddress, Date billDate, Date shipDate, Date deliveryDate,
			Date invoiceDueDate, BigDecimal totalWeight, BigDecimal totalCharges, BigDecimal totalWeightUom,
			BigDecimal tarrifCode, String glAccountsCode, String runNo, String checkNo, Date checkDate,
			BigDecimal checkAmount, String shipperName, String shipperAddress1, String shipperAddress2,
			String shipperAddress3, String shipperState, String shipperCity, String shipperZipcode,
			String shipperCountry, String receiverName, String receiverAddress1, String receiverAddress2,
			String receiverAddress3, String receiverState, String receiverCity, String receiverZipcode,
			String receiverCountry, String reference1, String reference2, String dataEntryComments,
			String auditorComments, String customerComments, BigDecimal subtotalAmount, BigDecimal invoiceTax1Amount,
			BigDecimal invoiceTax2Amount, BigDecimal totalDueAmount, BigDecimal paidAmount, BigDecimal balanceAmount,
			BigDecimal isBillOptionCorrect, BigDecimal isDuplicateBillingChecked, BigDecimal isFreightChargeChecked,
			BigDecimal isFuelSurchargesChecked, BigDecimal isAccessorialsChecked, BigDecimal isDocumentationChecked,
			BigDecimal invoiceStatus, String createUser, Date createDate, String lastUpdateUser, Date lastUpdateDate,
			String poNumber, String ratingContract, String invoiceType, BigDecimal origInvoiceId, Date closedDate,
			String closedBy, BigDecimal custAction, String custActionBy, Date custActionDate, Date receivedDate,
			String childCarrierName, String portOfOrigin, String portOfDestination, BigDecimal dwExtractFlag,
			BigDecimal serviceCodeId, String linkedDocuments, BigDecimal fileId, String reference3, String reference4,
			BigDecimal billedMiles, BigDecimal ratedMiles, BigDecimal currencyCode, BigDecimal equipmentType,
			String billtoName, String billtoAddress1, String billtoAddress2, String billtoAddress3, String billtoState,
			String billtoCity, String billtoZipcode, String billtoCountry, BigDecimal invoiceHsTaxAmount,
			String accountNumber, String addressType, String ratingComments, BigDecimal actualMiles, String exportCode,
			String importCode, String shipperVatin, String receiverVatin, BigDecimal usdTotalCharges,
			BigDecimal ftpserverLogId, String ladingDescription, BigDecimal totalInvoicedVolume,
			BigDecimal totalInvoicedUom, BigDecimal totalShipUnits, BigDecimal totalShipUom, BigDecimal exceptionReason,
			Date loadMatchExcpDate, String shipperRegion, String receiverRegion, String laneId, String incoTermPoint,
			String houseBolNumber, String masterBolNumber, BigDecimal incoTermCode, Date interlineDeliveryDate,
			String interlineVesselName, String interlineVoyageNumber, String customsDocumentNumber,
			String laneDescription, String glbEquipType, BigDecimal distanceUom, BigDecimal interlineCarrier,
			BigDecimal calculatedMiles, BigDecimal invPageCount, String invoiceIsaNumber) {
		this.nspInvoiceDetailsId = nspInvoiceDetailsId;
		this.invoiceNumber = invoiceNumber;
		this.scannedInvoiceId = scannedInvoiceId;
		this.proNumber = proNumber;
		this.bolNumber = bolNumber;
		this.customerId = customerId;
		this.carrierId = carrierId;
		this.billOption = billOption;
		this.invoiceMode = invoiceMode;
		this.remitToAddress = remitToAddress;
		this.billDate = billDate;
		this.shipDate = shipDate;
		this.deliveryDate = deliveryDate;
		this.invoiceDueDate = invoiceDueDate;
		this.totalWeight = totalWeight;
		this.totalCharges = totalCharges;
		this.totalWeightUom = totalWeightUom;
		this.tarrifCode = tarrifCode;
		this.glAccountsCode = glAccountsCode;
		this.runNo = runNo;
		this.checkNo = checkNo;
		this.checkDate = checkDate;
		this.checkAmount = checkAmount;
		this.shipperName = shipperName;
		this.shipperAddress1 = shipperAddress1;
		this.shipperAddress2 = shipperAddress2;
		this.shipperAddress3 = shipperAddress3;
		this.shipperState = shipperState;
		this.shipperCity = shipperCity;
		this.shipperZipcode = shipperZipcode;
		this.shipperCountry = shipperCountry;
		this.receiverName = receiverName;
		this.receiverAddress1 = receiverAddress1;
		this.receiverAddress2 = receiverAddress2;
		this.receiverAddress3 = receiverAddress3;
		this.receiverState = receiverState;
		this.receiverCity = receiverCity;
		this.receiverZipcode = receiverZipcode;
		this.receiverCountry = receiverCountry;
		this.reference1 = reference1;
		this.reference2 = reference2;
		this.dataEntryComments = dataEntryComments;
		this.auditorComments = auditorComments;
		this.customerComments = customerComments;
		this.subtotalAmount = subtotalAmount;
		this.invoiceTax1Amount = invoiceTax1Amount;
		this.invoiceTax2Amount = invoiceTax2Amount;
		this.totalDueAmount = totalDueAmount;
		this.paidAmount = paidAmount;
		this.balanceAmount = balanceAmount;
		this.isBillOptionCorrect = isBillOptionCorrect;
		this.isDuplicateBillingChecked = isDuplicateBillingChecked;
		this.isFreightChargeChecked = isFreightChargeChecked;
		this.isFuelSurchargesChecked = isFuelSurchargesChecked;
		this.isAccessorialsChecked = isAccessorialsChecked;
		this.isDocumentationChecked = isDocumentationChecked;
		this.invoiceStatus = invoiceStatus;
		this.createUser = createUser;
		this.createDate = createDate;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.poNumber = poNumber;
		this.ratingContract = ratingContract;
		this.invoiceType = invoiceType;
		this.origInvoiceId = origInvoiceId;
		this.closedDate = closedDate;
		this.closedBy = closedBy;
		this.custAction = custAction;
		this.custActionBy = custActionBy;
		this.custActionDate = custActionDate;
		this.receivedDate = receivedDate;
		this.childCarrierName = childCarrierName;
		this.portOfOrigin = portOfOrigin;
		this.portOfDestination = portOfDestination;
		this.dwExtractFlag = dwExtractFlag;
		this.serviceCodeId = serviceCodeId;
		this.linkedDocuments = linkedDocuments;
		this.fileId = fileId;
		this.reference3 = reference3;
		this.reference4 = reference4;
		this.billedMiles = billedMiles;
		this.ratedMiles = ratedMiles;
		this.currencyCode = currencyCode;
		this.equipmentType = equipmentType;
		this.billtoName = billtoName;
		this.billtoAddress1 = billtoAddress1;
		this.billtoAddress2 = billtoAddress2;
		this.billtoAddress3 = billtoAddress3;
		this.billtoState = billtoState;
		this.billtoCity = billtoCity;
		this.billtoZipcode = billtoZipcode;
		this.billtoCountry = billtoCountry;
		this.invoiceHsTaxAmount = invoiceHsTaxAmount;
		this.accountNumber = accountNumber;
		this.addressType = addressType;
		this.ratingComments = ratingComments;
		this.actualMiles = actualMiles;
		this.exportCode = exportCode;
		this.importCode = importCode;
		this.shipperVatin = shipperVatin;
		this.receiverVatin = receiverVatin;
		this.usdTotalCharges = usdTotalCharges;
		this.ftpserverLogId = ftpserverLogId;
		this.ladingDescription = ladingDescription;
		this.totalInvoicedVolume = totalInvoicedVolume;
		this.totalInvoicedUom = totalInvoicedUom;
		this.totalShipUnits = totalShipUnits;
		this.totalShipUom = totalShipUom;
		this.exceptionReason = exceptionReason;
		this.loadMatchExcpDate = loadMatchExcpDate;
		this.shipperRegion = shipperRegion;
		this.receiverRegion = receiverRegion;
		this.laneId = laneId;
		this.incoTermPoint = incoTermPoint;
		this.houseBolNumber = houseBolNumber;
		this.masterBolNumber = masterBolNumber;
		this.incoTermCode = incoTermCode;
		this.interlineDeliveryDate = interlineDeliveryDate;
		this.interlineVesselName = interlineVesselName;
		this.interlineVoyageNumber = interlineVoyageNumber;
		this.customsDocumentNumber = customsDocumentNumber;
		this.laneDescription = laneDescription;
		this.glbEquipType = glbEquipType;
		this.distanceUom = distanceUom;
		this.interlineCarrier = interlineCarrier;
		this.calculatedMiles = calculatedMiles;
		this.invPageCount = invPageCount;
		this.invoiceIsaNumber = invoiceIsaNumber;
	}

	@Column(name = "NSP_INVOICE_DETAILS_ID", precision = 22, scale = 0)
	public BigDecimal getNspInvoiceDetailsId() {
		return this.nspInvoiceDetailsId;
	}

	public void setNspInvoiceDetailsId(BigDecimal nspInvoiceDetailsId) {
		this.nspInvoiceDetailsId = nspInvoiceDetailsId;
	}

	@Column(name = "INVOICE_NUMBER", length = 100)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "SCANNED_INVOICE_ID", precision = 22, scale = 0)
	public BigDecimal getScannedInvoiceId() {
		return this.scannedInvoiceId;
	}

	public void setScannedInvoiceId(BigDecimal scannedInvoiceId) {
		this.scannedInvoiceId = scannedInvoiceId;
	}

	@Column(name = "PRO_NUMBER", length = 500)
	public String getProNumber() {
		return this.proNumber;
	}

	public void setProNumber(String proNumber) {
		this.proNumber = proNumber;
	}

	@Column(name = "BOL_NUMBER", length = 100)
	public String getBolNumber() {
		return this.bolNumber;
	}

	public void setBolNumber(String bolNumber) {
		this.bolNumber = bolNumber;
	}

	@Column(name = "CUSTOMER_ID", precision = 22, scale = 0)
	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CARRIER_ID", precision = 22, scale = 0)
	public BigDecimal getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(BigDecimal carrierId) {
		this.carrierId = carrierId;
	}

	@Column(name = "BILL_OPTION", precision = 22, scale = 0)
	public BigDecimal getBillOption() {
		return this.billOption;
	}

	public void setBillOption(BigDecimal billOption) {
		this.billOption = billOption;
	}

	@Column(name = "INVOICE_MODE", precision = 22, scale = 0)
	public BigDecimal getInvoiceMode() {
		return this.invoiceMode;
	}

	public void setInvoiceMode(BigDecimal invoiceMode) {
		this.invoiceMode = invoiceMode;
	}

	@Column(name = "REMIT_TO_ADDRESS", length = 500)
	public String getRemitToAddress() {
		return this.remitToAddress;
	}

	public void setRemitToAddress(String remitToAddress) {
		this.remitToAddress = remitToAddress;
	}

	@Column(name = "BILL_DATE", length = 7)
	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	@Column(name = "SHIP_DATE", length = 7)
	public Date getShipDate() {
		return this.shipDate;
	}

	public void setShipDate(Date shipDate) {
		this.shipDate = shipDate;
	}

	@Column(name = "DELIVERY_DATE", length = 7)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Column(name = "INVOICE_DUE_DATE", length = 7)
	public Date getInvoiceDueDate() {
		return this.invoiceDueDate;
	}

	public void setInvoiceDueDate(Date invoiceDueDate) {
		this.invoiceDueDate = invoiceDueDate;
	}

	@Column(name = "TOTAL_WEIGHT", precision = 22, scale = 0)
	public BigDecimal getTotalWeight() {
		return this.totalWeight;
	}

	public void setTotalWeight(BigDecimal totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Column(name = "TOTAL_CHARGES", precision = 22, scale = 0)
	public BigDecimal getTotalCharges() {
		return this.totalCharges;
	}

	public void setTotalCharges(BigDecimal totalCharges) {
		this.totalCharges = totalCharges;
	}

	@Column(name = "TOTAL_WEIGHT_UOM", precision = 22, scale = 0)
	public BigDecimal getTotalWeightUom() {
		return this.totalWeightUom;
	}

	public void setTotalWeightUom(BigDecimal totalWeightUom) {
		this.totalWeightUom = totalWeightUom;
	}

	@Column(name = "TARRIF_CODE", precision = 22, scale = 0)
	public BigDecimal getTarrifCode() {
		return this.tarrifCode;
	}

	public void setTarrifCode(BigDecimal tarrifCode) {
		this.tarrifCode = tarrifCode;
	}

	@Column(name = "GL_ACCOUNTS_CODE", length = 250)
	public String getGlAccountsCode() {
		return this.glAccountsCode;
	}

	public void setGlAccountsCode(String glAccountsCode) {
		this.glAccountsCode = glAccountsCode;
	}

	@Column(name = "RUN_NO", length = 20)
	public String getRunNo() {
		return this.runNo;
	}

	public void setRunNo(String runNo) {
		this.runNo = runNo;
	}

	@Column(name = "CHECK_NO", length = 20)
	public String getCheckNo() {
		return this.checkNo;
	}

	public void setCheckNo(String checkNo) {
		this.checkNo = checkNo;
	}

	@Column(name = "CHECK_DATE", length = 7)
	public Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

	@Column(name = "CHECK_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getCheckAmount() {
		return this.checkAmount;
	}

	public void setCheckAmount(BigDecimal checkAmount) {
		this.checkAmount = checkAmount;
	}

	@Column(name = "SHIPPER_NAME", length = 100)
	public String getShipperName() {
		return this.shipperName;
	}

	public void setShipperName(String shipperName) {
		this.shipperName = shipperName;
	}

	@Column(name = "SHIPPER_ADDRESS_1", length = 100)
	public String getShipperAddress1() {
		return this.shipperAddress1;
	}

	public void setShipperAddress1(String shipperAddress1) {
		this.shipperAddress1 = shipperAddress1;
	}

	@Column(name = "SHIPPER_ADDRESS_2", length = 100)
	public String getShipperAddress2() {
		return this.shipperAddress2;
	}

	public void setShipperAddress2(String shipperAddress2) {
		this.shipperAddress2 = shipperAddress2;
	}

	@Column(name = "SHIPPER_ADDRESS_3", length = 100)
	public String getShipperAddress3() {
		return this.shipperAddress3;
	}

	public void setShipperAddress3(String shipperAddress3) {
		this.shipperAddress3 = shipperAddress3;
	}

	@Column(name = "SHIPPER_STATE", length = 100)
	public String getShipperState() {
		return this.shipperState;
	}

	public void setShipperState(String shipperState) {
		this.shipperState = shipperState;
	}

	@Column(name = "SHIPPER_CITY", length = 100)
	public String getShipperCity() {
		return this.shipperCity;
	}

	public void setShipperCity(String shipperCity) {
		this.shipperCity = shipperCity;
	}

	@Column(name = "SHIPPER_ZIPCODE", length = 100)
	public String getShipperZipcode() {
		return this.shipperZipcode;
	}

	public void setShipperZipcode(String shipperZipcode) {
		this.shipperZipcode = shipperZipcode;
	}

	@Column(name = "SHIPPER_COUNTRY", length = 100)
	public String getShipperCountry() {
		return this.shipperCountry;
	}

	public void setShipperCountry(String shipperCountry) {
		this.shipperCountry = shipperCountry;
	}

	@Column(name = "RECEIVER_NAME", length = 100)
	public String getReceiverName() {
		return this.receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	@Column(name = "RECEIVER_ADDRESS_1", length = 100)
	public String getReceiverAddress1() {
		return this.receiverAddress1;
	}

	public void setReceiverAddress1(String receiverAddress1) {
		this.receiverAddress1 = receiverAddress1;
	}

	@Column(name = "RECEIVER_ADDRESS_2", length = 100)
	public String getReceiverAddress2() {
		return this.receiverAddress2;
	}

	public void setReceiverAddress2(String receiverAddress2) {
		this.receiverAddress2 = receiverAddress2;
	}

	@Column(name = "RECEIVER_ADDRESS_3", length = 100)
	public String getReceiverAddress3() {
		return this.receiverAddress3;
	}

	public void setReceiverAddress3(String receiverAddress3) {
		this.receiverAddress3 = receiverAddress3;
	}

	@Column(name = "RECEIVER_STATE", length = 100)
	public String getReceiverState() {
		return this.receiverState;
	}

	public void setReceiverState(String receiverState) {
		this.receiverState = receiverState;
	}

	@Column(name = "RECEIVER_CITY", length = 100)
	public String getReceiverCity() {
		return this.receiverCity;
	}

	public void setReceiverCity(String receiverCity) {
		this.receiverCity = receiverCity;
	}

	@Column(name = "RECEIVER_ZIPCODE", length = 100)
	public String getReceiverZipcode() {
		return this.receiverZipcode;
	}

	public void setReceiverZipcode(String receiverZipcode) {
		this.receiverZipcode = receiverZipcode;
	}

	@Column(name = "RECEIVER_COUNTRY", length = 100)
	public String getReceiverCountry() {
		return this.receiverCountry;
	}

	public void setReceiverCountry(String receiverCountry) {
		this.receiverCountry = receiverCountry;
	}

	@Column(name = "REFERENCE1", length = 4000)
	public String getReference1() {
		return this.reference1;
	}

	public void setReference1(String reference1) {
		this.reference1 = reference1;
	}

	@Column(name = "REFERENCE2", length = 2500)
	public String getReference2() {
		return this.reference2;
	}

	public void setReference2(String reference2) {
		this.reference2 = reference2;
	}

	@Column(name = "DATA_ENTRY_COMMENTS", length = 500)
	public String getDataEntryComments() {
		return this.dataEntryComments;
	}

	public void setDataEntryComments(String dataEntryComments) {
		this.dataEntryComments = dataEntryComments;
	}

	@Column(name = "AUDITOR_COMMENTS", length = 500)
	public String getAuditorComments() {
		return this.auditorComments;
	}

	public void setAuditorComments(String auditorComments) {
		this.auditorComments = auditorComments;
	}

	@Column(name = "CUSTOMER_COMMENTS", length = 500)
	public String getCustomerComments() {
		return this.customerComments;
	}

	public void setCustomerComments(String customerComments) {
		this.customerComments = customerComments;
	}

	@Column(name = "SUBTOTAL_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getSubtotalAmount() {
		return this.subtotalAmount;
	}

	public void setSubtotalAmount(BigDecimal subtotalAmount) {
		this.subtotalAmount = subtotalAmount;
	}

	@Column(name = "INVOICE_TAX1_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getInvoiceTax1Amount() {
		return this.invoiceTax1Amount;
	}

	public void setInvoiceTax1Amount(BigDecimal invoiceTax1Amount) {
		this.invoiceTax1Amount = invoiceTax1Amount;
	}

	@Column(name = "INVOICE_TAX2_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getInvoiceTax2Amount() {
		return this.invoiceTax2Amount;
	}

	public void setInvoiceTax2Amount(BigDecimal invoiceTax2Amount) {
		this.invoiceTax2Amount = invoiceTax2Amount;
	}

	@Column(name = "TOTAL_DUE_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getTotalDueAmount() {
		return this.totalDueAmount;
	}

	public void setTotalDueAmount(BigDecimal totalDueAmount) {
		this.totalDueAmount = totalDueAmount;
	}

	@Column(name = "PAID_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(BigDecimal paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Column(name = "BALANCE_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getBalanceAmount() {
		return this.balanceAmount;
	}

	public void setBalanceAmount(BigDecimal balanceAmount) {
		this.balanceAmount = balanceAmount;
	}

	@Column(name = "IS_BILL_OPTION_CORRECT", precision = 22, scale = 0)
	public BigDecimal getIsBillOptionCorrect() {
		return this.isBillOptionCorrect;
	}

	public void setIsBillOptionCorrect(BigDecimal isBillOptionCorrect) {
		this.isBillOptionCorrect = isBillOptionCorrect;
	}

	@Column(name = "IS_DUPLICATE_BILLING_CHECKED", precision = 22, scale = 0)
	public BigDecimal getIsDuplicateBillingChecked() {
		return this.isDuplicateBillingChecked;
	}

	public void setIsDuplicateBillingChecked(BigDecimal isDuplicateBillingChecked) {
		this.isDuplicateBillingChecked = isDuplicateBillingChecked;
	}

	@Column(name = "IS_FREIGHT_CHARGE_CHECKED", precision = 22, scale = 0)
	public BigDecimal getIsFreightChargeChecked() {
		return this.isFreightChargeChecked;
	}

	public void setIsFreightChargeChecked(BigDecimal isFreightChargeChecked) {
		this.isFreightChargeChecked = isFreightChargeChecked;
	}

	@Column(name = "IS_FUEL_SURCHARGES_CHECKED", precision = 22, scale = 0)
	public BigDecimal getIsFuelSurchargesChecked() {
		return this.isFuelSurchargesChecked;
	}

	public void setIsFuelSurchargesChecked(BigDecimal isFuelSurchargesChecked) {
		this.isFuelSurchargesChecked = isFuelSurchargesChecked;
	}

	@Column(name = "IS_ACCESSORIALS_CHECKED", precision = 22, scale = 0)
	public BigDecimal getIsAccessorialsChecked() {
		return this.isAccessorialsChecked;
	}

	public void setIsAccessorialsChecked(BigDecimal isAccessorialsChecked) {
		this.isAccessorialsChecked = isAccessorialsChecked;
	}

	@Column(name = "IS_DOCUMENTATION_CHECKED", precision = 22, scale = 0)
	public BigDecimal getIsDocumentationChecked() {
		return this.isDocumentationChecked;
	}

	public void setIsDocumentationChecked(BigDecimal isDocumentationChecked) {
		this.isDocumentationChecked = isDocumentationChecked;
	}

	@Column(name = "INVOICE_STATUS", precision = 22, scale = 0)
	public BigDecimal getInvoiceStatus() {
		return this.invoiceStatus;
	}

	public void setInvoiceStatus(BigDecimal invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}

	@Column(name = "CREATE_USER", length = 100)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "LAST_UPDATE_USER", length = 100)
	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "PO_NUMBER", length = 250)
	public String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Column(name = "RATING_CONTRACT", length = 100)
	public String getRatingContract() {
		return this.ratingContract;
	}

	public void setRatingContract(String ratingContract) {
		this.ratingContract = ratingContract;
	}

	@Column(name = "INVOICE_TYPE", length = 2)
	public String getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	@Column(name = "ORIG_INVOICE_ID", precision = 22, scale = 0)
	public BigDecimal getOrigInvoiceId() {
		return this.origInvoiceId;
	}

	public void setOrigInvoiceId(BigDecimal origInvoiceId) {
		this.origInvoiceId = origInvoiceId;
	}

	@Column(name = "CLOSED_DATE", length = 7)
	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	@Column(name = "CLOSED_BY", length = 20)
	public String getClosedBy() {
		return this.closedBy;
	}

	public void setClosedBy(String closedBy) {
		this.closedBy = closedBy;
	}

	@Column(name = "CUST_ACTION", precision = 22, scale = 0)
	public BigDecimal getCustAction() {
		return this.custAction;
	}

	public void setCustAction(BigDecimal custAction) {
		this.custAction = custAction;
	}

	@Column(name = "CUST_ACTION_BY", length = 20)
	public String getCustActionBy() {
		return this.custActionBy;
	}

	public void setCustActionBy(String custActionBy) {
		this.custActionBy = custActionBy;
	}

	@Column(name = "CUST_ACTION_DATE", length = 7)
	public Date getCustActionDate() {
		return this.custActionDate;
	}

	public void setCustActionDate(Date custActionDate) {
		this.custActionDate = custActionDate;
	}

	@Column(name = "RECEIVED_DATE", length = 7)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	@Column(name = "CHILD_CARRIER_NAME", length = 500)
	public String getChildCarrierName() {
		return this.childCarrierName;
	}

	public void setChildCarrierName(String childCarrierName) {
		this.childCarrierName = childCarrierName;
	}

	@Column(name = "PORT_OF_ORIGIN", length = 100)
	public String getPortOfOrigin() {
		return this.portOfOrigin;
	}

	public void setPortOfOrigin(String portOfOrigin) {
		this.portOfOrigin = portOfOrigin;
	}

	@Column(name = "PORT_OF_DESTINATION", length = 100)
	public String getPortOfDestination() {
		return this.portOfDestination;
	}

	public void setPortOfDestination(String portOfDestination) {
		this.portOfDestination = portOfDestination;
	}

	@Column(name = "DW_EXTRACT_FLAG", precision = 22, scale = 0)
	public BigDecimal getDwExtractFlag() {
		return this.dwExtractFlag;
	}

	public void setDwExtractFlag(BigDecimal dwExtractFlag) {
		this.dwExtractFlag = dwExtractFlag;
	}

	@Column(name = "SERVICE_CODE_ID", precision = 22, scale = 0)
	public BigDecimal getServiceCodeId() {
		return this.serviceCodeId;
	}

	public void setServiceCodeId(BigDecimal serviceCodeId) {
		this.serviceCodeId = serviceCodeId;
	}

	@Column(name = "LINKED_DOCUMENTS", length = 500)
	public String getLinkedDocuments() {
		return this.linkedDocuments;
	}

	public void setLinkedDocuments(String linkedDocuments) {
		this.linkedDocuments = linkedDocuments;
	}

	@Column(name = "FILE_ID", precision = 22, scale = 0)
	public BigDecimal getFileId() {
		return this.fileId;
	}

	public void setFileId(BigDecimal fileId) {
		this.fileId = fileId;
	}

	@Column(name = "REFERENCE3", length = 2500)
	public String getReference3() {
		return this.reference3;
	}

	public void setReference3(String reference3) {
		this.reference3 = reference3;
	}

	@Column(name = "REFERENCE4", length = 2500)
	public String getReference4() {
		return this.reference4;
	}

	public void setReference4(String reference4) {
		this.reference4 = reference4;
	}

	@Column(name = "BILLED_MILES", precision = 22, scale = 0)
	public BigDecimal getBilledMiles() {
		return this.billedMiles;
	}

	public void setBilledMiles(BigDecimal billedMiles) {
		this.billedMiles = billedMiles;
	}

	@Column(name = "RATED_MILES", precision = 22, scale = 0)
	public BigDecimal getRatedMiles() {
		return this.ratedMiles;
	}

	public void setRatedMiles(BigDecimal ratedMiles) {
		this.ratedMiles = ratedMiles;
	}

	@Column(name = "CURRENCY_CODE", precision = 22, scale = 0)
	public BigDecimal getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(BigDecimal currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "EQUIPMENT_TYPE", precision = 22, scale = 0)
	public BigDecimal getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(BigDecimal equipmentType) {
		this.equipmentType = equipmentType;
	}

	@Column(name = "BILLTO_NAME", length = 100)
	public String getBilltoName() {
		return this.billtoName;
	}

	public void setBilltoName(String billtoName) {
		this.billtoName = billtoName;
	}

	@Column(name = "BILLTO_ADDRESS_1", length = 100)
	public String getBilltoAddress1() {
		return this.billtoAddress1;
	}

	public void setBilltoAddress1(String billtoAddress1) {
		this.billtoAddress1 = billtoAddress1;
	}

	@Column(name = "BILLTO_ADDRESS_2", length = 100)
	public String getBilltoAddress2() {
		return this.billtoAddress2;
	}

	public void setBilltoAddress2(String billtoAddress2) {
		this.billtoAddress2 = billtoAddress2;
	}

	@Column(name = "BILLTO_ADDRESS_3", length = 100)
	public String getBilltoAddress3() {
		return this.billtoAddress3;
	}

	public void setBilltoAddress3(String billtoAddress3) {
		this.billtoAddress3 = billtoAddress3;
	}

	@Column(name = "BILLTO_STATE", length = 100)
	public String getBilltoState() {
		return this.billtoState;
	}

	public void setBilltoState(String billtoState) {
		this.billtoState = billtoState;
	}

	@Column(name = "BILLTO_CITY", length = 100)
	public String getBilltoCity() {
		return this.billtoCity;
	}

	public void setBilltoCity(String billtoCity) {
		this.billtoCity = billtoCity;
	}

	@Column(name = "BILLTO_ZIPCODE", length = 100)
	public String getBilltoZipcode() {
		return this.billtoZipcode;
	}

	public void setBilltoZipcode(String billtoZipcode) {
		this.billtoZipcode = billtoZipcode;
	}

	@Column(name = "BILLTO_COUNTRY", length = 100)
	public String getBilltoCountry() {
		return this.billtoCountry;
	}

	public void setBilltoCountry(String billtoCountry) {
		this.billtoCountry = billtoCountry;
	}

	@Column(name = "INVOICE_HS_TAX_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getInvoiceHsTaxAmount() {
		return this.invoiceHsTaxAmount;
	}

	public void setInvoiceHsTaxAmount(BigDecimal invoiceHsTaxAmount) {
		this.invoiceHsTaxAmount = invoiceHsTaxAmount;
	}

	@Column(name = "ACCOUNT_NUMBER", length = 100)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "ADDRESS_TYPE", length = 1)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@Column(name = "RATING_COMMENTS", length = 4000)
	public String getRatingComments() {
		return this.ratingComments;
	}

	public void setRatingComments(String ratingComments) {
		this.ratingComments = ratingComments;
	}

	@Column(name = "ACTUAL_MILES", precision = 22, scale = 0)
	public BigDecimal getActualMiles() {
		return this.actualMiles;
	}

	public void setActualMiles(BigDecimal actualMiles) {
		this.actualMiles = actualMiles;
	}

	@Column(name = "EXPORT_CODE", length = 100)
	public String getExportCode() {
		return this.exportCode;
	}

	public void setExportCode(String exportCode) {
		this.exportCode = exportCode;
	}

	@Column(name = "IMPORT_CODE", length = 100)
	public String getImportCode() {
		return this.importCode;
	}

	public void setImportCode(String importCode) {
		this.importCode = importCode;
	}

	@Column(name = "SHIPPER_VATIN", length = 50)
	public String getShipperVatin() {
		return this.shipperVatin;
	}

	public void setShipperVatin(String shipperVatin) {
		this.shipperVatin = shipperVatin;
	}

	@Column(name = "RECEIVER_VATIN", length = 50)
	public String getReceiverVatin() {
		return this.receiverVatin;
	}

	public void setReceiverVatin(String receiverVatin) {
		this.receiverVatin = receiverVatin;
	}

	@Column(name = "USD_TOTAL_CHARGES", precision = 22, scale = 0)
	public BigDecimal getUsdTotalCharges() {
		return this.usdTotalCharges;
	}

	public void setUsdTotalCharges(BigDecimal usdTotalCharges) {
		this.usdTotalCharges = usdTotalCharges;
	}

	@Column(name = "FTPSERVER_LOG_ID", precision = 22, scale = 0)
	public BigDecimal getFtpserverLogId() {
		return this.ftpserverLogId;
	}

	public void setFtpserverLogId(BigDecimal ftpserverLogId) {
		this.ftpserverLogId = ftpserverLogId;
	}

	@Column(name = "LADING_DESCRIPTION", length = 4000)
	public String getLadingDescription() {
		return this.ladingDescription;
	}

	public void setLadingDescription(String ladingDescription) {
		this.ladingDescription = ladingDescription;
	}

	@Column(name = "TOTAL_INVOICED_VOLUME", precision = 22, scale = 0)
	public BigDecimal getTotalInvoicedVolume() {
		return this.totalInvoicedVolume;
	}

	public void setTotalInvoicedVolume(BigDecimal totalInvoicedVolume) {
		this.totalInvoicedVolume = totalInvoicedVolume;
	}

	@Column(name = "TOTAL_INVOICED_UOM", precision = 22, scale = 0)
	public BigDecimal getTotalInvoicedUom() {
		return this.totalInvoicedUom;
	}

	public void setTotalInvoicedUom(BigDecimal totalInvoicedUom) {
		this.totalInvoicedUom = totalInvoicedUom;
	}

	@Column(name = "TOTAL_SHIP_UNITS", precision = 22, scale = 0)
	public BigDecimal getTotalShipUnits() {
		return this.totalShipUnits;
	}

	public void setTotalShipUnits(BigDecimal totalShipUnits) {
		this.totalShipUnits = totalShipUnits;
	}

	@Column(name = "TOTAL_SHIP_UOM", precision = 22, scale = 0)
	public BigDecimal getTotalShipUom() {
		return this.totalShipUom;
	}

	public void setTotalShipUom(BigDecimal totalShipUom) {
		this.totalShipUom = totalShipUom;
	}

	@Column(name = "EXCEPTION_REASON", precision = 22, scale = 0)
	public BigDecimal getExceptionReason() {
		return this.exceptionReason;
	}

	public void setExceptionReason(BigDecimal exceptionReason) {
		this.exceptionReason = exceptionReason;
	}

	@Column(name = "LOAD_MATCH_EXCP_DATE", length = 7)
	public Date getLoadMatchExcpDate() {
		return this.loadMatchExcpDate;
	}

	public void setLoadMatchExcpDate(Date loadMatchExcpDate) {
		this.loadMatchExcpDate = loadMatchExcpDate;
	}

	@Column(name = "SHIPPER_REGION", length = 25)
	public String getShipperRegion() {
		return this.shipperRegion;
	}

	public void setShipperRegion(String shipperRegion) {
		this.shipperRegion = shipperRegion;
	}

	@Column(name = "RECEIVER_REGION", length = 25)
	public String getReceiverRegion() {
		return this.receiverRegion;
	}

	public void setReceiverRegion(String receiverRegion) {
		this.receiverRegion = receiverRegion;
	}

	@Column(name = "LANE_ID", length = 400)
	public String getLaneId() {
		return this.laneId;
	}

	public void setLaneId(String laneId) {
		this.laneId = laneId;
	}

	@Column(name = "INCO_TERM_POINT", length = 20)
	public String getIncoTermPoint() {
		return this.incoTermPoint;
	}

	public void setIncoTermPoint(String incoTermPoint) {
		this.incoTermPoint = incoTermPoint;
	}

	@Column(name = "HOUSE_BOL_NUMBER", length = 20)
	public String getHouseBolNumber() {
		return this.houseBolNumber;
	}

	public void setHouseBolNumber(String houseBolNumber) {
		this.houseBolNumber = houseBolNumber;
	}

	@Column(name = "MASTER_BOL_NUMBER", length = 20)
	public String getMasterBolNumber() {
		return this.masterBolNumber;
	}

	public void setMasterBolNumber(String masterBolNumber) {
		this.masterBolNumber = masterBolNumber;
	}

	@Column(name = "INCO_TERM_CODE", precision = 22, scale = 0)
	public BigDecimal getIncoTermCode() {
		return this.incoTermCode;
	}

	public void setIncoTermCode(BigDecimal incoTermCode) {
		this.incoTermCode = incoTermCode;
	}

	@Column(name = "INTERLINE_DELIVERY_DATE", length = 7)
	public Date getInterlineDeliveryDate() {
		return this.interlineDeliveryDate;
	}

	public void setInterlineDeliveryDate(Date interlineDeliveryDate) {
		this.interlineDeliveryDate = interlineDeliveryDate;
	}

	@Column(name = "INTERLINE_VESSEL_NAME", length = 500)
	public String getInterlineVesselName() {
		return this.interlineVesselName;
	}

	public void setInterlineVesselName(String interlineVesselName) {
		this.interlineVesselName = interlineVesselName;
	}

	@Column(name = "INTERLINE_VOYAGE_NUMBER", length = 500)
	public String getInterlineVoyageNumber() {
		return this.interlineVoyageNumber;
	}

	public void setInterlineVoyageNumber(String interlineVoyageNumber) {
		this.interlineVoyageNumber = interlineVoyageNumber;
	}

	@Column(name = "CUSTOMS_DOCUMENT_NUMBER", length = 20)
	public String getCustomsDocumentNumber() {
		return this.customsDocumentNumber;
	}

	public void setCustomsDocumentNumber(String customsDocumentNumber) {
		this.customsDocumentNumber = customsDocumentNumber;
	}

	@Column(name = "LANE_DESCRIPTION", length = 400)
	public String getLaneDescription() {
		return this.laneDescription;
	}

	public void setLaneDescription(String laneDescription) {
		this.laneDescription = laneDescription;
	}

	@Column(name = "GLB_EQUIP_TYPE", length = 100)
	public String getGlbEquipType() {
		return this.glbEquipType;
	}

	public void setGlbEquipType(String glbEquipType) {
		this.glbEquipType = glbEquipType;
	}

	@Column(name = "DISTANCE_UOM", precision = 22, scale = 0)
	public BigDecimal getDistanceUom() {
		return this.distanceUom;
	}

	public void setDistanceUom(BigDecimal distanceUom) {
		this.distanceUom = distanceUom;
	}

	@Column(name = "INTERLINE_CARRIER", precision = 22, scale = 0)
	public BigDecimal getInterlineCarrier() {
		return this.interlineCarrier;
	}

	public void setInterlineCarrier(BigDecimal interlineCarrier) {
		this.interlineCarrier = interlineCarrier;
	}

	@Column(name = "CALCULATED_MILES", precision = 22, scale = 0)
	public BigDecimal getCalculatedMiles() {
		return this.calculatedMiles;
	}

	public void setCalculatedMiles(BigDecimal calculatedMiles) {
		this.calculatedMiles = calculatedMiles;
	}

	@Column(name = "INV_PAGE_COUNT", precision = 22, scale = 0)
	public BigDecimal getInvPageCount() {
		return this.invPageCount;
	}

	public void setInvPageCount(BigDecimal invPageCount) {
		this.invPageCount = invPageCount;
	}

	@Column(name = "INVOICE_ISA_NUMBER", length = 250)
	public String getInvoiceIsaNumber() {
		return this.invoiceIsaNumber;
	}

	public void setInvoiceIsaNumber(String invoiceIsaNumber) {
		this.invoiceIsaNumber = invoiceIsaNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpNspInvDetailsTestTbId))
			return false;
		ShpNspInvDetailsTestTbId castOther = (ShpNspInvDetailsTestTbId) other;

		return ((this.getNspInvoiceDetailsId() == castOther.getNspInvoiceDetailsId())
				|| (this.getNspInvoiceDetailsId() != null && castOther.getNspInvoiceDetailsId() != null
						&& this.getNspInvoiceDetailsId().equals(castOther.getNspInvoiceDetailsId())))
				&& ((this.getInvoiceNumber() == castOther.getInvoiceNumber())
						|| (this.getInvoiceNumber() != null && castOther.getInvoiceNumber() != null
								&& this.getInvoiceNumber().equals(castOther.getInvoiceNumber())))
				&& ((this.getScannedInvoiceId() == castOther.getScannedInvoiceId())
						|| (this.getScannedInvoiceId() != null && castOther.getScannedInvoiceId() != null
								&& this.getScannedInvoiceId().equals(castOther.getScannedInvoiceId())))
				&& ((this.getProNumber() == castOther.getProNumber()) || (this.getProNumber() != null
						&& castOther.getProNumber() != null && this.getProNumber().equals(castOther.getProNumber())))
				&& ((this.getBolNumber() == castOther.getBolNumber()) || (this.getBolNumber() != null
						&& castOther.getBolNumber() != null && this.getBolNumber().equals(castOther.getBolNumber())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCarrierId() == castOther.getCarrierId()) || (this.getCarrierId() != null
						&& castOther.getCarrierId() != null && this.getCarrierId().equals(castOther.getCarrierId())))
				&& ((this.getBillOption() == castOther.getBillOption()) || (this.getBillOption() != null
						&& castOther.getBillOption() != null && this.getBillOption().equals(castOther.getBillOption())))
				&& ((this.getInvoiceMode() == castOther.getInvoiceMode())
						|| (this.getInvoiceMode() != null && castOther.getInvoiceMode() != null
								&& this.getInvoiceMode().equals(castOther.getInvoiceMode())))
				&& ((this.getRemitToAddress() == castOther.getRemitToAddress())
						|| (this.getRemitToAddress() != null && castOther.getRemitToAddress() != null
								&& this.getRemitToAddress().equals(castOther.getRemitToAddress())))
				&& ((this.getBillDate() == castOther.getBillDate()) || (this.getBillDate() != null
						&& castOther.getBillDate() != null && this.getBillDate().equals(castOther.getBillDate())))
				&& ((this.getShipDate() == castOther.getShipDate()) || (this.getShipDate() != null
						&& castOther.getShipDate() != null && this.getShipDate().equals(castOther.getShipDate())))
				&& ((this.getDeliveryDate() == castOther.getDeliveryDate())
						|| (this.getDeliveryDate() != null && castOther.getDeliveryDate() != null
								&& this.getDeliveryDate().equals(castOther.getDeliveryDate())))
				&& ((this.getInvoiceDueDate() == castOther.getInvoiceDueDate())
						|| (this.getInvoiceDueDate() != null && castOther.getInvoiceDueDate() != null
								&& this.getInvoiceDueDate().equals(castOther.getInvoiceDueDate())))
				&& ((this.getTotalWeight() == castOther.getTotalWeight())
						|| (this.getTotalWeight() != null && castOther.getTotalWeight() != null
								&& this.getTotalWeight().equals(castOther.getTotalWeight())))
				&& ((this.getTotalCharges() == castOther.getTotalCharges())
						|| (this.getTotalCharges() != null && castOther.getTotalCharges() != null
								&& this.getTotalCharges().equals(castOther.getTotalCharges())))
				&& ((this.getTotalWeightUom() == castOther.getTotalWeightUom())
						|| (this.getTotalWeightUom() != null && castOther.getTotalWeightUom() != null
								&& this.getTotalWeightUom().equals(castOther.getTotalWeightUom())))
				&& ((this.getTarrifCode() == castOther.getTarrifCode()) || (this.getTarrifCode() != null
						&& castOther.getTarrifCode() != null && this.getTarrifCode().equals(castOther.getTarrifCode())))
				&& ((this.getGlAccountsCode() == castOther.getGlAccountsCode())
						|| (this.getGlAccountsCode() != null && castOther.getGlAccountsCode() != null
								&& this.getGlAccountsCode().equals(castOther.getGlAccountsCode())))
				&& ((this.getRunNo() == castOther.getRunNo()) || (this.getRunNo() != null
						&& castOther.getRunNo() != null && this.getRunNo().equals(castOther.getRunNo())))
				&& ((this.getCheckNo() == castOther.getCheckNo()) || (this.getCheckNo() != null
						&& castOther.getCheckNo() != null && this.getCheckNo().equals(castOther.getCheckNo())))
				&& ((this.getCheckDate() == castOther.getCheckDate()) || (this.getCheckDate() != null
						&& castOther.getCheckDate() != null && this.getCheckDate().equals(castOther.getCheckDate())))
				&& ((this.getCheckAmount() == castOther.getCheckAmount())
						|| (this.getCheckAmount() != null && castOther.getCheckAmount() != null
								&& this.getCheckAmount().equals(castOther.getCheckAmount())))
				&& ((this.getShipperName() == castOther.getShipperName())
						|| (this.getShipperName() != null && castOther.getShipperName() != null
								&& this.getShipperName().equals(castOther.getShipperName())))
				&& ((this.getShipperAddress1() == castOther.getShipperAddress1())
						|| (this.getShipperAddress1() != null && castOther.getShipperAddress1() != null
								&& this.getShipperAddress1().equals(castOther.getShipperAddress1())))
				&& ((this.getShipperAddress2() == castOther.getShipperAddress2())
						|| (this.getShipperAddress2() != null && castOther.getShipperAddress2() != null
								&& this.getShipperAddress2().equals(castOther.getShipperAddress2())))
				&& ((this.getShipperAddress3() == castOther.getShipperAddress3())
						|| (this.getShipperAddress3() != null && castOther.getShipperAddress3() != null
								&& this.getShipperAddress3().equals(castOther.getShipperAddress3())))
				&& ((this.getShipperState() == castOther.getShipperState())
						|| (this.getShipperState() != null && castOther.getShipperState() != null
								&& this.getShipperState().equals(castOther.getShipperState())))
				&& ((this.getShipperCity() == castOther.getShipperCity())
						|| (this.getShipperCity() != null && castOther.getShipperCity() != null
								&& this.getShipperCity().equals(castOther.getShipperCity())))
				&& ((this.getShipperZipcode() == castOther.getShipperZipcode())
						|| (this.getShipperZipcode() != null && castOther.getShipperZipcode() != null
								&& this.getShipperZipcode().equals(castOther.getShipperZipcode())))
				&& ((this.getShipperCountry() == castOther.getShipperCountry())
						|| (this.getShipperCountry() != null && castOther.getShipperCountry() != null
								&& this.getShipperCountry().equals(castOther.getShipperCountry())))
				&& ((this.getReceiverName() == castOther.getReceiverName())
						|| (this.getReceiverName() != null && castOther.getReceiverName() != null
								&& this.getReceiverName().equals(castOther.getReceiverName())))
				&& ((this.getReceiverAddress1() == castOther.getReceiverAddress1())
						|| (this.getReceiverAddress1() != null && castOther.getReceiverAddress1() != null
								&& this.getReceiverAddress1().equals(castOther.getReceiverAddress1())))
				&& ((this.getReceiverAddress2() == castOther.getReceiverAddress2())
						|| (this.getReceiverAddress2() != null && castOther.getReceiverAddress2() != null
								&& this.getReceiverAddress2().equals(castOther.getReceiverAddress2())))
				&& ((this.getReceiverAddress3() == castOther.getReceiverAddress3())
						|| (this.getReceiverAddress3() != null && castOther.getReceiverAddress3() != null
								&& this.getReceiverAddress3().equals(castOther.getReceiverAddress3())))
				&& ((this.getReceiverState() == castOther.getReceiverState())
						|| (this.getReceiverState() != null && castOther.getReceiverState() != null
								&& this.getReceiverState().equals(castOther.getReceiverState())))
				&& ((this.getReceiverCity() == castOther.getReceiverCity())
						|| (this.getReceiverCity() != null && castOther.getReceiverCity() != null
								&& this.getReceiverCity().equals(castOther.getReceiverCity())))
				&& ((this.getReceiverZipcode() == castOther.getReceiverZipcode())
						|| (this.getReceiverZipcode() != null && castOther.getReceiverZipcode() != null
								&& this.getReceiverZipcode().equals(castOther.getReceiverZipcode())))
				&& ((this.getReceiverCountry() == castOther.getReceiverCountry())
						|| (this.getReceiverCountry() != null && castOther.getReceiverCountry() != null
								&& this.getReceiverCountry().equals(castOther.getReceiverCountry())))
				&& ((this.getReference1() == castOther.getReference1()) || (this.getReference1() != null
						&& castOther.getReference1() != null && this.getReference1().equals(castOther.getReference1())))
				&& ((this.getReference2() == castOther.getReference2()) || (this.getReference2() != null
						&& castOther.getReference2() != null && this.getReference2().equals(castOther.getReference2())))
				&& ((this.getDataEntryComments() == castOther.getDataEntryComments())
						|| (this.getDataEntryComments() != null && castOther.getDataEntryComments() != null
								&& this.getDataEntryComments().equals(castOther.getDataEntryComments())))
				&& ((this.getAuditorComments() == castOther.getAuditorComments())
						|| (this.getAuditorComments() != null && castOther.getAuditorComments() != null
								&& this.getAuditorComments().equals(castOther.getAuditorComments())))
				&& ((this.getCustomerComments() == castOther.getCustomerComments())
						|| (this.getCustomerComments() != null && castOther.getCustomerComments() != null
								&& this.getCustomerComments().equals(castOther.getCustomerComments())))
				&& ((this.getSubtotalAmount() == castOther.getSubtotalAmount())
						|| (this.getSubtotalAmount() != null && castOther.getSubtotalAmount() != null
								&& this.getSubtotalAmount().equals(castOther.getSubtotalAmount())))
				&& ((this.getInvoiceTax1Amount() == castOther.getInvoiceTax1Amount())
						|| (this.getInvoiceTax1Amount() != null && castOther.getInvoiceTax1Amount() != null
								&& this.getInvoiceTax1Amount().equals(castOther.getInvoiceTax1Amount())))
				&& ((this.getInvoiceTax2Amount() == castOther.getInvoiceTax2Amount())
						|| (this.getInvoiceTax2Amount() != null && castOther.getInvoiceTax2Amount() != null
								&& this.getInvoiceTax2Amount().equals(castOther.getInvoiceTax2Amount())))
				&& ((this.getTotalDueAmount() == castOther.getTotalDueAmount())
						|| (this.getTotalDueAmount() != null && castOther.getTotalDueAmount() != null
								&& this.getTotalDueAmount().equals(castOther.getTotalDueAmount())))
				&& ((this.getPaidAmount() == castOther.getPaidAmount()) || (this.getPaidAmount() != null
						&& castOther.getPaidAmount() != null && this.getPaidAmount().equals(castOther.getPaidAmount())))
				&& ((this.getBalanceAmount() == castOther.getBalanceAmount())
						|| (this.getBalanceAmount() != null && castOther.getBalanceAmount() != null
								&& this.getBalanceAmount().equals(castOther.getBalanceAmount())))
				&& ((this.getIsBillOptionCorrect() == castOther.getIsBillOptionCorrect())
						|| (this.getIsBillOptionCorrect() != null && castOther.getIsBillOptionCorrect() != null
								&& this.getIsBillOptionCorrect().equals(castOther.getIsBillOptionCorrect())))
				&& ((this.getIsDuplicateBillingChecked() == castOther.getIsDuplicateBillingChecked())
						|| (this.getIsDuplicateBillingChecked() != null
								&& castOther.getIsDuplicateBillingChecked() != null
								&& this.getIsDuplicateBillingChecked()
										.equals(castOther.getIsDuplicateBillingChecked())))
				&& ((this.getIsFreightChargeChecked() == castOther.getIsFreightChargeChecked())
						|| (this.getIsFreightChargeChecked() != null && castOther.getIsFreightChargeChecked() != null
								&& this.getIsFreightChargeChecked().equals(castOther.getIsFreightChargeChecked())))
				&& ((this.getIsFuelSurchargesChecked() == castOther.getIsFuelSurchargesChecked())
						|| (this.getIsFuelSurchargesChecked() != null && castOther.getIsFuelSurchargesChecked() != null
								&& this.getIsFuelSurchargesChecked().equals(castOther.getIsFuelSurchargesChecked())))
				&& ((this.getIsAccessorialsChecked() == castOther.getIsAccessorialsChecked())
						|| (this.getIsAccessorialsChecked() != null && castOther.getIsAccessorialsChecked() != null
								&& this.getIsAccessorialsChecked().equals(castOther.getIsAccessorialsChecked())))
				&& ((this.getIsDocumentationChecked() == castOther.getIsDocumentationChecked())
						|| (this.getIsDocumentationChecked() != null && castOther.getIsDocumentationChecked() != null
								&& this.getIsDocumentationChecked().equals(castOther.getIsDocumentationChecked())))
				&& ((this.getInvoiceStatus() == castOther.getInvoiceStatus())
						|| (this.getInvoiceStatus() != null && castOther.getInvoiceStatus() != null
								&& this.getInvoiceStatus().equals(castOther.getInvoiceStatus())))
				&& ((this.getCreateUser() == castOther.getCreateUser()) || (this.getCreateUser() != null
						&& castOther.getCreateUser() != null && this.getCreateUser().equals(castOther.getCreateUser())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser())
						|| (this.getLastUpdateUser() != null && castOther.getLastUpdateUser() != null
								&& this.getLastUpdateUser().equals(castOther.getLastUpdateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate())
						|| (this.getLastUpdateDate() != null && castOther.getLastUpdateDate() != null
								&& this.getLastUpdateDate().equals(castOther.getLastUpdateDate())))
				&& ((this.getPoNumber() == castOther.getPoNumber()) || (this.getPoNumber() != null
						&& castOther.getPoNumber() != null && this.getPoNumber().equals(castOther.getPoNumber())))
				&& ((this.getRatingContract() == castOther.getRatingContract())
						|| (this.getRatingContract() != null && castOther.getRatingContract() != null
								&& this.getRatingContract().equals(castOther.getRatingContract())))
				&& ((this.getInvoiceType() == castOther.getInvoiceType())
						|| (this.getInvoiceType() != null && castOther.getInvoiceType() != null
								&& this.getInvoiceType().equals(castOther.getInvoiceType())))
				&& ((this.getOrigInvoiceId() == castOther.getOrigInvoiceId())
						|| (this.getOrigInvoiceId() != null && castOther.getOrigInvoiceId() != null
								&& this.getOrigInvoiceId().equals(castOther.getOrigInvoiceId())))
				&& ((this.getClosedDate() == castOther.getClosedDate()) || (this.getClosedDate() != null
						&& castOther.getClosedDate() != null && this.getClosedDate().equals(castOther.getClosedDate())))
				&& ((this.getClosedBy() == castOther.getClosedBy()) || (this.getClosedBy() != null
						&& castOther.getClosedBy() != null && this.getClosedBy().equals(castOther.getClosedBy())))
				&& ((this.getCustAction() == castOther.getCustAction()) || (this.getCustAction() != null
						&& castOther.getCustAction() != null && this.getCustAction().equals(castOther.getCustAction())))
				&& ((this.getCustActionBy() == castOther.getCustActionBy())
						|| (this.getCustActionBy() != null && castOther.getCustActionBy() != null
								&& this.getCustActionBy().equals(castOther.getCustActionBy())))
				&& ((this.getCustActionDate() == castOther.getCustActionDate())
						|| (this.getCustActionDate() != null && castOther.getCustActionDate() != null
								&& this.getCustActionDate().equals(castOther.getCustActionDate())))
				&& ((this.getReceivedDate() == castOther.getReceivedDate())
						|| (this.getReceivedDate() != null && castOther.getReceivedDate() != null
								&& this.getReceivedDate().equals(castOther.getReceivedDate())))
				&& ((this.getChildCarrierName() == castOther.getChildCarrierName())
						|| (this.getChildCarrierName() != null && castOther.getChildCarrierName() != null
								&& this.getChildCarrierName().equals(castOther.getChildCarrierName())))
				&& ((this.getPortOfOrigin() == castOther.getPortOfOrigin())
						|| (this.getPortOfOrigin() != null && castOther.getPortOfOrigin() != null
								&& this.getPortOfOrigin().equals(castOther.getPortOfOrigin())))
				&& ((this.getPortOfDestination() == castOther.getPortOfDestination())
						|| (this.getPortOfDestination() != null && castOther.getPortOfDestination() != null
								&& this.getPortOfDestination().equals(castOther.getPortOfDestination())))
				&& ((this.getDwExtractFlag() == castOther.getDwExtractFlag())
						|| (this.getDwExtractFlag() != null && castOther.getDwExtractFlag() != null
								&& this.getDwExtractFlag().equals(castOther.getDwExtractFlag())))
				&& ((this.getServiceCodeId() == castOther.getServiceCodeId())
						|| (this.getServiceCodeId() != null && castOther.getServiceCodeId() != null
								&& this.getServiceCodeId().equals(castOther.getServiceCodeId())))
				&& ((this.getLinkedDocuments() == castOther.getLinkedDocuments())
						|| (this.getLinkedDocuments() != null && castOther.getLinkedDocuments() != null
								&& this.getLinkedDocuments().equals(castOther.getLinkedDocuments())))
				&& ((this.getFileId() == castOther.getFileId()) || (this.getFileId() != null
						&& castOther.getFileId() != null && this.getFileId().equals(castOther.getFileId())))
				&& ((this.getReference3() == castOther.getReference3()) || (this.getReference3() != null
						&& castOther.getReference3() != null && this.getReference3().equals(castOther.getReference3())))
				&& ((this.getReference4() == castOther.getReference4()) || (this.getReference4() != null
						&& castOther.getReference4() != null && this.getReference4().equals(castOther.getReference4())))
				&& ((this.getBilledMiles() == castOther.getBilledMiles())
						|| (this.getBilledMiles() != null && castOther.getBilledMiles() != null
								&& this.getBilledMiles().equals(castOther.getBilledMiles())))
				&& ((this.getRatedMiles() == castOther.getRatedMiles()) || (this.getRatedMiles() != null
						&& castOther.getRatedMiles() != null && this.getRatedMiles().equals(castOther.getRatedMiles())))
				&& ((this.getCurrencyCode() == castOther.getCurrencyCode())
						|| (this.getCurrencyCode() != null && castOther.getCurrencyCode() != null
								&& this.getCurrencyCode().equals(castOther.getCurrencyCode())))
				&& ((this.getEquipmentType() == castOther.getEquipmentType())
						|| (this.getEquipmentType() != null && castOther.getEquipmentType() != null
								&& this.getEquipmentType().equals(castOther.getEquipmentType())))
				&& ((this.getBilltoName() == castOther.getBilltoName()) || (this.getBilltoName() != null
						&& castOther.getBilltoName() != null && this.getBilltoName().equals(castOther.getBilltoName())))
				&& ((this.getBilltoAddress1() == castOther.getBilltoAddress1())
						|| (this.getBilltoAddress1() != null && castOther.getBilltoAddress1() != null
								&& this.getBilltoAddress1().equals(castOther.getBilltoAddress1())))
				&& ((this.getBilltoAddress2() == castOther.getBilltoAddress2())
						|| (this.getBilltoAddress2() != null && castOther.getBilltoAddress2() != null
								&& this.getBilltoAddress2().equals(castOther.getBilltoAddress2())))
				&& ((this.getBilltoAddress3() == castOther.getBilltoAddress3())
						|| (this.getBilltoAddress3() != null && castOther.getBilltoAddress3() != null
								&& this.getBilltoAddress3().equals(castOther.getBilltoAddress3())))
				&& ((this.getBilltoState() == castOther.getBilltoState())
						|| (this.getBilltoState() != null && castOther.getBilltoState() != null
								&& this.getBilltoState().equals(castOther.getBilltoState())))
				&& ((this.getBilltoCity() == castOther.getBilltoCity()) || (this.getBilltoCity() != null
						&& castOther.getBilltoCity() != null && this.getBilltoCity().equals(castOther.getBilltoCity())))
				&& ((this.getBilltoZipcode() == castOther.getBilltoZipcode())
						|| (this.getBilltoZipcode() != null && castOther.getBilltoZipcode() != null
								&& this.getBilltoZipcode().equals(castOther.getBilltoZipcode())))
				&& ((this.getBilltoCountry() == castOther.getBilltoCountry())
						|| (this.getBilltoCountry() != null && castOther.getBilltoCountry() != null
								&& this.getBilltoCountry().equals(castOther.getBilltoCountry())))
				&& ((this.getInvoiceHsTaxAmount() == castOther.getInvoiceHsTaxAmount())
						|| (this.getInvoiceHsTaxAmount() != null && castOther.getInvoiceHsTaxAmount() != null
								&& this.getInvoiceHsTaxAmount().equals(castOther.getInvoiceHsTaxAmount())))
				&& ((this.getAccountNumber() == castOther.getAccountNumber())
						|| (this.getAccountNumber() != null && castOther.getAccountNumber() != null
								&& this.getAccountNumber().equals(castOther.getAccountNumber())))
				&& ((this.getAddressType() == castOther.getAddressType())
						|| (this.getAddressType() != null && castOther.getAddressType() != null
								&& this.getAddressType().equals(castOther.getAddressType())))
				&& ((this.getRatingComments() == castOther.getRatingComments())
						|| (this.getRatingComments() != null && castOther.getRatingComments() != null
								&& this.getRatingComments().equals(castOther.getRatingComments())))
				&& ((this.getActualMiles() == castOther.getActualMiles())
						|| (this.getActualMiles() != null && castOther.getActualMiles() != null
								&& this.getActualMiles().equals(castOther.getActualMiles())))
				&& ((this.getExportCode() == castOther.getExportCode()) || (this.getExportCode() != null
						&& castOther.getExportCode() != null && this.getExportCode().equals(castOther.getExportCode())))
				&& ((this.getImportCode() == castOther.getImportCode()) || (this.getImportCode() != null
						&& castOther.getImportCode() != null && this.getImportCode().equals(castOther.getImportCode())))
				&& ((this.getShipperVatin() == castOther.getShipperVatin())
						|| (this.getShipperVatin() != null && castOther.getShipperVatin() != null
								&& this.getShipperVatin().equals(castOther.getShipperVatin())))
				&& ((this.getReceiverVatin() == castOther.getReceiverVatin())
						|| (this.getReceiverVatin() != null && castOther.getReceiverVatin() != null
								&& this.getReceiverVatin().equals(castOther.getReceiverVatin())))
				&& ((this.getUsdTotalCharges() == castOther.getUsdTotalCharges())
						|| (this.getUsdTotalCharges() != null && castOther.getUsdTotalCharges() != null
								&& this.getUsdTotalCharges().equals(castOther.getUsdTotalCharges())))
				&& ((this.getFtpserverLogId() == castOther.getFtpserverLogId())
						|| (this.getFtpserverLogId() != null && castOther.getFtpserverLogId() != null
								&& this.getFtpserverLogId().equals(castOther.getFtpserverLogId())))
				&& ((this.getLadingDescription() == castOther.getLadingDescription())
						|| (this.getLadingDescription() != null && castOther.getLadingDescription() != null
								&& this.getLadingDescription().equals(castOther.getLadingDescription())))
				&& ((this.getTotalInvoicedVolume() == castOther.getTotalInvoicedVolume())
						|| (this.getTotalInvoicedVolume() != null && castOther.getTotalInvoicedVolume() != null
								&& this.getTotalInvoicedVolume().equals(castOther.getTotalInvoicedVolume())))
				&& ((this.getTotalInvoicedUom() == castOther.getTotalInvoicedUom())
						|| (this.getTotalInvoicedUom() != null && castOther.getTotalInvoicedUom() != null
								&& this.getTotalInvoicedUom().equals(castOther.getTotalInvoicedUom())))
				&& ((this.getTotalShipUnits() == castOther.getTotalShipUnits())
						|| (this.getTotalShipUnits() != null && castOther.getTotalShipUnits() != null
								&& this.getTotalShipUnits().equals(castOther.getTotalShipUnits())))
				&& ((this.getTotalShipUom() == castOther.getTotalShipUom())
						|| (this.getTotalShipUom() != null && castOther.getTotalShipUom() != null
								&& this.getTotalShipUom().equals(castOther.getTotalShipUom())))
				&& ((this.getExceptionReason() == castOther.getExceptionReason())
						|| (this.getExceptionReason() != null && castOther.getExceptionReason() != null
								&& this.getExceptionReason().equals(castOther.getExceptionReason())))
				&& ((this.getLoadMatchExcpDate() == castOther.getLoadMatchExcpDate())
						|| (this.getLoadMatchExcpDate() != null && castOther.getLoadMatchExcpDate() != null
								&& this.getLoadMatchExcpDate().equals(castOther.getLoadMatchExcpDate())))
				&& ((this.getShipperRegion() == castOther.getShipperRegion())
						|| (this.getShipperRegion() != null && castOther.getShipperRegion() != null
								&& this.getShipperRegion().equals(castOther.getShipperRegion())))
				&& ((this.getReceiverRegion() == castOther.getReceiverRegion())
						|| (this.getReceiverRegion() != null && castOther.getReceiverRegion() != null
								&& this.getReceiverRegion().equals(castOther.getReceiverRegion())))
				&& ((this.getLaneId() == castOther.getLaneId()) || (this.getLaneId() != null
						&& castOther.getLaneId() != null && this.getLaneId().equals(castOther.getLaneId())))
				&& ((this.getIncoTermPoint() == castOther.getIncoTermPoint())
						|| (this.getIncoTermPoint() != null && castOther.getIncoTermPoint() != null
								&& this.getIncoTermPoint().equals(castOther.getIncoTermPoint())))
				&& ((this.getHouseBolNumber() == castOther.getHouseBolNumber())
						|| (this.getHouseBolNumber() != null && castOther.getHouseBolNumber() != null
								&& this.getHouseBolNumber().equals(castOther.getHouseBolNumber())))
				&& ((this.getMasterBolNumber() == castOther.getMasterBolNumber())
						|| (this.getMasterBolNumber() != null && castOther.getMasterBolNumber() != null
								&& this.getMasterBolNumber().equals(castOther.getMasterBolNumber())))
				&& ((this.getIncoTermCode() == castOther.getIncoTermCode())
						|| (this.getIncoTermCode() != null && castOther.getIncoTermCode() != null
								&& this.getIncoTermCode().equals(castOther.getIncoTermCode())))
				&& ((this.getInterlineDeliveryDate() == castOther.getInterlineDeliveryDate())
						|| (this.getInterlineDeliveryDate() != null && castOther.getInterlineDeliveryDate() != null
								&& this.getInterlineDeliveryDate().equals(castOther.getInterlineDeliveryDate())))
				&& ((this.getInterlineVesselName() == castOther.getInterlineVesselName())
						|| (this.getInterlineVesselName() != null && castOther.getInterlineVesselName() != null
								&& this.getInterlineVesselName().equals(castOther.getInterlineVesselName())))
				&& ((this.getInterlineVoyageNumber() == castOther.getInterlineVoyageNumber())
						|| (this.getInterlineVoyageNumber() != null && castOther.getInterlineVoyageNumber() != null
								&& this.getInterlineVoyageNumber().equals(castOther.getInterlineVoyageNumber())))
				&& ((this.getCustomsDocumentNumber() == castOther.getCustomsDocumentNumber())
						|| (this.getCustomsDocumentNumber() != null && castOther.getCustomsDocumentNumber() != null
								&& this.getCustomsDocumentNumber().equals(castOther.getCustomsDocumentNumber())))
				&& ((this.getLaneDescription() == castOther.getLaneDescription())
						|| (this.getLaneDescription() != null && castOther.getLaneDescription() != null
								&& this.getLaneDescription().equals(castOther.getLaneDescription())))
				&& ((this.getGlbEquipType() == castOther.getGlbEquipType())
						|| (this.getGlbEquipType() != null && castOther.getGlbEquipType() != null
								&& this.getGlbEquipType().equals(castOther.getGlbEquipType())))
				&& ((this.getDistanceUom() == castOther.getDistanceUom())
						|| (this.getDistanceUom() != null && castOther.getDistanceUom() != null
								&& this.getDistanceUom().equals(castOther.getDistanceUom())))
				&& ((this.getInterlineCarrier() == castOther.getInterlineCarrier())
						|| (this.getInterlineCarrier() != null && castOther.getInterlineCarrier() != null
								&& this.getInterlineCarrier().equals(castOther.getInterlineCarrier())))
				&& ((this.getCalculatedMiles() == castOther.getCalculatedMiles())
						|| (this.getCalculatedMiles() != null && castOther.getCalculatedMiles() != null
								&& this.getCalculatedMiles().equals(castOther.getCalculatedMiles())))
				&& ((this.getInvPageCount() == castOther.getInvPageCount())
						|| (this.getInvPageCount() != null && castOther.getInvPageCount() != null
								&& this.getInvPageCount().equals(castOther.getInvPageCount())))
				&& ((this.getInvoiceIsaNumber() == castOther.getInvoiceIsaNumber())
						|| (this.getInvoiceIsaNumber() != null && castOther.getInvoiceIsaNumber() != null
								&& this.getInvoiceIsaNumber().equals(castOther.getInvoiceIsaNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNspInvoiceDetailsId() == null ? 0 : this.getNspInvoiceDetailsId().hashCode());
		result = 37 * result + (getInvoiceNumber() == null ? 0 : this.getInvoiceNumber().hashCode());
		result = 37 * result + (getScannedInvoiceId() == null ? 0 : this.getScannedInvoiceId().hashCode());
		result = 37 * result + (getProNumber() == null ? 0 : this.getProNumber().hashCode());
		result = 37 * result + (getBolNumber() == null ? 0 : this.getBolNumber().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCarrierId() == null ? 0 : this.getCarrierId().hashCode());
		result = 37 * result + (getBillOption() == null ? 0 : this.getBillOption().hashCode());
		result = 37 * result + (getInvoiceMode() == null ? 0 : this.getInvoiceMode().hashCode());
		result = 37 * result + (getRemitToAddress() == null ? 0 : this.getRemitToAddress().hashCode());
		result = 37 * result + (getBillDate() == null ? 0 : this.getBillDate().hashCode());
		result = 37 * result + (getShipDate() == null ? 0 : this.getShipDate().hashCode());
		result = 37 * result + (getDeliveryDate() == null ? 0 : this.getDeliveryDate().hashCode());
		result = 37 * result + (getInvoiceDueDate() == null ? 0 : this.getInvoiceDueDate().hashCode());
		result = 37 * result + (getTotalWeight() == null ? 0 : this.getTotalWeight().hashCode());
		result = 37 * result + (getTotalCharges() == null ? 0 : this.getTotalCharges().hashCode());
		result = 37 * result + (getTotalWeightUom() == null ? 0 : this.getTotalWeightUom().hashCode());
		result = 37 * result + (getTarrifCode() == null ? 0 : this.getTarrifCode().hashCode());
		result = 37 * result + (getGlAccountsCode() == null ? 0 : this.getGlAccountsCode().hashCode());
		result = 37 * result + (getRunNo() == null ? 0 : this.getRunNo().hashCode());
		result = 37 * result + (getCheckNo() == null ? 0 : this.getCheckNo().hashCode());
		result = 37 * result + (getCheckDate() == null ? 0 : this.getCheckDate().hashCode());
		result = 37 * result + (getCheckAmount() == null ? 0 : this.getCheckAmount().hashCode());
		result = 37 * result + (getShipperName() == null ? 0 : this.getShipperName().hashCode());
		result = 37 * result + (getShipperAddress1() == null ? 0 : this.getShipperAddress1().hashCode());
		result = 37 * result + (getShipperAddress2() == null ? 0 : this.getShipperAddress2().hashCode());
		result = 37 * result + (getShipperAddress3() == null ? 0 : this.getShipperAddress3().hashCode());
		result = 37 * result + (getShipperState() == null ? 0 : this.getShipperState().hashCode());
		result = 37 * result + (getShipperCity() == null ? 0 : this.getShipperCity().hashCode());
		result = 37 * result + (getShipperZipcode() == null ? 0 : this.getShipperZipcode().hashCode());
		result = 37 * result + (getShipperCountry() == null ? 0 : this.getShipperCountry().hashCode());
		result = 37 * result + (getReceiverName() == null ? 0 : this.getReceiverName().hashCode());
		result = 37 * result + (getReceiverAddress1() == null ? 0 : this.getReceiverAddress1().hashCode());
		result = 37 * result + (getReceiverAddress2() == null ? 0 : this.getReceiverAddress2().hashCode());
		result = 37 * result + (getReceiverAddress3() == null ? 0 : this.getReceiverAddress3().hashCode());
		result = 37 * result + (getReceiverState() == null ? 0 : this.getReceiverState().hashCode());
		result = 37 * result + (getReceiverCity() == null ? 0 : this.getReceiverCity().hashCode());
		result = 37 * result + (getReceiverZipcode() == null ? 0 : this.getReceiverZipcode().hashCode());
		result = 37 * result + (getReceiverCountry() == null ? 0 : this.getReceiverCountry().hashCode());
		result = 37 * result + (getReference1() == null ? 0 : this.getReference1().hashCode());
		result = 37 * result + (getReference2() == null ? 0 : this.getReference2().hashCode());
		result = 37 * result + (getDataEntryComments() == null ? 0 : this.getDataEntryComments().hashCode());
		result = 37 * result + (getAuditorComments() == null ? 0 : this.getAuditorComments().hashCode());
		result = 37 * result + (getCustomerComments() == null ? 0 : this.getCustomerComments().hashCode());
		result = 37 * result + (getSubtotalAmount() == null ? 0 : this.getSubtotalAmount().hashCode());
		result = 37 * result + (getInvoiceTax1Amount() == null ? 0 : this.getInvoiceTax1Amount().hashCode());
		result = 37 * result + (getInvoiceTax2Amount() == null ? 0 : this.getInvoiceTax2Amount().hashCode());
		result = 37 * result + (getTotalDueAmount() == null ? 0 : this.getTotalDueAmount().hashCode());
		result = 37 * result + (getPaidAmount() == null ? 0 : this.getPaidAmount().hashCode());
		result = 37 * result + (getBalanceAmount() == null ? 0 : this.getBalanceAmount().hashCode());
		result = 37 * result + (getIsBillOptionCorrect() == null ? 0 : this.getIsBillOptionCorrect().hashCode());
		result = 37 * result
				+ (getIsDuplicateBillingChecked() == null ? 0 : this.getIsDuplicateBillingChecked().hashCode());
		result = 37 * result + (getIsFreightChargeChecked() == null ? 0 : this.getIsFreightChargeChecked().hashCode());
		result = 37 * result
				+ (getIsFuelSurchargesChecked() == null ? 0 : this.getIsFuelSurchargesChecked().hashCode());
		result = 37 * result + (getIsAccessorialsChecked() == null ? 0 : this.getIsAccessorialsChecked().hashCode());
		result = 37 * result + (getIsDocumentationChecked() == null ? 0 : this.getIsDocumentationChecked().hashCode());
		result = 37 * result + (getInvoiceStatus() == null ? 0 : this.getInvoiceStatus().hashCode());
		result = 37 * result + (getCreateUser() == null ? 0 : this.getCreateUser().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser().hashCode());
		result = 37 * result + (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate().hashCode());
		result = 37 * result + (getPoNumber() == null ? 0 : this.getPoNumber().hashCode());
		result = 37 * result + (getRatingContract() == null ? 0 : this.getRatingContract().hashCode());
		result = 37 * result + (getInvoiceType() == null ? 0 : this.getInvoiceType().hashCode());
		result = 37 * result + (getOrigInvoiceId() == null ? 0 : this.getOrigInvoiceId().hashCode());
		result = 37 * result + (getClosedDate() == null ? 0 : this.getClosedDate().hashCode());
		result = 37 * result + (getClosedBy() == null ? 0 : this.getClosedBy().hashCode());
		result = 37 * result + (getCustAction() == null ? 0 : this.getCustAction().hashCode());
		result = 37 * result + (getCustActionBy() == null ? 0 : this.getCustActionBy().hashCode());
		result = 37 * result + (getCustActionDate() == null ? 0 : this.getCustActionDate().hashCode());
		result = 37 * result + (getReceivedDate() == null ? 0 : this.getReceivedDate().hashCode());
		result = 37 * result + (getChildCarrierName() == null ? 0 : this.getChildCarrierName().hashCode());
		result = 37 * result + (getPortOfOrigin() == null ? 0 : this.getPortOfOrigin().hashCode());
		result = 37 * result + (getPortOfDestination() == null ? 0 : this.getPortOfDestination().hashCode());
		result = 37 * result + (getDwExtractFlag() == null ? 0 : this.getDwExtractFlag().hashCode());
		result = 37 * result + (getServiceCodeId() == null ? 0 : this.getServiceCodeId().hashCode());
		result = 37 * result + (getLinkedDocuments() == null ? 0 : this.getLinkedDocuments().hashCode());
		result = 37 * result + (getFileId() == null ? 0 : this.getFileId().hashCode());
		result = 37 * result + (getReference3() == null ? 0 : this.getReference3().hashCode());
		result = 37 * result + (getReference4() == null ? 0 : this.getReference4().hashCode());
		result = 37 * result + (getBilledMiles() == null ? 0 : this.getBilledMiles().hashCode());
		result = 37 * result + (getRatedMiles() == null ? 0 : this.getRatedMiles().hashCode());
		result = 37 * result + (getCurrencyCode() == null ? 0 : this.getCurrencyCode().hashCode());
		result = 37 * result + (getEquipmentType() == null ? 0 : this.getEquipmentType().hashCode());
		result = 37 * result + (getBilltoName() == null ? 0 : this.getBilltoName().hashCode());
		result = 37 * result + (getBilltoAddress1() == null ? 0 : this.getBilltoAddress1().hashCode());
		result = 37 * result + (getBilltoAddress2() == null ? 0 : this.getBilltoAddress2().hashCode());
		result = 37 * result + (getBilltoAddress3() == null ? 0 : this.getBilltoAddress3().hashCode());
		result = 37 * result + (getBilltoState() == null ? 0 : this.getBilltoState().hashCode());
		result = 37 * result + (getBilltoCity() == null ? 0 : this.getBilltoCity().hashCode());
		result = 37 * result + (getBilltoZipcode() == null ? 0 : this.getBilltoZipcode().hashCode());
		result = 37 * result + (getBilltoCountry() == null ? 0 : this.getBilltoCountry().hashCode());
		result = 37 * result + (getInvoiceHsTaxAmount() == null ? 0 : this.getInvoiceHsTaxAmount().hashCode());
		result = 37 * result + (getAccountNumber() == null ? 0 : this.getAccountNumber().hashCode());
		result = 37 * result + (getAddressType() == null ? 0 : this.getAddressType().hashCode());
		result = 37 * result + (getRatingComments() == null ? 0 : this.getRatingComments().hashCode());
		result = 37 * result + (getActualMiles() == null ? 0 : this.getActualMiles().hashCode());
		result = 37 * result + (getExportCode() == null ? 0 : this.getExportCode().hashCode());
		result = 37 * result + (getImportCode() == null ? 0 : this.getImportCode().hashCode());
		result = 37 * result + (getShipperVatin() == null ? 0 : this.getShipperVatin().hashCode());
		result = 37 * result + (getReceiverVatin() == null ? 0 : this.getReceiverVatin().hashCode());
		result = 37 * result + (getUsdTotalCharges() == null ? 0 : this.getUsdTotalCharges().hashCode());
		result = 37 * result + (getFtpserverLogId() == null ? 0 : this.getFtpserverLogId().hashCode());
		result = 37 * result + (getLadingDescription() == null ? 0 : this.getLadingDescription().hashCode());
		result = 37 * result + (getTotalInvoicedVolume() == null ? 0 : this.getTotalInvoicedVolume().hashCode());
		result = 37 * result + (getTotalInvoicedUom() == null ? 0 : this.getTotalInvoicedUom().hashCode());
		result = 37 * result + (getTotalShipUnits() == null ? 0 : this.getTotalShipUnits().hashCode());
		result = 37 * result + (getTotalShipUom() == null ? 0 : this.getTotalShipUom().hashCode());
		result = 37 * result + (getExceptionReason() == null ? 0 : this.getExceptionReason().hashCode());
		result = 37 * result + (getLoadMatchExcpDate() == null ? 0 : this.getLoadMatchExcpDate().hashCode());
		result = 37 * result + (getShipperRegion() == null ? 0 : this.getShipperRegion().hashCode());
		result = 37 * result + (getReceiverRegion() == null ? 0 : this.getReceiverRegion().hashCode());
		result = 37 * result + (getLaneId() == null ? 0 : this.getLaneId().hashCode());
		result = 37 * result + (getIncoTermPoint() == null ? 0 : this.getIncoTermPoint().hashCode());
		result = 37 * result + (getHouseBolNumber() == null ? 0 : this.getHouseBolNumber().hashCode());
		result = 37 * result + (getMasterBolNumber() == null ? 0 : this.getMasterBolNumber().hashCode());
		result = 37 * result + (getIncoTermCode() == null ? 0 : this.getIncoTermCode().hashCode());
		result = 37 * result + (getInterlineDeliveryDate() == null ? 0 : this.getInterlineDeliveryDate().hashCode());
		result = 37 * result + (getInterlineVesselName() == null ? 0 : this.getInterlineVesselName().hashCode());
		result = 37 * result + (getInterlineVoyageNumber() == null ? 0 : this.getInterlineVoyageNumber().hashCode());
		result = 37 * result + (getCustomsDocumentNumber() == null ? 0 : this.getCustomsDocumentNumber().hashCode());
		result = 37 * result + (getLaneDescription() == null ? 0 : this.getLaneDescription().hashCode());
		result = 37 * result + (getGlbEquipType() == null ? 0 : this.getGlbEquipType().hashCode());
		result = 37 * result + (getDistanceUom() == null ? 0 : this.getDistanceUom().hashCode());
		result = 37 * result + (getInterlineCarrier() == null ? 0 : this.getInterlineCarrier().hashCode());
		result = 37 * result + (getCalculatedMiles() == null ? 0 : this.getCalculatedMiles().hashCode());
		result = 37 * result + (getInvPageCount() == null ? 0 : this.getInvPageCount().hashCode());
		result = 37 * result + (getInvoiceIsaNumber() == null ? 0 : this.getInvoiceIsaNumber().hashCode());
		return result;
	}

}
