package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpNspCarrierCreditTbId generated by hbm2java
 */
@Embeddable
public class ShpNspCarrierCreditTbId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal creditId;
	private BigDecimal customerId;
	private BigDecimal carrierId;
	private String creditType;
	private String status;
	private String carrierRef;
	private BigDecimal totalCrAmount;
	private BigDecimal usedCrAmount;
	private BigDecimal remainingCrAmount;
	private String comments;
	private Date createDate;
	private String createUser;
	private Date lastUpdateDate;
	private String lastUpdateUser;
	private BigDecimal currencyId;

	public ShpNspCarrierCreditTbId() {
	}

	public ShpNspCarrierCreditTbId(BigDecimal creditId, BigDecimal customerId, BigDecimal carrierId, String creditType,
			String status, String carrierRef, BigDecimal totalCrAmount, BigDecimal usedCrAmount,
			BigDecimal remainingCrAmount, String comments, Date createDate, String createUser, Date lastUpdateDate,
			String lastUpdateUser, BigDecimal currencyId) {
		this.creditId = creditId;
		this.customerId = customerId;
		this.carrierId = carrierId;
		this.creditType = creditType;
		this.status = status;
		this.carrierRef = carrierRef;
		this.totalCrAmount = totalCrAmount;
		this.usedCrAmount = usedCrAmount;
		this.remainingCrAmount = remainingCrAmount;
		this.comments = comments;
		this.createDate = createDate;
		this.createUser = createUser;
		this.lastUpdateDate = lastUpdateDate;
		this.lastUpdateUser = lastUpdateUser;
		this.currencyId = currencyId;
	}

	@Column(name = "CREDIT_ID", precision = 22, scale = 0)
	public BigDecimal getCreditId() {
		return this.creditId;
	}

	public void setCreditId(BigDecimal creditId) {
		this.creditId = creditId;
	}

	@Column(name = "CUSTOMER_ID", precision = 22, scale = 0)
	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CARRIER_ID", precision = 22, scale = 0)
	public BigDecimal getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(BigDecimal carrierId) {
		this.carrierId = carrierId;
	}

	@Column(name = "CREDIT_TYPE", length = 20)
	public String getCreditType() {
		return this.creditType;
	}

	public void setCreditType(String creditType) {
		this.creditType = creditType;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CARRIER_REF", length = 20)
	public String getCarrierRef() {
		return this.carrierRef;
	}

	public void setCarrierRef(String carrierRef) {
		this.carrierRef = carrierRef;
	}

	@Column(name = "TOTAL_CR_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getTotalCrAmount() {
		return this.totalCrAmount;
	}

	public void setTotalCrAmount(BigDecimal totalCrAmount) {
		this.totalCrAmount = totalCrAmount;
	}

	@Column(name = "USED_CR_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getUsedCrAmount() {
		return this.usedCrAmount;
	}

	public void setUsedCrAmount(BigDecimal usedCrAmount) {
		this.usedCrAmount = usedCrAmount;
	}

	@Column(name = "REMAINING_CR_AMOUNT", precision = 22, scale = 0)
	public BigDecimal getRemainingCrAmount() {
		return this.remainingCrAmount;
	}

	public void setRemainingCrAmount(BigDecimal remainingCrAmount) {
		this.remainingCrAmount = remainingCrAmount;
	}

	@Column(name = "COMMENTS", length = 500)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER", length = 20)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "LAST_UPDATE_DATE", length = 7)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "LAST_UPDATE_USER", length = 20)
	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	@Column(name = "CURRENCY_ID", precision = 22, scale = 0)
	public BigDecimal getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(BigDecimal currencyId) {
		this.currencyId = currencyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpNspCarrierCreditTbId))
			return false;
		ShpNspCarrierCreditTbId castOther = (ShpNspCarrierCreditTbId) other;

		return ((this.getCreditId() == castOther.getCreditId()) || (this.getCreditId() != null
				&& castOther.getCreditId() != null && this.getCreditId().equals(castOther.getCreditId())))
				&& ((this.getCustomerId() == castOther.getCustomerId()) || (this.getCustomerId() != null
						&& castOther.getCustomerId() != null && this.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getCarrierId() == castOther.getCarrierId()) || (this.getCarrierId() != null
						&& castOther.getCarrierId() != null && this.getCarrierId().equals(castOther.getCarrierId())))
				&& ((this.getCreditType() == castOther.getCreditType()) || (this.getCreditType() != null
						&& castOther.getCreditType() != null && this.getCreditType().equals(castOther.getCreditType())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getCarrierRef() == castOther.getCarrierRef()) || (this.getCarrierRef() != null
						&& castOther.getCarrierRef() != null && this.getCarrierRef().equals(castOther.getCarrierRef())))
				&& ((this.getTotalCrAmount() == castOther.getTotalCrAmount())
						|| (this.getTotalCrAmount() != null && castOther.getTotalCrAmount() != null
								&& this.getTotalCrAmount().equals(castOther.getTotalCrAmount())))
				&& ((this.getUsedCrAmount() == castOther.getUsedCrAmount())
						|| (this.getUsedCrAmount() != null && castOther.getUsedCrAmount() != null
								&& this.getUsedCrAmount().equals(castOther.getUsedCrAmount())))
				&& ((this.getRemainingCrAmount() == castOther.getRemainingCrAmount())
						|| (this.getRemainingCrAmount() != null && castOther.getRemainingCrAmount() != null
								&& this.getRemainingCrAmount().equals(castOther.getRemainingCrAmount())))
				&& ((this.getComments() == castOther.getComments()) || (this.getComments() != null
						&& castOther.getComments() != null && this.getComments().equals(castOther.getComments())))
				&& ((this.getCreateDate() == castOther.getCreateDate()) || (this.getCreateDate() != null
						&& castOther.getCreateDate() != null && this.getCreateDate().equals(castOther.getCreateDate())))
				&& ((this.getCreateUser() == castOther.getCreateUser()) || (this.getCreateUser() != null
						&& castOther.getCreateUser() != null && this.getCreateUser().equals(castOther.getCreateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate())
						|| (this.getLastUpdateDate() != null && castOther.getLastUpdateDate() != null
								&& this.getLastUpdateDate().equals(castOther.getLastUpdateDate())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser())
						|| (this.getLastUpdateUser() != null && castOther.getLastUpdateUser() != null
								&& this.getLastUpdateUser().equals(castOther.getLastUpdateUser())))
				&& ((this.getCurrencyId() == castOther.getCurrencyId())
						|| (this.getCurrencyId() != null && castOther.getCurrencyId() != null
								&& this.getCurrencyId().equals(castOther.getCurrencyId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCreditId() == null ? 0 : this.getCreditId().hashCode());
		result = 37 * result + (getCustomerId() == null ? 0 : this.getCustomerId().hashCode());
		result = 37 * result + (getCarrierId() == null ? 0 : this.getCarrierId().hashCode());
		result = 37 * result + (getCreditType() == null ? 0 : this.getCreditType().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getCarrierRef() == null ? 0 : this.getCarrierRef().hashCode());
		result = 37 * result + (getTotalCrAmount() == null ? 0 : this.getTotalCrAmount().hashCode());
		result = 37 * result + (getUsedCrAmount() == null ? 0 : this.getUsedCrAmount().hashCode());
		result = 37 * result + (getRemainingCrAmount() == null ? 0 : this.getRemainingCrAmount().hashCode());
		result = 37 * result + (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result + (getCreateDate() == null ? 0 : this.getCreateDate().hashCode());
		result = 37 * result + (getCreateUser() == null ? 0 : this.getCreateUser().hashCode());
		result = 37 * result + (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate().hashCode());
		result = 37 * result + (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser().hashCode());
		result = 37 * result + (getCurrencyId() == null ? 0 : this.getCurrencyId().hashCode());
		return result;
	}

}
