package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShpZipcodeTimezoneTb generated by hbm2java
 */
@Entity
@Table(name = "SHP_ZIPCODE_TIMEZONE_TB")
public class ShpZipcodeTimezoneTb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ShpZipcodeTimezoneTbId id;

	public ShpZipcodeTimezoneTb() {
	}

	public ShpZipcodeTimezoneTb(ShpZipcodeTimezoneTbId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "city", column = @Column(name = "CITY", length = 30) ),
			@AttributeOverride(name = "state", column = @Column(name = "STATE", length = 2) ),
			@AttributeOverride(name = "zipcode", column = @Column(name = "ZIPCODE", length = 10) ),
			@AttributeOverride(name = "areacode", column = @Column(name = "AREACODE", length = 3) ),
			@AttributeOverride(name = "countyFips", column = @Column(name = "COUNTY_FIPS", length = 5) ),
			@AttributeOverride(name = "countyName", column = @Column(name = "COUNTY_NAME", length = 30) ),
			@AttributeOverride(name = "preferredFlag", column = @Column(name = "PREFERRED_FLAG", length = 1) ),
			@AttributeOverride(name = "timezone", column = @Column(name = "TIMEZONE", length = 5) ),
			@AttributeOverride(name = "dstFlag", column = @Column(name = "DST_FLAG", length = 1) ),
			@AttributeOverride(name = "zipcodeTypeFlag", column = @Column(name = "ZIPCODE_TYPE_FLAG", length = 1) ),
			@AttributeOverride(name = "latitude", column = @Column(name = "LATITUDE", precision = 22, scale = 0) ),
			@AttributeOverride(name = "longitude", column = @Column(name = "LONGITUDE", precision = 22, scale = 0) ) })
	public ShpZipcodeTimezoneTbId getId() {
		return this.id;
	}

	public void setId(ShpZipcodeTimezoneTbId id) {
		this.id = id;
	}

}
