package com.envista.msi.api.domain.freight;
// Generated Jul 6, 2015 6:18:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShpZipcodeTimezoneTbId generated by hbm2java
 */
@Embeddable
public class ShpZipcodeTimezoneTbId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String city;
	private String state;
	private String zipcode;
	private String areacode;
	private String countyFips;
	private String countyName;
	private Character preferredFlag;
	private String timezone;
	private Character dstFlag;
	private Character zipcodeTypeFlag;
	private BigDecimal latitude;
	private BigDecimal longitude;

	public ShpZipcodeTimezoneTbId() {
	}

	public ShpZipcodeTimezoneTbId(String city, String state, String zipcode, String areacode, String countyFips,
			String countyName, Character preferredFlag, String timezone, Character dstFlag, Character zipcodeTypeFlag,
			BigDecimal latitude, BigDecimal longitude) {
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.areacode = areacode;
		this.countyFips = countyFips;
		this.countyName = countyName;
		this.preferredFlag = preferredFlag;
		this.timezone = timezone;
		this.dstFlag = dstFlag;
		this.zipcodeTypeFlag = zipcodeTypeFlag;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Column(name = "CITY", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIPCODE", length = 10)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "AREACODE", length = 3)
	public String getAreacode() {
		return this.areacode;
	}

	public void setAreacode(String areacode) {
		this.areacode = areacode;
	}

	@Column(name = "COUNTY_FIPS", length = 5)
	public String getCountyFips() {
		return this.countyFips;
	}

	public void setCountyFips(String countyFips) {
		this.countyFips = countyFips;
	}

	@Column(name = "COUNTY_NAME", length = 30)
	public String getCountyName() {
		return this.countyName;
	}

	public void setCountyName(String countyName) {
		this.countyName = countyName;
	}

	@Column(name = "PREFERRED_FLAG", length = 1)
	public Character getPreferredFlag() {
		return this.preferredFlag;
	}

	public void setPreferredFlag(Character preferredFlag) {
		this.preferredFlag = preferredFlag;
	}

	@Column(name = "TIMEZONE", length = 5)
	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	@Column(name = "DST_FLAG", length = 1)
	public Character getDstFlag() {
		return this.dstFlag;
	}

	public void setDstFlag(Character dstFlag) {
		this.dstFlag = dstFlag;
	}

	@Column(name = "ZIPCODE_TYPE_FLAG", length = 1)
	public Character getZipcodeTypeFlag() {
		return this.zipcodeTypeFlag;
	}

	public void setZipcodeTypeFlag(Character zipcodeTypeFlag) {
		this.zipcodeTypeFlag = zipcodeTypeFlag;
	}

	@Column(name = "LATITUDE", precision = 22, scale = 0)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", precision = 22, scale = 0)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShpZipcodeTimezoneTbId))
			return false;
		ShpZipcodeTimezoneTbId castOther = (ShpZipcodeTimezoneTbId) other;

		return ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
				&& this.getCity().equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getZipcode() == castOther.getZipcode()) || (this.getZipcode() != null
						&& castOther.getZipcode() != null && this.getZipcode().equals(castOther.getZipcode())))
				&& ((this.getAreacode() == castOther.getAreacode()) || (this.getAreacode() != null
						&& castOther.getAreacode() != null && this.getAreacode().equals(castOther.getAreacode())))
				&& ((this.getCountyFips() == castOther.getCountyFips()) || (this.getCountyFips() != null
						&& castOther.getCountyFips() != null && this.getCountyFips().equals(castOther.getCountyFips())))
				&& ((this.getCountyName() == castOther.getCountyName()) || (this.getCountyName() != null
						&& castOther.getCountyName() != null && this.getCountyName().equals(castOther.getCountyName())))
				&& ((this.getPreferredFlag() == castOther.getPreferredFlag())
						|| (this.getPreferredFlag() != null && castOther.getPreferredFlag() != null
								&& this.getPreferredFlag().equals(castOther.getPreferredFlag())))
				&& ((this.getTimezone() == castOther.getTimezone()) || (this.getTimezone() != null
						&& castOther.getTimezone() != null && this.getTimezone().equals(castOther.getTimezone())))
				&& ((this.getDstFlag() == castOther.getDstFlag()) || (this.getDstFlag() != null
						&& castOther.getDstFlag() != null && this.getDstFlag().equals(castOther.getDstFlag())))
				&& ((this.getZipcodeTypeFlag() == castOther.getZipcodeTypeFlag())
						|| (this.getZipcodeTypeFlag() != null && castOther.getZipcodeTypeFlag() != null
								&& this.getZipcodeTypeFlag().equals(castOther.getZipcodeTypeFlag())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this.getLatitude() != null
						&& castOther.getLatitude() != null && this.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this.getLongitude() != null
						&& castOther.getLongitude() != null && this.getLongitude().equals(castOther.getLongitude())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getZipcode() == null ? 0 : this.getZipcode().hashCode());
		result = 37 * result + (getAreacode() == null ? 0 : this.getAreacode().hashCode());
		result = 37 * result + (getCountyFips() == null ? 0 : this.getCountyFips().hashCode());
		result = 37 * result + (getCountyName() == null ? 0 : this.getCountyName().hashCode());
		result = 37 * result + (getPreferredFlag() == null ? 0 : this.getPreferredFlag().hashCode());
		result = 37 * result + (getTimezone() == null ? 0 : this.getTimezone().hashCode());
		result = 37 * result + (getDstFlag() == null ? 0 : this.getDstFlag().hashCode());
		result = 37 * result + (getZipcodeTypeFlag() == null ? 0 : this.getZipcodeTypeFlag().hashCode());
		result = 37 * result + (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result + (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		return result;
	}

}
